// Unified learning path and progressive-disclosure shell. Engines own learner evidence.
(function(){
'use strict';
const KEY='harumalLearningPathV1',L=(ko,ja,en,zh)=>({ko,ja,en,zh}[S.lang]||en),h=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stageIds=['hangul','foundation','topik1','topik2','advanced'];
let settingsOpen=false,settingsReturn=null,settingsScroll=0,priorOverflow='',inertNodes=[],lastView='home';
function prefs(){try{const v=JSON.parse(localStorage.getItem(KEY)||'{}'),legacy=JSON.parse(localStorage.getItem('malbitProductPrefsV1')||'{}').learningPath,oldStage=legacy==='topik1'?'topik1':legacy==='topik2'?'topik2':'hangul';return {stage:stageIds.includes(v.stage)?v.stage:oldStage,goal:stageIds.includes(v.goal)?v.goal:'advanced',palette:['mint','peach','lavender'].includes(v.palette)?v.palette:'mint'}}catch(e){return {stage:'hangul',goal:'advanced',palette:'mint'}}}
function save(changes){try{localStorage.setItem(KEY,JSON.stringify({...prefs(),...changes}));return true}catch(e){toast(L('변경을 저장하지 못했어요. 저장 공간을 확인해 주세요.','変更を保存できませんでした。空き容量を確認してください。','Could not save. Check browser storage.','保存失败，请检查浏览器存储空间。'));return false}}
function stages(){return [
{id:'hangul',number:'01',title:L('한글 첫걸음','ハングルの第一歩','First steps in Hangul','韩文第一步'),copy:L('소리와 글자 · 읽기 · 따라 쓰기','音と文字・読む・なぞる','Sounds & letters · read · trace','声音和字母 · 阅读 · 描写'),lesson:L('한글의 소리와 글자','ハングルの音と文字','Hangul sounds and letters','韩文字母与发音'),mark:'가'},
{id:'foundation',number:'02',title:L('기초 한국어','基礎韓国語','Korean foundations','基础韩语'),copy:L('기초 단어 · 문법 · 짧은 문장','基本単語・文法・短い文','Core words · grammar · short sentences','基础词汇 · 语法 · 短句'),lesson:L('뜻이 보이는 기초 문법','意味が見える基礎文法','Understand basic grammar','理解基础语法'),mark:'나'},
{id:'topik1',number:'03',title:'TOPIK I',copy:L('1–2급 목표 · 듣기와 읽기','1〜2級を目指す・聴解と読解','Aim for levels 1–2 · listening & reading','目标1–2级 · 听力与阅读'),lesson:L('TOPIK I 듣기·읽기 연습','TOPIK I 聴解・読解の練習','TOPIK I listening & reading','TOPIK I 听力与阅读练习'),mark:'I'},
{id:'topik2',number:'04',title:L('TOPIK II 중급','TOPIK II 中級','TOPIK II intermediate','TOPIK II 中级'),copy:L('3–4급 목표 · 이해와 문장 연결','3〜4級を目指す・理解と文のつながり','Aim for levels 3–4 · meaning & connections','目标3–4级 · 理解与句子衔接'),lesson:L('핵심 의미부터 연결하기','中心の意味をつなげる','Connect the main ideas','连接核心含义'),mark:'II'},
{id:'advanced',number:'05',title:L('TOPIK II 고급','TOPIK II 上級','TOPIK II advanced','TOPIK II 高级'),copy:L('5–6급 목표 · 추론과 논리 전개','5〜6級を目指す・推論と論理展開','Aim for levels 5–6 · inference & arguments','目标5–6级 · 推理与论证'),lesson:L('글의 근거로 추론하기','文章の根拠から推論する','Infer from evidence in a text','根据文章依据推理'),mark:'✦'}]}
function current(){return stages().find(s=>s.id===prefs().stage)||stages()[0]}
function row(title,copy,action,mark='›',extra=''){return `<button type="button" class="hubRow" ${extra} onclick="${action}"><span><b>${title}</b>${copy?`<small>${copy}</small>`:''}</span><i aria-hidden="true">${mark}</i></button>`}
function head(title,back='home'){return `<header class="hubPageHead"><button class="hubBack" aria-label="${L('뒤로','戻る','Back','返回')}" onclick="setView('${back}')">‹</button><h1>${title}</h1></header>`}
function art(name,cls=''){return `<img class="hubMascot ${cls}" src="assets/art/haruman/${name}-v2.webp" width="120" height="120" alt="" decoding="async">`}
function reward(){const state=window.HARUMAL_REWARDS?.getState()||{xp:0,coins:0};return {...state,...(window.HARUMAL_REWARDS?.levelInfo(state.xp)||{level:1,currentXp:0,nextXp:100,remaining:100})}}
function hasResume(){try{const id=prefs().stage;if(id==='hangul'){const b=JSON.parse(localStorage.getItem('malbitBeginnerV1')||'{}');return !!(b.known?.length||b.quiz||b.correct||(Array.isArray(b.readingV2?.completed)&&b.readingV2.completed.length)||Number(b.readingV2?.index)>0||b.readingV2?.confirmed===true||Number(b.blocksV1?.reveal)>1||Number(b.blocksV1?.index)>0)}if(id==='foundation')return !!JSON.parse(localStorage.getItem('malbitBeginnerV1')||'{}').grammarV1?.lastLesson;if(id==='topik1'){const q=JSON.parse(localStorage.getItem('topikQuestTopik1Session')||'null');return !!(q&&!q.result&&Number(q.examLevel||1)===1)}const g=window.HARUMAL_GROWTH?.getState();return Object.values(g?.sessions||{}).some(s=>s.recipeId===(id==='advanced'?'inference':'gist'))}catch(e){return false}}
function continueLabel(){return hasResume()?L('이어서 학습','学習を続ける','Continue learning','继续学习'):L('학습 시작','学習を始める','Start learning','开始学习')}
function compact(){const r=reward();return `<button type="button" class="harumalCompactStatus palette-${prefs().palette}" data-hub-action="profile" onclick="HARUMAL_HUB.openProfile()" aria-label="${L('내 정보와 학습 기록 열기','プロフィールと学習記録を開く','Open profile and learning record','打开个人信息与学习记录')}">${art('progress-proud')}<span class="hubStatusMain"><span><b>Lv. ${r.level}</b><small>${L('나의 학습','私の学習','My learning','我的学习')}</small></span><progress max="${r.nextXp}" value="${r.currentXp}" aria-label="${L('활동 경험치','活動経験値','Activity XP','活动经验值')}"></progress><small>${r.currentXp} / ${r.nextXp} XP</small></span><span class="hubCoins"><b>◉ ${r.coins}</b><small>${L('내 정보','マイページ','Profile','个人信息')} ›</small></span></button>`}
function home(sc){const s=current();sc.className='screen hubHome';sc.innerHTML=`<header class="hubHomeHeader"><div class="hubWordmark">하루말<span>harumal</span></div><button type="button" class="harumalSettingsTrigger" aria-label="${L('설정 열기','設定を開く','Open settings','打开设置')}" onclick="HARUMAL_HUB.openSettings()">${gear()}</button></header>${compact()}<section class="hubCurrent"><div class="hubLessonTop"><span class="hubEyebrow">${L('지금의 한 걸음','今の一歩','YOUR NEXT STEP','现在的一步')}</span><button class="hubTextButton" data-hub-action="path" onclick="HARUMAL_HUB.openPath()">${L('전체 과정','全コース','Course path','全部课程')} ›</button></div><div class="hubLessonBody"><div><small>${h(s.title)}</small><h1>${h(s.lesson)}</h1><p>${h(s.copy)}</p></div>${art('home-study')}</div><button class="hubPrimary" data-hub-action="continue" onclick="HARUMAL_HUB.continueLearning()">${continueLabel()} <span>→</span></button></section><p class="hubGoal">${L('나의 목표','私の目標','My goal','我的目标')} · ${h(stages().find(x=>x.id===prefs().goal).title)}</p><section class="hubSecondary">${row(L('빠른 어휘','クイック単語','Quick vocabulary','快速词汇'),L('단어 문제만 가볍게','単語問題だけ、気軽に','Short word questions','轻松练习短词汇题'),"tqStartMode('shorts')",'↗','data-hub-action="shorts"')}${row(L('다른 연습','ほかの練習','More practice','其他练习'),L('영역별 · 시험 · 상황과 이야기','分野別・試験・場面と物語','Skills · exam · situations & stories','专项 · 考试 · 情景与故事'),"HARUMAL_HUB.openPractice()",'›','data-hub-action="practice"')}</section>`}
function path(sc){sc.className='screen hubPath';const p=prefs();sc.innerHTML=head(L('나의 학습 과정','私の学習コース','Your learning path','我的学习课程'))+`<p class="hubIntro">${L('한글부터 TOPIK II까지. 아는 단계는 건너뛰어도 괜찮아요.','ハングルからTOPIK IIまで。知っている段階から始められます。','From Hangul to TOPIK II. Start at the stage that fits you.','从韩文到TOPIK II，可以从适合自己的阶段开始。')}</p><ol class="hubPathList">${stages().map(s=>`<li class="${s.id===p.stage?'isCurrent':''}"><button onclick="HARUMAL_HUB.showStage('${s.id}')"><i>${s.mark}</i><span><small>STEP ${s.number}${s.id===p.stage?' · '+L('현재 선택','現在選択中','Selected','当前选择'):''}</small><b>${s.title}</b><small>${s.copy}</small></span><em>›</em></button></li>`).join('')}</ol><p class="hubNote">${L('단계 선택은 실력 인증이 아니에요. 단계별로 기존 연습을 연결했으며, 모든 단원이 완성된 정규 과정은 아니에요.','段階の選択は実力認定ではありません。既存の練習をつないだ構成で、全単元完成のコースではありません。','Choosing a stage is not a proficiency assessment. Existing practice is organized by stage; this is not a fully authored end-to-end course.','选择阶段并非能力认证。当前按阶段整合现有练习，尚非所有单元均已完成的完整课程。')}</p>`}
function stage(sc){const s=current();sc.className='screen hubStage';const items=s.id==='hangul'?[[L('글자와 소리 익히기','文字と音を学ぶ','Letters and sounds','学习字母与发音'),L('모음 · 자음 · 읽기 · 손글씨','母音・子音・読み・手書き','Vowels · consonants · reading · handwriting','元音 · 辅音 · 阅读 · 手写'),"harumalCourse('beginner')"]]:s.id==='foundation'?[[L('기초 문법','基礎文法','Basic grammar','基础语法'),L('설명과 예문을 보고 직접 써요','説明と例文を見て書く','Read examples and write','阅读说明与例句后书写'),"malbitOpenGrammar()"],[L('한 문장부터 쓰기','一文から書く','Write one sentence','从一句话开始写'),L('현재 열린 소단원부터','公開済みの単元から','Start with the available unit','从已开放的小单元开始'),"harumalWritingGo('course')"],[L('단어의 뜻 발견하기','単語の意味を発見','Discover word meanings','发现词义'),L('비교하고 새 상황에서 확인','比べて新しい場面で確かめる','Compare, then try a new situation','比较后在新情景中确认'),"HARUMAL_GROWTH.open('meaning')"]]:[
[L('단계별 이해 연습','段階的な理解練習','Guided understanding','分步理解练习'),L('직접 만든 예제로 방법을 익혀요','オリジナル例題で方法を学ぶ','Learn the method with authored examples','用原创例题学习方法'),`HARUMAL_GROWTH.open('${s.id==='advanced'?'inference':s.id==='topik2'?'gist':'meaning'}')`],
[L('듣기·읽기 실전','聴解・読解の実戦','Listening & reading practice','听力与阅读实战'),s.id==='topik1'?'TOPIK I':L('TOPIK II 공통 문제 풀기','TOPIK II 共通問題','Shared TOPIK II question pool','TOPIK II 共用题库'),`HARUMAL_HUB.exam(${s.id==='topik1'?1:2},'random')`],
...(s.id==='topik1'?[]:[[L('쓰기 연습','作文練習','Writing practice','写作练习'),L('기초 문장 과정 · 시험 쓰기 유형','基礎文のコース・試験作文形式','Sentence course · exam writing formats','基础句子课程 · 考试写作题型'),"harumalWritingGo('course')"]]),
[L('모의고사','模擬試験','Mock exam','模拟考试'),L('전체 또는 영역별로 확인','全体または分野別に確認','Full exam or by section','全套或分项测试'),`HARUMAL_HUB.exam(${s.id==='topik1'?1:2},'real')`]];
sc.innerHTML=head(s.title,'courseMap')+`<section class="hubStageLead"><span class="hubStageMark">${s.mark}</span><div><small>STEP ${s.number}</small><h2>${s.lesson}</h2><p>${s.copy}</p></div></section><button class="hubPrimary" data-hub-action="continue" onclick="HARUMAL_HUB.continueLearning()">${L('이 단계 학습하기','この段階を学ぶ','Study this stage','学习此阶段')} →</button><h2 class="hubSectionTitle">${L('이 단계에서 할 수 있는 연습','この段階の練習','Practice in this stage','此阶段的练习')}</h2><div class="hubRowGroup">${items.map(x=>row(...x)).join('')}</div>${s.id==='advanced'?`<p class="hubNote">${L('고급 단계도 TOPIK II 문제 은행을 함께 사용해요. 고급 쓰기 전체 과정은 아직 준비 중이에요.','上級もTOPIK IIの問題を共用します。上級作文の全コースは準備中です。','Advanced practice shares the TOPIK II bank. A complete advanced writing course is still in preparation.','高级阶段共用TOPIK II题库，完整高级写作课程仍在准备中。')}</p>`:''}`}
function practice(sc){sc.className='screen hubPractice';sc.innerHTML=head(L('다른 연습','ほかの練習','More practice','其他练习'))+`<p class="hubIntro">${L('오늘 필요한 연습만 골라요.','今日必要な練習を選ぼう。','Choose the practice you need today.','选择今天需要的练习。')}</p><h2 class="hubSectionTitle">${L('짧게 연습','短く練習','Quick practice','短时练习')}</h2><div class="hubRowGroup">${row(L('빠른 어휘','クイック単語','Quick vocabulary','快速词汇'),L('어휘 문제만 빠르게','単語問題だけを素早く','Fast vocabulary-only questions','快速练习词汇题'),"tqStartMode('shorts')",'↗','data-hub-action="shorts"')}${row(L('기초 문법','基礎文法','Basic grammar','基础语法'),L('예문과 짧은 쓰기','例文と短い作文','Examples & short writing','例句与短句书写'),"malbitOpenGrammar()")}${row(L('한 문장부터 쓰기','一文から書く','Write one sentence','从一句话开始写'),L('문장 능력 지도와 소단원','文章力マップと単元','Sentence map & units','句子能力地图与小单元'),"harumalWritingGo('course')")}${row(L('말하기 · 따라 읽기','話す・音読する','Speak & repeat','口语 · 跟读'),L('듣고 소리 내어 읽기','聞いて声に出す','Listen and read aloud','听音并朗读'),"setView('speaking')")}${row(L('뜻을 발견하는 연습','意味を発見する練習','Explore meaning','发现含义的练习'),L('선택된 11개 소단원','11の選定単元','11 selected mini-units','精选11个小单元'),"HARUMAL_GROWTH.open('all')",'›','data-hub-action="growth"')}</div><h2 class="hubSectionTitle">${L('시험 연습','試験練習','Exam practice','考试练习')}</h2><div class="hubRowGroup">${row('TOPIK I',L('1–2급 · 듣기와 읽기','1〜2級・聴解と読解','Levels 1–2 · listening & reading','1–2级 · 听力与阅读'),"HARUMAL_HUB.showStage('topik1')")}${row('TOPIK II',L('3–6급 · 듣기·읽기·쓰기','3〜6級・聴解・読解・作文','Levels 3–6 · listening, reading & writing','3–6级 · 听力、阅读、写作'),"HARUMAL_HUB.showStage('topik2')")}</div><h2 class="hubSectionTitle">${L('상황과 이야기','場面と物語','Situations & stories','情景与故事')}</h2><div class="hubRowGroup">${row(L('여행 한국어','旅の韓国語','Travel Korean','旅行韩语'),L('이동 · 식사 · 부탁 · 조건 비교','移動・食事・お願い・条件比較','Travel · meals · requests · conditions','出行 · 用餐 · 请求 · 条件比较'),"setView('travel')",'›','data-hub-action="travel"')}${row(L('워드라이트 원정','ワードライト遠征','Wordlight Expedition','词光远征'),L('기존 모험과 기록 이어가기','これまでの冒険を続ける','Continue your saved adventure','继续已有的冒险与记录'),"tqStartMode('game')")}</div>`}
function profile(sc){sc.className='screen hubProfile';sc.innerHTML=head(L('내 정보','マイページ','My profile','个人信息'))+compact()+`<p class="hubNote">${L('레벨은 학습 활동 기록이에요. 한국어 실력이나 TOPIK 등급 인증과는 달라요. 기록은 이 브라우저에 저장돼요.','レベルは学習活動の記録です。韓国語力やTOPIK級の認定ではありません。このブラウザに保存されます。','Levels track learning activity, not Korean proficiency or a TOPIK certification. Records are saved in this browser.','等级记录学习活动，不代表韩语能力或TOPIK等级认证。记录保存在此浏览器。')}</p><div class="hubRowGroup">${row(L('학습 기록','学習記録','Learning record','学习记录'),L('실제로 연습한 내용 확인','実際に練習した記録を見る','See your actual practice history','查看实际练习记录'),"setView('stats')")}${row(L('학습 단계와 목표','学習段階と目標','Stage and goal','学习阶段与目标'),current().title,"HARUMAL_HUB.openPath()")}</div><h2 class="hubSectionTitle">${L('프로필 색상','プロフィールの色','Profile color','个人资料颜色')}</h2><div class="hubPalettes">${['mint','peach','lavender'].map((p,i)=>`<button class="palette-${p} ${prefs().palette===p?'selected':''}" onclick="HARUMAL_HUB.setPalette('${p}')" aria-pressed="${prefs().palette===p}">${[L('민트','ミント','Mint','薄荷'),L('피치','ピーチ','Peach','蜜桃'),L('라벤더','ラベンダー','Lavender','薰衣草')][i]}</button>`).join('')}</div><p class="hubNote">${L('기본 색상은 무료예요. 코인은 모을 수 있으며, 코인 상점과 다이어리 스티커 구매는 아직 제공하지 않아요.','基本色は無料です。コインは貯められますが、ショップと日記ステッカーの購入は未提供です。','Basic colors are free. You can collect coins; a coin shop and diary sticker purchases are not available yet.','基础颜色免费。金币可以积累，金币商店与日记贴纸购买尚未开放。')}</p>`}
function review(sc){if(sc.querySelector('.hubReviewLinks'))return;const box=document.createElement('section');box.className='hubReviewLinks';box.innerHTML=`<h2 class="hubSectionTitle">${L('다시 떠올릴 시간','思い出す時間','Time to recall','回想的时间')}</h2><div class="hubRowGroup">${row(L('저장한 단어 복습','保存した単語を復習','Review saved words','复习收藏单词'),L('단어장에서 뜻을 떠올려요','単語帳で意味を思い出す','Recall meanings in your wordbook','在单词本中回想词义'),"setView('vocab')")}${row(L('여행 표현 복습','旅の表現を復習','Review travel phrases','复习旅行表达'),L('풀었던 장면에서 다시 말해요','学んだ場面でもう一度','Revisit your practiced scenes','复习已练习的情景'),"setView('travel')")}</div><h2 class="hubSectionTitle">${L('시험 오답 다시 풀기','試験の間違いを解き直す','Retry exam mistakes','重做考试错题')}</h2>`;sc.prepend(box)}
function gear(){return '<svg width="24" height="24" viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><polygon points="21.78,9.92 21.78,14.08 19.23,14.35 18.77,15.45 20.39,17.45 17.45,20.39 15.45,18.77 14.35,19.23 14.08,21.78 9.92,21.78 9.65,19.23 8.55,18.77 6.55,20.39 3.61,17.45 5.23,15.45 4.77,14.35 2.22,14.08 2.22,9.92 4.77,9.65 5.23,8.55 3.61,6.55 6.55,3.61 8.55,5.23 9.65,4.77 9.92,2.22 14.08,2.22 14.35,4.77 15.45,5.23 17.45,3.61 20.39,6.55 18.77,8.55 19.23,9.65"/><circle cx="12" cy="12" r="3.25"/></svg>'}
function languagePicker(){
 const label=L('설명 언어','説明の言語','Explanation language','说明语言');
 const choices=[['ko',L('한국어','韓国語','Korean','韩语')],['ja',L('일본어','日本語','Japanese','日语')],['en',L('영어','英語','English','英语')],['zh',L('중국어','中国語','Chinese','中文')]];
 return `<div class="hubSettingLanguage"><span id="hubLanguageLabel">${label}</span><div class="hubLanguageOptions" role="group" aria-labelledby="hubLanguageLabel">${choices.map(([id,name])=>`<button type="button" class="hubLanguageOption" data-hub-language="${id}" aria-label="${h(name)}" title="${h(name)}" aria-pressed="${S.lang===id}" onclick="malbitSetLanguage('${id}')">${window.HARUMAL_UI.languageFlag(id)}<span class="hubLanguageCheck" aria-hidden="true">✓</span></button>`).join('')}</div></div>`;
}
function chrome(){document.body.classList.add('hubRedesign');document.body.dataset.hubView=S.view;for(const button of document.querySelectorAll('.tqLang,#flagBtn,.tqStatsHeader button[onclick*="flagMenu"],.t1GameLang,.t1ModeLang,.wcLanguage')){button.hidden=true;button.style.display='none';if(button.closest('#screen')&&!button.parentElement.querySelector('.harumalSettingsTrigger')){const gearButton=document.createElement('button');gearButton.type='button';gearButton.className='harumalSettingsTrigger';gearButton.onclick=openSettings;gearButton.innerHTML=gear();button.after(gearButton)}}const header=document.querySelector('.toprow');if(header&&!header.querySelector('.harumalSettingsTrigger')){const b=document.createElement('button');b.className='harumalSettingsTrigger';b.type='button';b.onclick=openSettings;b.innerHTML=gear();header.append(b)}for(const b of document.querySelectorAll('.harumalSettingsTrigger'))b.setAttribute('aria-label',L('설정 열기','設定を開く','Open settings','打开设置'));const topGear=document.querySelector('.toprow .harumalSettingsTrigger');if(topGear)topGear.hidden=!!document.querySelector('#screen .harumalSettingsTrigger');const selected=window.HARUMAL_UI.activeTab(S.view);for(const b of document.querySelectorAll('.nav button')){const active=b.id==='nav_'+selected;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')}const title=document.querySelector('.top .title small');if(title)title.textContent=L('한글부터 TOPIK II까지','ハングルからTOPIK IIまで','From Hangul to TOPIK II','从韩文到TOPIK II');}
function ensureDialog(){let dialog=document.getElementById('harumalSettingsDialog');if(dialog)return dialog;dialog=document.createElement('div');dialog.id='harumalSettingsDialog';dialog.className='hubSettingsOverlay';dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.setAttribute('aria-labelledby','hubSettingsTitle');dialog.hidden=true;dialog.innerHTML='<section class="hubSettingsSheet"><header class="hubSettingsHead"><h2 id="hubSettingsTitle"></h2><button type="button" data-hub-action="close-settings" onclick="HARUMAL_HUB.closeSettings()">×</button></header><div class="hubSettingsContent"></div></section>';dialog.addEventListener('click',event=>{if(event.target===dialog)closeSettings()});dialog.addEventListener('click',event=>{const action=event.target.closest('button')?.getAttribute('onclick')||'';if(/malbitOpenSupport|malbitOpenLegal|malbitOpenAccount/.test(action))closeSettings();},true);dialog.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();closeSettings()}if(event.key==='Tab'){const items=[...dialog.querySelectorAll('button,input,select,summary,a[href]')].filter(n=>!n.disabled&&n.getClientRects().length),first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}});document.body.append(dialog);return dialog}
function fillSettings(){const dialog=ensureDialog(),content=dialog.querySelector('.hubSettingsContent'),oldScroll=content.scrollTop,focused=document.activeElement,focusKey=content.contains(focused)?focused.getAttribute('onchange')||focused.getAttribute('onclick'):null;const expanded=[...content.querySelectorAll('details[open]')].map(n=>n.dataset.settingKey).filter(Boolean);dialog.querySelector('h2').textContent=L('설정','設定','Settings','设置');dialog.querySelector('[data-hub-action="close-settings"]').setAttribute('aria-label',L('설정 닫기','設定を閉じる','Close settings','关闭设置'));content.innerHTML='';const stageOptions=stages().map(s=>`<option value="${s.id}" ${prefs().goal===s.id?'selected':''}>${h(s.title)}</option>`).join('');content.innerHTML=`<section class="hubSettingBasics">${languagePicker()}<label>${L('학습 목표','学習目標','Learning goal','学习目标')}<select onchange="HARUMAL_HUB.setGoal(this.value)">${stageOptions}</select></label><label>${L('화면 모드','画面モード','Appearance','显示模式')}<select onchange="malbitSetTheme(this.value)">${[['system',L('기기 설정','システム','System','跟随系统')],['light',L('밝게','ライト','Light','浅色')],['dark',L('어둡게','ダーク','Dark','深色')]].map(([id,name])=>`<option value="${id}" ${document.documentElement.dataset.themeMode===id?'selected':''}>${name}</option>`).join('')}</select></label></section>`;
const old=document.createElement('div');window.morePage(old);old.querySelectorAll('.malbitPageTitle,.malbitAccountCard,.malbitThemeSetting').forEach(n=>n.remove());const first=old.querySelector('.malbitSetting');if(first?.querySelector('.malbitLangGrid'))first.remove();let i=0;for(const node of [...old.children]){if(node.tagName==='DETAILS'){content.append(node);continue}const title=node.querySelector('h2,h3,summary');if(!title){content.append(node);continue}const details=document.createElement('details');details.className='hubSettingsGroup';details.dataset.settingKey=String(i++);details.open=expanded.includes(details.dataset.settingKey);const summary=document.createElement('summary');summary.textContent=title.textContent;details.append(summary);title.remove();details.append(node);content.append(details)}content.scrollTop=oldScroll;if(focusKey)[...content.querySelectorAll('[onchange],[onclick]')].find(n=>(n.getAttribute('onchange')||n.getAttribute('onclick'))===focusKey)?.focus({preventScroll:true});window.MALBIT_TTS?.refreshSettings?.();chrome();}
function openSettings(){if(settingsOpen)return;settingsOpen=true;settingsReturn=document.activeElement;settingsScroll=window.scrollY;priorOverflow=document.body.style.overflow;const dialog=ensureDialog();fillSettings();dialog.hidden=false;inertNodes=[...document.body.children].filter(n=>n!==dialog&&n.tagName!=='SCRIPT'&&n.tagName!=='STYLE').map(n=>[n,n.inert]);for(const [node] of inertNodes)node.inert=true;document.body.style.overflow='hidden';history.pushState({...history.state,harumalSettings:true},'');dialog.querySelector('button').focus();}
function closeSettings(pop=true){if(!settingsOpen)return;window.MALBIT_TTS?.cancel?.();settingsOpen=false;ensureDialog().hidden=true;document.body.style.overflow=priorOverflow;for(const [node,was] of inertNodes)node.inert=was;inertNodes=[];window.scrollTo?.(0,settingsScroll);(settingsReturn?.isConnected&&settingsReturn.getClientRects().length?settingsReturn:[...document.querySelectorAll('.harumalSettingsTrigger')].find(n=>n.getClientRects().length&&!n.hidden))?.focus?.();if(pop&&history.state?.harumalSettings)history.back();}
window.addEventListener('popstate',()=>{if(settingsOpen&&!history.state?.harumalSettings)closeSettings(false)});
function renderHub(){const sc=document.getElementById('screen');if(!sc)return;if(S.view==='home'||S.view==='learn')home(sc);else if(S.view==='courseMap')path(sc);else if(S.view==='courseStage')stage(sc);else if(S.view==='practiceHub')practice(sc);else if(S.view==='profile')profile(sc);else if(S.view==='review')review(sc);else if(S.view==='more'){S.view='home';window.save?.();home(sc);if(!settingsOpen)openSettings()}if(S.view==='vocab'&&!S.vocab?.length&&!sc.querySelector('.hubDiaryEmpty')){const img=document.createElement('img');img.src='assets/harumal/ui/vocab-diary-empty-v1.webp';img.className='hubDiaryEmpty';img.width=96;img.height=96;img.alt='';sc.prepend(img)}chrome();if(settingsOpen){fillSettings();document.body.style.overflow='hidden'}lastView=S.view;}
const base=window.render;window.render=function(){const r=base.apply(this,arguments);renderHub();return r};
window.HARUMAL_HUB=Object.freeze({storageKey:KEY,openSettings,closeSettings,openProfile:()=>setView('profile'),openPath:()=>setView('courseMap'),openPractice:()=>setView('practiceHub'),showStage:id=>{if(stageIds.includes(id)&&save({stage:id}))setView('courseStage')},chooseStage:id=>{if(stageIds.includes(id)&&save({stage:id}))setView('home')},setGoal:id=>{if(stageIds.includes(id)&&save({goal:id}))render()},setPalette:id=>{if(['mint','peach','lavender'].includes(id)&&save({palette:id}))render()},exam:(level,mode)=>{tqSetLevel(level);tqStartMode(mode)},continueLearning:()=>{const id=prefs().stage;if(id==='hangul')harumalCourse('beginner');else if(id==='foundation')malbitOpenGrammar();else if(id==='topik1'){tqSetLearningPath('topik1');tqHomeContinue()}else HARUMAL_GROWTH.open(id==='advanced'?'inference':'gist')},getState:prefs,stages});
window.addEventListener('harumal:rewards-change',()=>{if(['home','learn','profile'].includes(S.view))renderHub()});
renderHub();
})();
