const $=id=>document.getElementById(id);
const LANGS={ko:{flag:'🇰🇷',name:'한국어'},ja:{flag:'🇯🇵',name:'日本語'},en:{flag:'🇺🇸',name:'English'},zh:{flag:'🇨🇳',name:'中文'}};
const UI={
 home:{ko:'홈',ja:'ホーム',en:'Home',zh:'首页'}, game:{ko:'게임',ja:'ゲーム',en:'Game',zh:'游戏'}, review:{ko:'복습',ja:'復習',en:'Review',zh:'复习'}, vocab:{ko:'단어장',ja:'単語帳',en:'Vocab',zh:'单词本'}, more:{ko:'더보기',ja:'その他',en:'More',zh:'更多'},
 real:{ko:'실전모드',ja:'実戦モード',en:'Real Exam',zh:'实战模式'}, infinity:{ko:'인피니티',ja:'インフィニティ',en:'Infinity',zh:'无限模式'}, audioLab:{ko:'듣기 제작실',ja:'聴解制作室',en:'Listening Lab',zh:'听力制作室'},
 start:{ko:'시작',ja:'スタート',en:'Start',zh:'开始'}, continue:{ko:'이어하기',ja:'続きから',en:'Continue',zh:'继续'}, next:{ko:'다음',ja:'次へ',en:'Next',zh:'下一题'}, prev:{ko:'이전',ja:'前へ',en:'Previous',zh:'上一题'}, submit:{ko:'제출',ja:'提出',en:'Submit',zh:'提交'}, explain:{ko:'해설 보기',ja:'解説を見る',en:'Explanation',zh:'查看解析'}, close:{ko:'닫기',ja:'閉じる',en:'Close',zh:'关闭'},
 answer:{ko:'정답',ja:'正解',en:'Answer',zh:'正确答案'}, translation:{ko:'번역/해석',ja:'訳',en:'Translation',zh:'翻译'}, grammar:{ko:'문법 포인트',ja:'文法ポイント',en:'Grammar',zh:'语法要点'}, words:{ko:'어휘 포인트',ja:'語彙ポイント',en:'Vocabulary',zh:'词汇要点'}, why:{ko:'풀이 포인트',ja:'解き方・誤答ポイント',en:'Why this answer',zh:'解题要点'},
 locked:{ko:'잠김',ja:'ロック',en:'Locked',zh:'未解锁'}, clear:{ko:'클리어',ja:'クリア',en:'Clear',zh:'通关'}, timeover:{ko:'시간 초과',ja:'TIME OVER',en:'Time over',zh:'时间到'}, correct:{ko:'정답!',ja:'正解！',en:'Correct!',zh:'答对了！'}, wrong:{ko:'오답',ja:'不正解',en:'Wrong',zh:'答错了'},
 listening:{ko:'듣기',ja:'聴解',en:'Listening',zh:'听力'}, writing:{ko:'쓰기',ja:'作文',en:'Writing',zh:'写作'}, reading:{ko:'읽기',ja:'読解',en:'Reading',zh:'阅读'},
};
function tr(k){return (UI[k]&&UI[k][S.lang])||k}
function ml(ko,ja,en,zh){return ({ko,ja,en,zh})[S.lang]||ko}
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function fmt(sec){sec=Math.max(0,Math.round(sec||0));let m=Math.floor(sec/60),s=sec%60,h=Math.floor(m/60);m%=60;if(h)return `${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;return `${m}:${String(s).padStart(2,'0')}`}
const DEFAULT={lang:'ko',view:'home',gameUnlock:1,gameWorld:1,gameExamLevel:2,gameAnswers:{},realAnswers:{listen:{},read:{}},writing:{},vocab:[],rwAnswers:{},lsAnswers:{},transCache:{},infinity:null,speaking:{mode:'read',index:0,last:null}};
let S=JSON.parse(JSON.stringify(DEFAULT));
try{Object.assign(S,JSON.parse(localStorage.getItem('topikQuestV8')||'{}'))}catch(e){}
function save(){try{localStorage.setItem('topikQuestV8',JSON.stringify(S))}catch(e){}}
let timerId=null, qStart=0, qLimit=0, qTimerKind='', selected=null, speechBusy=false, selectedText='', activeAudio=null, audioFallbackToken=0, speechRec=null, speakingStart=0, devRecorder=null, devStream=null, devChunks=[], devRecordingId=null, devBlobs={};
function stopTimer(){if(timerId)clearInterval(timerId);timerId=null;qStart=0;qLimit=0;qTimerKind=''}
function startQuestionTimer(limit,kind){stopTimer();qStart=Date.now();qLimit=limit;qTimerKind=kind;timerId=setInterval(tickTimer,250);tickTimer()}
function tickTimer(){if(!qStart)return;let el=$('liveTimer'),bar=$('timeBar');if(!el)return;let elapsed=(Date.now()-qStart)/1000,left=Math.max(0,qLimit-elapsed),pct=Math.max(0,left/qLimit*100);el.textContent='⏱ '+fmt(left);el.classList.toggle('danger',pct<15);if(bar){bar.style.width=pct+'%';bar.className=pct<25?'low':''}if(left<=0){stopTimer();if(qTimerKind==='game')gameTimeout();else if(qTimerKind==='infinity')infTimeout()}}
function elapsed(){return qStart?Math.max(1,Math.round((Date.now()-qStart)/1000)):0}
function setProgress(v){$('progressBar').style.width=Math.max(0,Math.min(100,v))+'%'}
function stopListeningAudio(){audioFallbackToken++;try{speechSynthesis.cancel()}catch(e){};speechBusy=false;if(activeAudio){try{activeAudio.pause();activeAudio.currentTime=0}catch(e){};activeAudio=null}}
function setView(v){stopTimer();stopListeningAudio();S.view=v;save();render()}
function flagMenu(){ $('flagMenu').classList.toggle('open') }
function setLang(l){S.lang=l;save();$('flagMenu').classList.remove('open');renderShell();render()}
function renderShell(){ $('flagBtn').textContent=LANGS[S.lang].flag; let labels={home:tr('home'),review:tr('review'),speaking:ml('말하기','話す','Speaking','口语'),vocab:tr('vocab'),more:tr('more')}; Object.keys(labels).forEach(k=>{let b=$('nav_'+k);if(b)b.querySelector('span').textContent=labels[k]}); document.querySelectorAll('.flagOpt').forEach(b=>b.classList.toggle('active',b.dataset.lang===S.lang)) }
function navActive(k){document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));let el=$('nav_'+k);if(el)el.classList.add('active')}
function stageBg(n){return ASSETS[`stage${((n-1)%3)+1}.webp`]}
function mascot(state='fresh'){return ASSETS[`monster_${state}.webp`]}
function render(){hideSelection();renderShell();let sc=$('screen');sc.innerHTML='';if(S.view==='home')return home(sc);if(S.view==='game')return gameMap(sc);if(S.view==='gameQ')return gameQuestion(sc);if(S.view==='realSetup')return realSetup(sc);if(S.view==='real')return realQuestion(sc);if(S.view==='infinity')return infQuestion(sc);if(S.view==='speaking')return speakingPage(sc);if(S.view==='devStudio')return developerStudio(sc);if(S.view==='vocab')return vocabPage(sc);if(S.view==='review')return reviewPage(sc);if(S.view==='more')return morePage(sc);home(sc)}
function home(sc){navActive('home');setProgress(0);sc.innerHTML=`
<div class="sectionTitle" style="margin-top:2px"><h2>MALBIT · 말빛</h2><span>TOPIK I · II</span></div>
<div class="modeGrid three">
<button class="modeCard" onclick="startRandomPractice()"><div class="modeIcon">🎲</div><span class="chip">RANDOM</span><b>${ml('랜덤 실전','ランダム実戦','Random Practice','随机实战')}</b><p>${ml('듣기·읽기·쓰기를 랜덤하게 한 문제씩 풉니다.','聴解・読解・作文を1問ずつランダムに解きます。','Solve randomized listening, reading, and writing questions.','随机练习听力、阅读和写作题。')}</p></button>
<button class="modeCard" onclick="setView('game')"><div class="modeIcon">⚔️</div><span class="chip">STAGE</span><b>${ml('게임모드','ゲームモード','Game Mode','游戏模式')}</b><p>${ml('몬스터와 스테이지를 차례로 클리어합니다.','モンスターとステージを順番に攻略。','Clear monster stages in order.','按顺序挑战怪物关卡。')}</p></button>
<button class="modeCard" onclick="window.startShorts?startShorts():setView('home')"><div class="modeIcon">⚡</div><span class="chip">SHORTS</span><b>${ml('숏츠 모드','ショーツモード','Shorts Mode','短题模式')}</b><p>${ml('한국어 단어·어휘·문법을 내 언어 보기로 빠르게 맞힙니다.','韓国語の単語・語彙・文法を自分の言語の選択肢で素早く解きます。','Rapid Korean vocab and grammar with choices in your language.','用自己的语言选项快速练习韩语词汇与语法。')}</p></button>
</div>
<div class="sectionTitle"><h2>${ml('오늘의 실전','今日の実戦','Exam practice','今日实战')}</h2><span>FULL + SECTION</span></div>
<section class="examModeHero"><img src="${ASSETS['exam_student.png']}" alt="exam student"><div class="examCopy"><span class="eyebrow">TOPIK II · EXAM MODE</span><h1>${tr('real')}</h1><p>${ml('몬스터 없이 실제 시험장 분위기로 집중합니다. 전체 실전 또는 듣기·읽기·쓰기만 따로 도전할 수 있습니다.','モンスターなしの試験会場コンセプト。フル実戦または各領域だけ挑戦できます。','A focused exam-room mode with full or section-only challenges.','无怪物的真实考场氛围，可挑战全套或单项。')}</p><button class="primary" onclick="setView('realSetup')">▶ ${ml('실전 선택','実戦を選ぶ','Choose exam','选择实战')}</button></div></section>
<div class="infoCard"><h3>🎙 ${ml('말하기 연습','スピーキング練習','Speaking practice','口语练习')}</h3><p>${ml('대본 읽기와 듣고 따라하기에서 마이크로 발음을 인식하고 학습 점수를 확인할 수 있습니다.','台本読み・聞いて真似る練習で音声認識による学習スコアを確認できます。','Read aloud or shadow a model voice and get a learning score from speech recognition.','朗读或跟读示范音频，并通过语音识别获得学习评分。')}</p><button class="primary alt" onclick="setView('speaking')">🎙 ${ml('말하기 시작','話す練習','Start speaking','开始口语')}</button></div>`}
function morePage(sc){navActive('more');let dev=new URLSearchParams(location.search).get('dev')==='studio';sc.innerHTML=`<div class="sectionTitle"><h2>${tr('more')}</h2></div><div class="modeGrid"><button class="modeCard wideCard" onclick="resetAll()"><div class="modeIcon">↺</div><div><b>${ml('진행 초기화','進行状況を初期化','Reset progress','重置进度')}</b><p>${ml('기기에 저장된 스테이지·오답·단어장 기록을 삭제합니다.','端末に保存されたステージ・誤答・単語帳を削除します。','Delete saved stages, mistakes, and vocabulary on this device.','删除本机保存的关卡、错题和单词本。')}</p></div></button>${dev?`<button class="modeCard wideCard" onclick="setView('devStudio')"><div class="modeIcon">🔒</div><div><b>Developer Listening Studio</b><p>Recording scripts and audio file mapping.</p></div></button>`:''}</div>`}
function resetAll(){if(confirm(ml('진행 기록을 모두 삭제할까요?','進行状況をすべて削除しますか？','Delete all saved progress?','删除所有已保存的进度吗？'))){S=JSON.parse(JSON.stringify(DEFAULT));save();render()}}
// GAME MODE
function stageMeta(st){if(st<=50)return{type:'read',id:st};if(st<=54)return{type:'write',id:st};return{type:'listen',id:st-54}}
function gameLimit(st){let m=stageMeta(st);if(m.type==='read'){let n=m.id;if(n<=4)return 28;if(n<=12)return 38;if(n<=24)return 50;if(n<=38)return 70;if(n<=47)return 85;return 105}if(m.type==='listen'){let q=LS[m.id-1];return Math.max(35,Math.round((q.recommendedSec||60)*.82))}if(m.id<=52)return 180;if(m.id===53)return 540;return 1200}
function worldFor(st){return Math.floor((st-1)/10)+1}
function worldRange(w){let a=(w-1)*10+1,b=Math.min(104,w*10);return[a,b]}
function gameMap(sc){navActive('game');setProgress((S.gameUnlock-1)/103*100);let maxWorld=11,w=Math.max(1,Math.min(maxWorld,S.gameWorld||worldFor(S.gameUnlock))),range=worldRange(w),unlockedWorld=worldFor(S.gameUnlock);let cleared=0;for(let st=range[0];st<=range[1];st++)if(S.gameAnswers[st]?.clear)cleared++;let mstate=cleared===0?'fresh':cleared<4?'hurt':cleared<range[1]-range[0]?'critical':'dead';sc.innerHTML=`<div class="stageHero"><div class="bg" style="background-image:url('${stageBg(w)}')"></div><div class="shade"></div><div class="copy"><span class="eyebrow">WORLD ${w} / ${maxWorld}</span><h2>${worldTitle(w)}</h2><p>${worldDesc(w)}</p></div><img class="stageMonster" src="${mascot(mstate)}"></div><div class="actionRow" style="grid-template-columns:48px 1fr 48px;margin-bottom:12px"><button class="sideBtn" onclick="changeWorld(-1)">‹</button><button class="attack" onclick="startGameStage(${Math.min(S.gameUnlock,range[1])})">▶ ${tr('continue')} · STAGE ${S.gameUnlock}</button><button class="sideBtn" onclick="changeWorld(1)">›</button></div><div class="stageGrid">${Array.from({length:range[1]-range[0]+1},(_,i)=>{let st=range[0]+i,locked=st>S.gameUnlock,cl=S.gameAnswers[st]?.clear;return `<button class="stageBtn ${locked?'locked':''} ${cl?'clear':''} ${st===S.gameUnlock?'current':''}" ${locked?'disabled':''} onclick="startGameStage(${st})">${locked?'🔒':st}<small>${cl?'✓':''}</small></button>`}).join('')}</div><div class="infoCard"><h3>⚔️ GAME RULE</h3><p>${ml('정답을 맞혀야 다음 스테이지가 해금됩니다. 난이도별 제한시간이 적용되며, 쓰기 스테이지는 최소 작성 기준을 채워 제출하면 클리어됩니다.','正解すると次のステージが解放。制限時間は難易度別。作文ステージは最低文字数を満たして提出するとクリア扱いです。','A correct answer unlocks the next stage. Time limits scale with difficulty. Writing stages clear after meeting the minimum writing requirement and submitting.','答对后解锁下一关。限时按难度调整。写作关达到最低字数并提交即可通关。')}</p></div>`}
function changeWorld(d){S.gameWorld=Math.max(1,Math.min(11,(S.gameWorld||1)+d));save();render()}
function worldTitle(w){let ko=['문법의 광장','문장의 동굴','추론의 길','고급 독해탑','파이널 성문','작문의 왕국','듣기 마을','듣기 서재','듣기 협곡','듣기 성채','마지막 청해탑'];let ja=['文法の広場','文章の洞窟','推論の道','上級読解塔','ファイナル城門','作文王国','聴解の村','聴解書庫','聴解峡谷','聴解城塞','最終聴解塔'];let en=['Grammar Plaza','Sentence Cave','Inference Road','Advanced Reading Tower','Final Gate','Writing Kingdom','Listening Village','Listening Library','Listening Canyon','Listening Fortress','Final Listening Tower'];let zh=['语法广场','句子洞窟','推理之路','高级阅读塔','最终城门','写作王国','听力村庄','听力书库','听力峡谷','听力城塞','最终听力塔'];return ({ko,ja,en,zh})[S.lang][w-1]}
function worldDesc(w){return w<=5?'READING STAGES':w===6?'WRITING BOSS STAGES':'LISTENING STAGES'}
function startGameStage(st){if(st>S.gameUnlock)return;S.gameExamLevel=2;S.gameStage=st;S.view='gameQ';save();render()}
function monsterState(st){let [a,b]=worldRange(worldFor(st)),done=0;for(let s=a;s<=b;s++)if(S.gameAnswers[s]?.clear)done++;let hp=Math.max(0,100-Math.round(done/(b-a+1)*100));return{hp,state:hp===0?'dead':hp<=35?'critical':hp<=70?'hurt':'fresh'}}
function gameQuestion(sc){navActive('game');S.gameExamLevel=2;let st=S.gameStage,m=stageMeta(st),ms=monsterState(st),limit=gameLimit(st);setProgress((st-1)/103*100);let body='';if(m.type==='read')body=renderMCQ(RW[m.id-1],'read',false);else if(m.type==='listen')body=renderListening(LS[m.id-1],false);else body=renderWriting(RW[m.id-1],false);sc.innerHTML=`<div class="hud"><span>TOPIK II · STAGE ${st}/104</span><span>⚡ ${difficulty(limit)}</span><span id="liveTimer" class="timer">⏱ ${fmt(limit)}</span></div><div class="countdown"><i id="timeBar"></i></div><div class="battle"><img id="monsterPic" class="monsterImg" src="${mascot(ms.state)}"><div><b>${worldTitle(worldFor(st))} · BLUE FOX</b><div class="hp"><i style="width:${ms.hp}%"></i></div><small>HP ${ms.hp}% · ${ms.state.toUpperCase()}</small></div></div>${body}`;selected=null;bindMCQ('game');if(m.type==='write')bindWrite(m.id,'game');startQuestionTimer(limit,'game')}
function difficulty(sec){if(sec<=35)return'EASY';if(sec<=55)return'NORMAL';if(sec<=85)return'HARD';return'EXPERT'}
function gameTimeout(){let st=S.gameStage;S.gameAnswers[st]={clear:false,timeout:true,time:gameLimit(st)};save();render();setTimeout(()=>openGameResult(false,true),150)}
function gameSubmit(){let st=S.gameStage,m=stageMeta(st),sec=elapsed();stopTimer();if(m.type==='write'){let txt=(S.writing[m.id]||'').trim(),need=m.id<=52?8:m.id===53?180:520;if(txt.length<need){toast((S.lang==='ja'?'もう少し書いてください。':'조금 더 작성해 주세요.'));startQuestionTimer(Math.max(15,gameLimit(st)-sec),'game');return}S.gameAnswers[st]={clear:true,time:sec};unlockNext(st);save();flashMonster();render();setTimeout(()=>openGameResult(true,false),180);return}let q=m.type==='read'?RW[m.id-1]:LS[m.id-1];if(selected==null){toast(S.lang==='ja'?'答えを選んでください。':'답을 선택해 주세요.');return}let ok=selected===q.answerIndex;S.gameAnswers[st]={clear:ok,selected,time:sec};if(ok)unlockNext(st);save();flashMonster();render();setTimeout(()=>openGameResult(ok,false),180)}
function unlockNext(st){if(st===S.gameUnlock&&st<104)S.gameUnlock=st+1}
function flashMonster(){let p=$('monsterPic');if(p)p.src=mascot('attack')}
function openGameResult(ok,timeout){let st=S.gameStage,m=stageMeta(st),q=m.type==='read'?RW[m.id-1]:m.type==='listen'?LS[m.id-1]:RW[m.id-1];let extra=timeout?tr('timeover'):ok?tr('correct'):tr('wrong');$('sheetBody').innerHTML=`<div class="reward"><b>${extra}</b><small>STAGE ${st} · ${ok?'UNLOCK +1':'RETRY'}</small></div>${m.type==='write'?`<h3>${S.lang==='ja'?'模範解答':'모범답안'}</h3><div class="answerBox"><p>${esc(q.model)}</p></div>`:`<h3>${tr('answer')}</h3><div class="answerBox"><p>${esc(q.answer||(['①','②','③','④'][q.answerIndex]))}</p></div>`}<button class="primary" style="margin-top:15px" onclick="closeSheet();${ok?`startGameStage(${Math.min(104,st+1)})`:`startGameStage(${st})`}">${ok?tr('next'):ml('재도전','リトライ','Retry','重试')}</button><button class="closeBtn" onclick="explainCurrent('${m.type}',${m.id})">${tr('explain')}</button>`;$('overlay').classList.add('open')}
// RENDER QUESTION CARDS
function instructionRW(n){if(n<=2)return'※ [1~2] (   )에 들어갈 가장 알맞은 것을 고르십시오. (각 2점)';if(n<=4)return'※ [3~4] 밑줄 친 부분과 의미가 가장 비슷한 것을 고르십시오. (각 2점)';if(n<=8)return'※ [5~8] 다음은 무엇에 대한 글인지 가장 알맞은 것을 고르십시오. (각 2점)';if(n<=12)return'※ [9~12] 다음 글 또는 안내의 내용과 같은 것을 고르십시오. (각 2점)';if(n<=15)return'※ [13~15] 다음 문장을 순서대로 맞게 배열한 것을 고르십시오. (각 2점)';if(n<=18)return'※ [16~18] 다음 문장이 들어갈 곳으로 가장 알맞은 것을 고르십시오. (각 2점)';if(n<=47)return`※ [${Math.max(19,n-(n%2?0:1))}~${Math.min(47,n+(n%2?1:0))}] 다음 글을 읽고 물음에 답하십시오. (각 2점)`;return'※ [48~50] 다음 글을 읽고 물음에 답하십시오. (각 2점)'}
function pictureChoices(q,saved){return `<div class="pictureSelect"><img src="${ASSETS[q.image]}">${[0,1,2,3].map(i=>`<button class="picHit ${saved?.selected===i?'selected':''}" data-choice="${i}" aria-label="${i+1}번 그림"><span class="picBadge">${i+1}</span></button>`).join('')}</div>`}
function choiceTapHint(){return `<div class="doubleTapHint">${ml('한 번 탭해 선택 · 같은 답을 다시 탭하면 즉시 제출','1回タップで選択・同じ答えをもう一度タップすると提出','Tap once to select · tap the same answer again to submit','点一次选择 · 再点同一答案立即提交')}</div>`}
function renderMCQ(q,type,real){let saved=real?(type==='read'?S.realAnswers.read[q.id]:S.realAnswers.listen[q.id]):null,isPicture=type==='listen'&&q.image&&q.id<=3;return `<article class="card"><div class="instruction">${esc(type==='read'?instructionRW(q.id):q.instruction)}</div><div class="qmeta"><div class="qno">${q.id}</div><span class="cat">${esc(type==='read'?(S.lang==='ja'?q.categoryJa:q.categoryKo):tr('listening'))}</span>${!real?`<span class="pace">⏱ ${fmt(type==='read'?gameLimit(q.id):q.recommendedSec||60)}</span>`:''}</div><div class="stem selectable">${esc(q.stem||q.prompt)}</div>${isPicture?pictureChoices(q,saved):q.image?`<img class="listenArt" src="${ASSETS[q.image]}">`:''}${type==='listen'?audioControls(q,real):''}${isPicture?'':`<div class="choices">${q.choices.map((c,i)=>`<button class="choice ${saved?.selected===i?'selected':''}" data-choice="${i}"><span class="n">${i+1}</span><span class="selectable">${esc(c.replace(/^[①②③④]\s*/,''))}</span></button>`).join('')}</div>`}${choiceTapHint()}${real?'':`<div class="questionMiniNav"><button onclick="gameBack()">‹ ${tr('prev')}</button><button onclick="gameNextMaybe()">${tr('next')} ›</button></div>`}</article>`}
function renderListening(q,real){return renderMCQ(q,'listen',real)}
function renderWriting(q,real){let v=S.writing[q.id]||'';let instr=q.id<=52?'※ [51~52] 다음을 읽고 ㉠과 ㉡에 들어갈 말을 각각 한 문장으로 쓰십시오. (각 10점)':q.id===53?'※ [53] 다음을 참고하여 200~300자로 글을 쓰십시오. 단, 글의 제목을 쓰지 마십시오. (30점)':'※ [54] 다음을 주제로 하여 자신의 생각을 600~700자로 글을 쓰십시오. (50점)';return `<article class="card"><div class="instruction">${instr}</div><div class="qmeta"><div class="qno">${q.id}</div><span class="cat">${tr('writing')}</span></div><div class="stem selectable">${esc(q.stem)}</div><textarea id="writeBox" class="write" placeholder="${ml('여기에 답안을 작성하세요','ここに答案を書いてください','Write your answer here','请在这里作答')}">${esc(v)}</textarea><div class="counter"><span>${ml('자동 저장','自動保存','Auto-save','自动保存')}</span><b id="charCount">${v.replace(/\n/g,'').length}${q.max?` / ${q.min}~${q.max}`:''}</b></div>${real?'':`<div class="actionRow"><button class="sideBtn" onclick="gameBack()">‹</button><button class="attack" onclick="gameSubmit()">✍ ${ml('작성 완료','作成完了','Finish writing','完成写作')}</button><button class="sideBtn" onclick="gameNextMaybe()">›</button></div>`}</article>`}
function bindMCQ(context){const buttons=[...document.querySelectorAll('[data-choice]')],active=buttons.find(b=>b.classList.contains('selected'));selected=active?Number(active.dataset.choice):null;buttons.forEach(b=>b.onclick=()=>{const next=Number(b.dataset.choice);if(selected===next){if(context==='real'){realSaveChoice(next);return realMove(1)}if(context==='game')return gameSubmit();if(context==='inf')return submitInfinity()}selected=next;buttons.forEach(x=>x.classList.remove('selected'));b.classList.add('selected');if(context==='real')realSaveChoice(selected)})}
function bindWrite(id,context){let ta=$('writeBox');if(!ta)return;ta.oninput=()=>{S.writing[id]=ta.value;save();let c=$('charCount');if(c)c.textContent=ta.value.replace(/\n/g,'').length+(RW[id-1].max?` / ${RW[id-1].min}~${RW[id-1].max}`:'')}}
function gameBack(){if(S.gameStage>1&&S.gameStage-1<=S.gameUnlock)startGameStage(S.gameStage-1)}function gameNextMaybe(){if(S.gameStage+1<=S.gameUnlock)startGameStage(S.gameStage+1);else toast(tr('locked'))}
function audioControls(q,real){let played=real&&S.real?.audioPlayed?.[q.id];return `<button id="audioBtn" class="audioBtn ${played?'locked':''}" ${played?'disabled':''} onclick="playListening(${q.id},${real?'true':'false'})">${played?'🔒 '+ml('재생 완료','再生済み','Played','已播放'):'▶ '+ml(real?'문제 음성 1회 재생':'문제 음성 재생',real?'問題音声を1回再生':'問題音声を再生',real?'Play once':'Play audio',real?'播放1次':'播放音频')}</button><div class="audioHint">${real?ml('실전 듣기는 문항당 1회만 재생됩니다. 다음 문제로 이동하면 즉시 중단됩니다.','実戦聴解は1問につき1回のみ。次へ進むと即停止します。','Real listening plays once per question and stops immediately when you move on.','实战听力每题仅播放1次，进入下一题会立即停止。'):ml('등록된 녹음 음원이 있으면 그것을 우선 재생하고, 없을 때만 기기 음성을 사용합니다.','録音音源があれば優先し、無い場合のみ端末音声を使います。','Uploaded recordings play first; device TTS is fallback only.','优先播放已上传录音，没有时才使用设备TTS。')}</div><div id="audioSource" class="audioSource"></div>`}
function koVoices(){if(window.MALBIT_TTS)return window.MALBIT_TTS.voices();let vs=speechSynthesis.getVoices().filter(v=>(v.lang||'').toLowerCase().startsWith('ko'));let rank=v=>{let n=(v.name||'').toLowerCase();return /premium|enhanced|natural|neural|sora|yuna|sunhi|hyunsu/.test(n)?0:v.localService?1:2};return vs.sort((a,b)=>rank(a)-rank(b))}
function recordedAudioCandidates(id){let n=String(id).padStart(3,'0');return [`audio/topik2/q${n}.mp3`,`audio/topik2/q${n}.m4a`,`audio/topik2/q${n}.aac`,`audio/topik2/q${n}.webm`]}
async function findRecordedAudio(id){for(let u of recordedAudioCandidates(id)){try{let r=await fetch(u,{method:'HEAD',cache:'no-store'});if(r.ok)return u}catch(e){}}return null}
function naturalizeLine(line){return line.replace(/\s+/g,' ').replace(/([.!?。！？])(?=\S)/g,'$1 ').trim()}
async function playListening(id,real){if(speechBusy)return;if(real){S.real.audioPlayed=S.real.audioPlayed||{};if(S.real.audioPlayed[id])return;S.real.audioPlayed[id]=true;save()}stopListeningAudio();let requestToken=++audioFallbackToken;speechBusy=true,q=!real&&S.infinity?.current?.bankId?infinityCurrentQuestion():LS[id-1],btn=$('audioBtn'),src=$('audioSource');if(btn){btn.classList.add('playing');btn.innerHTML='<span class="audioPlayingDot"></span>'+ml('재생 중…','再生中…','Playing…','播放中…')}let file=q?.bankId?null:await findRecordedAudio(id);if(requestToken!==audioFallbackToken)return;if(file){if(src)src.textContent='🎙 RECORDED AUDIO';let a=new Audio(file);activeAudio=a;a.onended=()=>audioDone(btn,real);a.onerror=()=>{if(requestToken===audioFallbackToken)playTTSFallback(q,btn,real)};try{await a.play();return}catch(e){if(requestToken===audioFallbackToken)return playTTSFallback(q,btn,real)}}if(requestToken===audioFallbackToken)playTTSFallback(q,btn,real)}
function audioDone(btn,real){speechBusy=false;activeAudio=null;if(btn){btn.classList.remove('playing');if(real){btn.disabled=true;btn.classList.add('locked');btn.textContent='🔒 '+ml('재생 완료','再生済み','Played','已播放')}else btn.textContent='▶ '+ml('다시 재생','もう一度再生','Replay','重新播放')}}
function playTTSFallback(q,btn,real){let src=$('audioSource');if(src)src.textContent='⚠ DEVICE TTS FALLBACK';let token=++audioFallbackToken,lines=(q.script||'').split(/\n+/).filter(Boolean),voices=koVoices(),seq=[];for(let line of lines)seq.push(line);let idx=0;function next(){if(token!==audioFallbackToken)return;if(idx>=seq.length){audioDone(btn,real);return}let line=seq[idx++],female=/^여자|여성/.test(line),male=/^남자|남성/.test(line),text=naturalizeLine(line.replace(/^[^:：]+[:：]\s*/,'')),u=window.MALBIT_TTS?window.MALBIT_TTS.utterance(text,{gender:female?'female':male?'male':''}):new SpeechSynthesisUtterance(text);if(!window.MALBIT_TTS){u.lang='ko-KR';u.rate=.82;u.pitch=1;let pick=female?voices.find(v=>/female|yuna|sora|sunhi|jimin|seohyeon|yujin/i.test(v.name||'')):male?voices.find(v=>/male|hyunsu|injoon|bongjin|gookmin/i.test(v.name||'')):voices[0];u.voice=pick||voices[0]||null}u.onend=()=>setTimeout(next,window.MALBIT_TTS?.lineDelay||380);u.onerror=()=>setTimeout(next,100);speechSynthesis.speak(u)}next()}
// REAL EXAM
function realSetup(sc){navActive('home');setProgress(0);sc.innerHTML=`<section class="examModeHero"><img src="${ASSETS['exam_student.png']}" alt="exam student"><div class="examCopy"><span class="eyebrow">TOPIK II · REAL EXAM</span><h1>${tr('real')}</h1><p>${ml('실제 시험처럼 해설 없이 시간을 재며 풉니다. 전체 시험과 영역별 도전을 선택할 수 있습니다.','本番同様、解説なしで時間を計って解きます。フル試験と領域別挑戦を選べます。','Timed exam practice without explanations. Choose full exam or a single section.','像真实考试一样计时作答，不显示解析，可选择全套或单项。')}</p></div></section><div class="sectionTitle"><h2>${ml('전체 실전','フル実戦','Full exam','全套实战')}</h2><span>180 MIN</span></div><button class="primary" onclick="beginReal('full')">▶ ${ml('듣기 → 쓰기 → 읽기 전체 시작','聴解→作文→読解を開始','Start Listening → Writing → Reading','开始听力→写作→阅读')}</button><div class="sectionTitle"><h2>${ml('개별 도전','領域別チャレンジ','Section challenge','单项挑战')}</h2><span>TOPIK II</span></div><div class="challengeGrid"><button class="challengeCard" onclick="beginReal('listen')"><div class="ci">🎧</div><div><b>${ml('듣기만 풀기','聴解だけ','Listening only','仅听力')}</b><small>50 QUESTIONS</small></div><div class="ct">60 MIN ›</div></button><button class="challengeCard" onclick="beginReal('read')"><div class="ci">📖</div><div><b>${ml('읽기만 풀기','読解だけ','Reading only','仅读写')}</b><small>50 QUESTIONS</small></div><div class="ct">70 MIN ›</div></button><button class="challengeCard" onclick="beginReal('write')"><div class="ci">✍️</div><div><b>${ml('쓰기만 풀기','作文だけ','Writing only','仅写作')}</b><small>4 QUESTIONS</small></div><div class="ct">50 MIN ›</div></button></div><div class="infoCard"><h3>🔒 ${ml('실전 규칙','実戦ルール','Exam rules','实战规则')}</h3><p>${ml('문제별 해설은 시험 종료 후에만 열립니다. 실전 듣기는 문항당 한 번만 재생되며, 다음 문제로 이동하면 재생 중인 음성이 즉시 멈춥니다.','問題ごとの解説は終了後のみ。実戦聴解は1問1回で、次へ進むと再生中の音声は即停止します。','Explanations unlock only after the exam. Listening plays once per question and stops immediately when you move on.','每题解析仅在考试结束后开放。实战听力每题仅播放一次，进入下一题时立即停止。')}</p></div>`}
function activateTopik2BankSet(set){return !!window.MALBIT_BANK?.activateTopik2Set(Number(set)||1,LS,RW)}
function beginReal(mode='full'){stopListeningAudio();let phase=mode==='read'?'read':mode==='write'?'write':'listen',id=phase==='write'?51:1,mins=phase==='listen'?60:phase==='write'?50:70,mockSet=window.MALBIT_BANK?.nextMockSet(2)||1;activateTopik2BankSet(mockSet);S.real={active:true,mode,phase,id,mockSet,deadline:Date.now()+mins*60*1000,audioPlayed:{}};S.realAnswers={listen:{},read:{}};S.writing={};S.view='real';save();render()}
function realPhaseName(){return S.real.phase==='listen'?tr('listening'):S.real.phase==='write'?tr('writing'):tr('reading')}
function realQuestion(sc){navActive('home');let r=S.real;if(!r?.active)return setView('realSetup');if(r.mockSet)activateTopik2BankSet(r.mockSet);let total=r.phase==='listen'?50:r.phase==='write'?4:50,idx=r.phase==='write'?r.id-50:r.id,pct=(idx-1)/total*100;setProgress(pct);let remain=Math.max(0,(r.deadline-Date.now())/1000),modeLabel=r.mode==='full'?'FULL':r.phase.toUpperCase();sc.innerHTML=`<div class="examHeader"><h2>${modeLabel} · SET ${r.mockSet||1} · ${realPhaseName()} · ${idx}/${total}</h2><p>${ml('실전 중에는 해설을 표시하지 않습니다. 답안은 자동 저장됩니다.','実戦中は解説を表示しません。答案は自動保存。','No explanations during the exam. Answers are auto-saved.','考试中不显示解析，答案自动保存。')}</p><div id="realTimer" class="examTimer">${fmt(remain)}</div></div>`;if(r.phase==='listen')sc.innerHTML+=renderMCQ(LS[r.id-1],'listen',true);else if(r.phase==='read')sc.innerHTML+=renderMCQ(RW[r.id-1],'read',true);else sc.innerHTML+=renderWriting(RW[r.id-1],true);sc.innerHTML+=`<div class="examNav"><button class="prev" onclick="realMove(-1)">${tr('prev')}</button><button class="next" onclick="realMove(1)">${(r.phase==='write'?r.id===54:r.id===50)?ml('시험 종료','試験終了','Finish Exam','结束考试'):tr('next')}</button></div><div class="noExplain">🔒 ${ml('해설은 종료 후에 해금됩니다.','解説は終了後に解放。','Explanations unlock after finishing.','解析将在结束后解锁。')}</div>`;bindMCQ('real');if(r.phase==='write')bindWrite(r.id,'real');clearInterval(timerId);timerId=setInterval(realTick,250);realTick()}
function realTick(){let r=S.real;if(!r?.active)return;let left=(r.deadline-Date.now())/1000,el=$('realTimer');if(el)el.textContent=fmt(left);if(left<=0){clearInterval(timerId);advanceRealSection()}}
function realSaveChoice(i){let r=S.real,q=r.phase==='listen'?LS[r.id-1]:RW[r.id-1],entry={selected:i,bankId:q?.bankId||null};if(r.phase==='listen')S.realAnswers.listen[r.id]=entry;else if(r.phase==='read')S.realAnswers.read[r.id]=entry;save()}
function realMove(d){let r=S.real;stopListeningAudio();let max=r.phase==='write'?54:50,min=r.phase==='write'?51:1;if(d>0&&r.id>=max){advanceRealSection();return}r.id=Math.max(min,Math.min(max,r.id+d));save();render()}
function advanceRealSection(){let r=S.real;stopListeningAudio();if(r.mode!=='full'){finishReal();return}if(r.phase==='listen'){r.phase='write';r.id=51;r.deadline=Date.now()+50*60*1000;save();render();return}if(r.phase==='write'){r.phase='read';r.id=1;r.deadline=Date.now()+70*60*1000;save();render();return}finishReal()}
function writingEstimate(){let total=0;for(const id of[51,52]){const text=(S.writing[id]||'').trim(),chars=text.replace(/\s/g,'').length;total+=Math.min(10,(chars>=8?6:chars>=3?3:0)+(/[.!?。]|[다요]$/.test(text)?2:0)+(/고|며|지만|때문|위해/.test(text)?2:0))}let q53=S.writing[53]||'',c53=q53.replace(/\s/g,'').length,s53=c53>=200&&c53<=300?16:c53>=150?10:c53>=80?5:0;s53+=Math.min(8,(q53.match(/\d+(?:\.\d+)?%?/g)||[]).length*2);if(/반면|증가|감소|차이|가장|비교/.test(q53))s53+=4;if((q53.match(/\n/g)||[]).length>=1)s53+=2;total+=Math.min(30,s53);let q54=S.writing[54]||'',c54=q54.replace(/\s/g,'').length,s54=c54>=600&&c54<=750?24:c54>=480?17:c54>=300?9:0;s54+=Math.min(14,(q54.match(/따라서|그러나|또한|반면|먼저|다음으로|결국|때문|예를 들면/g)||[]).length*2);if((q54.match(/\n/g)||[]).length>=2)s54+=6;if(new Set(q54.split(/\s+/).filter(Boolean)).size>=90)s54+=6;total+=Math.min(50,s54);return Math.round(Math.min(100,total))}
function finishReal(){stopTimer();stopListeningAudio();let mode=S.real.mode||'full';if(S.real.mockSet)activateTopik2BankSet(S.real.mockSet);S.real.active=false;let l=0,r=0;for(let i=1;i<=50;i++){const la=S.realAnswers.listen[i],lq=LS[i-1],ra=S.realAnswers.read[i],rq=RW[i-1];if(la?.selected===lq.answerIndex)l+=2;if(ra?.selected===rq.answerIndex)r+=2}let w=writingEstimate();if(mode==='listen'){S.lastResult={mode,l,total:l,max:100,mockSet:S.real.mockSet};save();return showSectionResult()}if(mode==='read'){S.lastResult={mode,r,total:r,max:100,mockSet:S.real.mockSet};save();return showSectionResult()}if(mode==='write'){S.lastResult={mode,w,total:w,max:100,mockSet:S.real.mockSet};save();return showSectionResult()}let total=l+w+r,grade=total>=230?6:total>=190?5:total>=150?4:total>=120?3:0;S.lastResult={mode,l,w,r,total,grade,max:300,mockSet:S.real.mockSet};save();showResultCeremony()}
function showSectionResult(){let c=$('resultCurtain'),dr=$('drum'),card=$('resultCard'),x=S.lastResult,label=x.mode==='listen'?tr('listening'):x.mode==='read'?tr('reading'):tr('writing');c.classList.add('open');dr.style.display='block';card.classList.remove('show');playDrumRoll();setTimeout(()=>{dr.style.display='none';card.innerHTML=`<div class="eyebrow" style="color:#5b6a82">TOPIK II SECTION RESULT</div><div class="grade">${label}</div><div style="font-size:30px;font-weight:950">${x.total} / 100</div><p>${x.mode==='write'?ml('쓰기 점수는 학습용 간이 추정입니다.','作文点数は学習用の簡易推定です。','Writing is a study-only estimate.','写作分数为学习用估算。'):ml('실전 종료 후 복습에서 문항별 해설을 확인할 수 있습니다.','終了後、復習で問題別解説を確認できます。','Review item explanations after finishing.','结束后可在复习中查看逐题解析。')}</p><div class="resultActions"><button class="sub" onclick="closeResult();setView('review')">${tr('review')}</button><button class="main" onclick="closeResult();setView('home')">${tr('home')}</button></div>`;card.classList.add('show')},2200)}
function showResultCeremony(){let c=$('resultCurtain'),dr=$('drum'),card=$('resultCard');c.classList.add('open');dr.style.display='block';card.classList.remove('show');playDrumRoll();setTimeout(()=>{dr.style.display='none';let x=S.lastResult;card.innerHTML=`<div class="eyebrow" style="color:#5b6a82">TOPIK II ESTIMATED RESULT</div><div class="grade">${x.grade?x.grade+'급':'불합격'}</div><div style="font-size:26px;font-weight:950">${x.total} / 300</div><div class="scoreGrid"><div><b>${x.l}</b><small>${tr('listening')}</small></div><div><b>${x.w}</b><small>${tr('writing')}*</small></div><div><b>${x.r}</b><small>${tr('reading')}</small></div></div><p>* ${ml('쓰기 점수는 글자 수·과제어·구성 표현을 기준으로 한 학습용 간이 추정이며 공식 채점이 아닙니다.','作文点数は文字数・課題語・構成表現による学習用の簡易推定です。公式採点ではありません。','Writing is a study-only estimate based on length, task keywords, and structure. It is not official scoring.','写作分数仅依据字数、任务关键词和结构进行学习用估算，并非官方评分。')}</p><div class="resultActions"><button class="sub" onclick="closeResult();setView('review')">${tr('review')}</button><button class="main" onclick="closeResult();setView('home')">${tr('home')}</button></div>`;card.classList.add('show')},3100)}
function closeResult(){$('resultCurtain').classList.remove('open')}
function playDrumRoll(){try{let ac=new (window.AudioContext||window.webkitAudioContext)();let now=ac.currentTime;for(let i=0;i<18;i++){let t=now+i*.14,buf=ac.createBuffer(1,ac.sampleRate*.045,ac.sampleRate),d=buf.getChannelData(0);for(let j=0;j<d.length;j++)d[j]=(Math.random()*2-1)*Math.pow(1-j/d.length,2);let s=ac.createBufferSource(),g=ac.createGain();s.buffer=buf;g.gain.setValueAtTime(.05+i*.004,t);g.gain.exponentialRampToValueAtTime(.001,t+.045);s.connect(g).connect(ac.destination);s.start(t)}let o=ac.createOscillator(),g=ac.createGain();o.frequency.setValueAtTime(880,now+2.8);o.frequency.exponentialRampToValueAtTime(1320,now+3.05);g.gain.setValueAtTime(.001,now+2.8);g.gain.exponentialRampToValueAtTime(.18,now+2.82);g.gain.exponentialRampToValueAtTime(.001,now+3.25);o.connect(g).connect(ac.destination);o.start(now+2.8);o.stop(now+3.3)}catch(e){}}
// RANDOM PRACTICE
function startRandomPractice(examLevel=2){if(Number(examLevel)===1&&typeof window.tqStartMode==='function'){try{localStorage.setItem('topikQuestExamLevel','1')}catch(e){}return window.tqStartMode('random')}S.infinity={active:true,examLevel:2,count:0,graded:0,correct:0,writing:0,totalSec:0,targetSec:0,last:null,feedback:null,seenIds:[]};S.view='infinity';save();nextInfinity()}
function exitRandomPractice(){stopTimer();stopListeningAudio();S.infinity=null;save();setView('home')}
function startInfinity(){return startRandomPractice()}
function infinityDifficulties(){let inf=S.infinity,graded=Number(inf?.graded)||0,acc=graded?Number(inf.correct||0)/graded:0;if(graded<4)return['medium'];if(acc>=.82)return['hard','very_hard'];if(acc<.5)return['medium'];return['medium','hard']}
function infinityCurrentQuestion(){let x=S.infinity?.current;if(!x)return null;if(x.bankId&&window.MALBIT_BANK){let q=window.MALBIT_BANK.present(x.bankId,x.choiceOrder);if(!q)return null;return{...q,id:x.id,stem:[q.passage,q.prompt].filter(Boolean).join('\n\n'),categoryKo:q.group,categoryJa:q.group,max:x.type==='write'?(x.id<=52?100:x.id===53?300:800):undefined,min:x.type==='write'?(x.id<=52?3:x.id===53?180:500):undefined}}return x.type==='listen'?LS[x.id-1]:RW[x.id-1]}
function nextInfinity(){if(Number(S.infinity?.examLevel)!==2)return startRandomPractice(2);let inf=S.infinity,roll=Math.random(),type=inf.nextType||(Number(inf.count)<3?(roll<.5?'listen':'read'):roll<.45?'listen':roll<.9?'read':'write');delete inf.nextType;let section=type==='listen'?'listening':type==='read'?'reading':'writing',seen=Array.isArray(inf.seenIds)?inf.seenIds:[],item=window.MALBIT_BANK?.draw({level:2,sections:[section],difficulties:infinityDifficulties(),exclude:seen,recentKey:`random:2:${section}`,recentLimit:480});if(!item)item=window.MALBIT_BANK?.draw({level:2,sections:[section],exclude:seen,recentKey:`random:2:${section}`,recentLimit:480});let x;if(item){x={type,id:item.no,bankId:item.id,choiceOrder:item.section==='writing'?[]:window.MALBIT_BANK.freshOrder(item.id)};seen.push(item.id);inf.seenIds=seen.slice(-1200);if(type==='write')S.writing[item.no]=''}else{let id=type==='write'?51+Math.floor(Math.random()*4):1+Math.floor(Math.random()*50);x={type,id}}inf.current=x;inf.last=x;inf.feedback=null;save();render()}
function infLimit(x){let q=infinityCurrentQuestion();if(x.type==='write')return x.id<=52?180:x.id===53?720:1200;return Math.max(35,Math.round((q?.recommendedSec||60)*.9))}
function randomTypeName(type){return type==='listen'?tr('listening'):type==='read'?tr('reading'):tr('writing')}
function infQuestion(sc){navActive('home');let inf=S.infinity;if(!inf?.active||Number(inf.examLevel)!==2)return startRandomPractice(2);let x=inf.current,q=infinityCurrentQuestion(),lim=infLimit(x),graded=Number(inf.graded)||0;if(!q)return nextInfinity();setProgress(0);sc.innerHTML=`<div class="randomPracticeTop"><button onclick="exitRandomPractice()" aria-label="${ml('메뉴로 돌아가기','メニューに戻る','Back to menu','返回菜单')}">‹</button><div><b>${ml('랜덤 실전','ランダム実戦','Random Practice','随机实战')}</b><small>TOPIK II · ${randomTypeName(x.type)} ${x.id} · ${q.difficulty||''}</small></div></div><div class="infinityBar"><div><b>${inf.count}</b><small>QUESTIONS</small></div><div><b>${inf.correct}</b><small>CORRECT</small></div><div><b>${graded?Math.round(inf.correct/graded*100):0}%</b><small>ACC</small></div><div><b>${fmt(inf.totalSec)}</b><small>TIME</small></div></div><div class="hud"><span>TOPIK II</span><span>🎲 ${ml('랜덤 실전','ランダム実戦','RANDOM PRACTICE','随机实战')}</span><span>${randomTypeName(x.type)} ${x.id}</span><span id="liveTimer" class="timer">⏱ ${fmt(lim)}</span></div><div class="countdown"><i id="timeBar"></i></div>${x.type==='write'?renderRandomWriting(q):renderInfMCQ(q,x.type)}<button class="dangerBtn" onclick="finishInfinity()">■ ${ml('연습 종료 · 결과 보기','練習終了・結果を見る','Finish practice · Results','结束练习 · 查看结果')}</button>`;selected=null;if(x.type==='write')bindWrite(x.id,'inf');else bindMCQ('inf');if(inf.feedback)stopTimer();else startQuestionTimer(lim,'infinity')}
function renderInfMCQ(q,type){let isPicture=type==='listen'&&q.image&&q.id<=3,fb=S.infinity.feedback,instruction=q.bankId?q.instruction:(type==='read'?instructionRW(q.id):q.instruction);return `<article class="card"><div class="instruction">${esc(instruction)}</div><div class="qmeta"><div class="qno">${q.id}</div><span class="cat">${randomTypeName(type)}</span></div><div class="stem selectable">${esc(q.stem||q.prompt)}</div>${isPicture?`<div class="pictureSelect"><img src="${ASSETS[q.image]}">${[0,1,2,3].map(i=>`<button class="picHit ${fb&&i===q.answerIndex?'selected':''} ${fb&&!fb.ok&&i===fb.selected?'wrong':''}" data-choice="${i}" ${fb?'disabled':''}><span class="picBadge">${i+1}</span></button>`).join('')}</div>`:q.image?`<img class="listenArt" src="${ASSETS[q.image]}">`:''}${type==='listen'?audioControls(q,false):''}${isPicture?'':`<div class="choices">${q.choices.map((c,i)=>`<button class="choice ${fb&&i===q.answerIndex?'correct':''} ${fb&&!fb.ok&&i===fb.selected?'wrong':''}" data-choice="${i}" ${fb?'disabled':''}><span class="n">${i+1}</span><span>${esc(c.replace(/^[①②③④]\s*/,''))}</span></button>`).join('')}</div>`}${fb?`<div class="resultStrip ${fb.ok?'good':'bad'}">${fb.timeout?tr('timeover'):fb.ok?tr('correct'):tr('wrong')} · ${fb.sec}s</div><button class="primary" style="margin-top:10px" onclick="nextInfinity()">${tr('next')} →</button><button class="closeBtn" onclick="explainInfinityCurrent()">${tr('explain')}</button>`:choiceTapHint()}</article>`}
function randomWritingInstruction(q){return q.id<=52?'※ [51~52] ㉠과 ㉡에 들어갈 말을 한 문장으로 쓰십시오.':q.id===53?'※ [53] 자료를 참고하여 핵심을 요약해 쓰십시오.':'※ [54] 주제에 대한 자신의 생각과 근거를 쓰십시오.'}
function renderRandomWriting(q){let fb=S.infinity.feedback,v=S.writing[q.id]||'';return `<article class="card"><div class="instruction">${q.bankId?q.instruction:randomWritingInstruction(q)}</div><div class="qmeta"><div class="qno">${q.id}</div><span class="cat">${tr('writing')}</span></div><div class="stem selectable">${esc(q.stem)}</div>${fb?`<div class="resultStrip ${fb.timeout?'bad':'good'}">${fb.timeout?tr('timeover'):ml('작성 완료','作成完了','Writing complete','写作完成')} · ${fb.sec}s</div><h3>${ml('모범답안과 비교','模範解答と比較','Compare with the model','与参考答案比较')}</h3><div class="answerBox"><p>${esc(q.model||'')}</p></div><button class="primary" style="margin-top:10px" onclick="nextInfinity()">${tr('next')} →</button><button class="closeBtn" onclick="explainInfinityCurrent()">${tr('explain')}</button>`:`<textarea id="writeBox" class="write" placeholder="${ml('핵심만 짧게 작성해도 됩니다.','要点だけ短く書いても構いません。','A short key-point answer is enough.','只写核心要点也可以。')}">${esc(v)}</textarea><div class="counter"><span>${ml('자동 저장','自動保存','Auto-save','自动保存')}</span><b id="charCount">${v.replace(/\n/g,'').length}${q.max?` / ${q.min}~${q.max}`:''}</b></div><button class="randomWriteAction" onclick="submitInfinityWriting()">✍ ${ml('작성 완료 · 모범답안 보기','作成完了・模範解答を見る','Finish · View model answer','完成 · 查看参考答案')}</button>`}</article>`}
function submitInfinity(){if(selected==null)return toast(ml('답을 먼저 선택해 주세요.','先に答えを選んでください。','Select an answer first.','请先选择答案。'));let inf=S.infinity,x=inf.current,q=infinityCurrentQuestion(),sec=elapsed();stopTimer();let ok=selected===q.answerIndex;inf.count++;inf.graded=(Number(inf.graded)||0)+1;if(ok)inf.correct++;else try{window.MALBIT_REVIEW?.record(2,x.type==='listen'?'listen':'read',q.bankId||x.id,selected,'random',{choiceOrder:q.choiceOrder})}catch(e){}inf.totalSec+=sec;inf.targetSec+=infLimit(x);inf.feedback={ok,selected,sec};save();render()}
function submitInfinityWriting(){let inf=S.infinity,x=inf?.current;if(!inf||x?.type!=='write')return;let q=infinityCurrentQuestion(),txt=(S.writing[x.id]||'').trim(),need=x.id<=52?3:x.id===53?80:180;if(txt.length<need)return toast(ml(`조금만 더 써 주세요. 최소 ${need}자입니다.`,`もう少し書いてください。最低${need}字です。`,`Write a little more — at least ${need} characters.`,`请再写一点，至少${need}字。`));let sec=elapsed();stopTimer();inf.count++;inf.writing=(Number(inf.writing)||0)+1;inf.totalSec+=sec;inf.targetSec+=infLimit(x);inf.feedback={write:true,sec};save();render()}
function infTimeout(){let inf=S.infinity;if(!inf)return;let x=inf.current,q=infinityCurrentQuestion(),sec=infLimit(x);inf.count++;if(x.type==='write')inf.writing=(Number(inf.writing)||0)+1;else{inf.graded=(Number(inf.graded)||0)+1;try{window.MALBIT_REVIEW?.record(2,x.type==='listen'?'listen':'read',q?.bankId||x.id,-1,'random',{choiceOrder:q?.choiceOrder})}catch(e){}}inf.totalSec+=sec;inf.targetSec+=sec;inf.feedback={ok:false,write:x.type==='write',selected:selected??-1,sec,timeout:true};save();render()}
function finishInfinity(){stopTimer();let i=S.infinity;if(!i)return;let graded=Number(i.graded)||0,writing=Number(i.writing)||0,acc=graded?i.correct/graded:0,pace=i.totalSec?Math.min(1,i.targetSec/i.totalSec):0,score=graded?Math.round(acc*80+pace*20):0,cls=graded?(score>=90?'S':score>=80?'A':score>=70?'B':score>=60?'C':'D'):'–';$('sheetBody').innerHTML=`<div class="reward"><b>${ml('TOPIK II 랜덤 실전 결과','TOPIK II ランダム実戦結果','TOPIK II RANDOM PRACTICE RESULT','TOPIK II 随机实战结果')}</b><small>${i.count} QUESTIONS</small></div><div class="classBadge">${cls}</div><table class="miniTable"><tr><th>${ml('선택형 정답률','選択問題の正答率','Choice accuracy','选择题正确率')}</th><td>${graded?Math.round(acc*100):0}%</td></tr><tr><th>${ml('선택형 문제','選択問題','Choice questions','选择题')}</th><td>${graded}</td></tr><tr><th>${ml('쓰기 연습','作文練習','Writing prompts','写作练习')}</th><td>${writing}</td></tr><tr><th>${ml('총 시간','総時間','Total time','总时间')}</th><td>${fmt(i.totalSec)}</td></tr></table><button class="primary" onclick="closeSheet();startRandomPractice(2)">🎲 ${ml('다시 시작','もう一度','Again','再来一次')}</button><button class="closeBtn" onclick="closeSheet();S.infinity=null;setView('home')">${tr('close')}</button>`;$('overlay').classList.add('open')}
// EXPLANATIONS + TRANSLATION
async function explainCurrent(type,id){let q=type==='read'?RW[id-1]:type==='listen'?LS[id-1]:RW[id-1];$('sheetBody').innerHTML=`<div class="reward"><b>${tr('explain')}</b><small>${LANGS[S.lang].flag} ${LANGS[S.lang].name}</small></div><div id="expBody" class="translationLoading">${S.lang==='ja'?'解説を準備しています…':S.lang==='en'?'Preparing explanation…':S.lang==='zh'?'正在准备解析…':'해설을 준비하고 있습니다…'}</div><button class="closeBtn" onclick="closeSheet()">${tr('close')}</button>`;$('overlay').classList.add('open');let html=await buildExplanation(type,q);$('expBody').className='';$('expBody').innerHTML=html}
async function explainInfinityCurrent(){let x=S.infinity?.current,q=infinityCurrentQuestion();if(!x||!q)return;$('sheetBody').innerHTML=`<div class="reward"><b>${tr('explain')}</b><small>${LANGS[S.lang].flag} ${LANGS[S.lang].name}</small></div><div id="expBody" class="translationLoading">${S.lang==='ja'?'解説を準備しています…':S.lang==='en'?'Preparing explanation…':S.lang==='zh'?'正在准备解析…':'해설을 준비하고 있습니다…'}</div><button class="closeBtn" onclick="closeSheet()">${tr('close')}</button>`;$('overlay').classList.add('open');let html=await buildExplanation(x.type,q);$('expBody').className='';$('expBody').innerHTML=html}
async function buildExplanation(type,q){if(q?.bankId){let answer=q.section==='writing'?(q.model||''):q.choices?.[q.answerIndex]||'',base=S.lang==='ja'?(q.explanationJa||q.explanationKo):q.explanationKo||q.explanation||'',detail=(S.lang==='ko'||S.lang==='ja')?base:await translateCached(`bank_${q.bankId}_${S.lang}`,base,'ko',S.lang);if(q.section==='writing')return `<h3>${ml('모범답안','模範解答','Model answer','参考答案')}</h3><div class="answerBox"><p>${esc(answer)}</p></div><h3>${tr('why')}</h3><p>${esc(detail)}</p>`;return `<h3>${tr('answer')}</h3><div class="answerBox"><p>${esc(answer)}</p></div><h3>${tr('why')}</h3><p>${esc(detail)}</p>${q.targetSkills?.length?`<h3>${tr('words')}</h3><p>${esc(q.targetSkills.join(' · '))}</p>`:''}`}
 if(type==='listen'){let ans=q.answer||['①','②','③','④'][q.answerIndex],jaScript=q.scriptJa||q.script,jaChoice=(q.choicesJa||q.choices)[q.answerIndex]||'';let baseJa=`正解は${ans}です。音声では次の内容がポイントになります。\n${jaScript}\n\n正解選択肢：${jaChoice}`;let txt=S.lang==='ja'?baseJa:S.lang==='ko'?`정답은 ${ans}입니다. 음성의 핵심 내용과 정답 선택지를 비교하면 답을 찾을 수 있습니다.\n\n${q.script}`:await translateCached('listen_'+q.id,baseJa,'ja',S.lang);return `<h3>${tr('answer')}</h3><div class="answerBox"><p>${esc(ans)}</p></div><h3>${tr('why')}</h3><p>${esc(txt)}</p>`}
 if(q.section==='writing'){let src=q.jp||'模範解答と課題条件を比較してください。',exp=S.lang==='ja'?src:S.lang==='ko'?await translateCached('wko'+q.id,src,'ja','ko'):await translateCached('w'+S.lang+q.id,src,'ja',S.lang);let model=S.lang==='ko'?q.model:S.lang==='ja'?q.model:await translateCached('model'+S.lang+q.id,q.model,'ko',S.lang);return `<h3>${S.lang==='ja'?'模範解答':'MODEL ANSWER'}</h3><div class="answerBox"><p>${esc(model)}</p></div><h3>${tr('grammar')}</h3><p>${esc(q.grammar)}</p><h3>${tr('why')}</h3><p>${esc(exp)}</p>`}
 let fields={translation:q.translation||'',grammar:q.grammar||'',vocab:q.vocab||'',why:q.why||''};if(S.lang==='ja')return `<h3>${tr('answer')}</h3><div class="answerBox"><p>${esc(q.answer)}</p></div><h3>${tr('translation')}</h3><p>${esc(fields.translation)}</p><h3>${tr('grammar')}</h3><p>${esc(fields.grammar)}</p><h3>${tr('words')}</h3><p>${esc(fields.vocab)}</p><h3>${tr('why')}</h3><p>${esc(fields.why)}</p>`;if(S.lang==='ko'){let g=await translateCached('ko_g'+q.id,fields.grammar,'ja','ko'),v=await translateCached('ko_v'+q.id,fields.vocab,'ja','ko'),w=await translateCached('ko_w'+q.id,fields.why,'ja','ko');return `<h3>${tr('answer')}</h3><div class="answerBox"><p>${esc(q.answer)}</p></div><h3>${tr('grammar')}</h3><p>${esc(g)}</p><h3>${tr('words')}</h3><p>${esc(v)}</p><h3>${tr('why')}</h3><p>${esc(w)}</p>`}let [trans,g,v,w]=await Promise.all([translateCached(S.lang+'_t'+q.id,fields.translation,'ja',S.lang),translateCached(S.lang+'_g'+q.id,fields.grammar,'ja',S.lang),translateCached(S.lang+'_v'+q.id,fields.vocab,'ja',S.lang),translateCached(S.lang+'_w'+q.id,fields.why,'ja',S.lang)]);return `<h3>${tr('answer')}</h3><div class="answerBox"><p>${esc(q.answer)}</p></div><h3>${tr('translation')}</h3><p>${esc(trans)}</p><h3>${tr('grammar')}</h3><p>${esc(g)}</p><h3>${tr('words')}</h3><p>${esc(v)}</p><h3>${tr('why')}</h3><p>${esc(w)}</p>`}
async function translateCached(key,text,src,target){if(!text)return'';if(target===src)return text;let ck=src+'_'+target+'_'+key;if(S.transCache[ck])return S.transCache[ck];let parts=splitText(text,360),out=[];for(let p of parts){try{let code=target==='zh'?'zh-CN':target;let url='https://api.mymemory.translated.net/get?q='+encodeURIComponent(p)+'&langpair='+src+'%7C'+code;let r=await fetch(url),j=await r.json();out.push(j?.responseData?.translatedText||p)}catch(e){out.push(p)}}let res=out.join(' ');S.transCache[ck]=res;save();return res}
function splitText(t,n){let a=[];while(t.length>n){let p=t.lastIndexOf(' ',n);if(p<100)p=n;a.push(t.slice(0,p));t=t.slice(p)}if(t)a.push(t);return a}
function closeSheet(){$('overlay').classList.remove('open')}
// REVIEW
function reviewPage(sc){navActive('review');let res=S.lastResult;let items=[];for(let i=1;i<=50;i++){let a=S.realAnswers.listen[i];if(a)items.push({type:'listen',id:i,ok:a.selected===LS[i-1].answerIndex});let r=S.realAnswers.read[i];if(r)items.push({type:'read',id:i,ok:r.selected===RW[i-1].answerIndex})}sc.innerHTML=`${res?`<div class="infoCard"><h3>LAST REAL EXAM · ${res.total}/300 · ${res.grade?res.grade+'급':'불합격'}</h3><p>${tr('listening')} ${res.l} / ${tr('writing')} ${res.w} / ${tr('reading')} ${res.r}</p></div>`:''}<div class="sectionTitle"><h2>${tr('review')}</h2><span>${items.length}</span></div><div class="reviewList">${items.length?items.map(x=>`<div class="reviewItem ${x.ok?'good':'bad'}"><b>${x.type==='listen'?'L':'R'}${x.id}</b><span>${x.ok?tr('correct'):tr('wrong')}</span><button onclick="explainCurrent('${x.type}',${x.id})">${tr('explain')}</button></div>`).join(''):`<div class="infoCard"><p>${S.lang==='ja'?'実戦モードを完了すると答案レビューが表示されます。':'실전모드를 완료하면 답안 복습이 표시됩니다.'}</p></div>`}</div>`}
// VOCAB
function hideSelection(){$('selectionBar').classList.remove('show');selectedText=''}
function addVocab(){let w=selectedText.trim().replace(/\s+/g,' ');if(!w)return;if(S.vocab.some(v=>v.text===w))return toast(S.lang==='ja'?'すでに単語帳にあります。':'이미 단어장에 있습니다.');S.vocab.unshift({text:w,source:currentSource(),ja:'',show:false});save();toast('「'+w+'」 +');hideSelection();try{window.getSelection().removeAllRanges()}catch(e){}}
function currentSource(){if(S.view==='gameQ'){let m=stageMeta(S.gameStage);return(m.type==='listen'?'L':m.type==='write'?'W':'R')+m.id}if(S.view==='infinity'){let x=S.infinity.current;return(x.type==='listen'?'L':x.type==='write'?'W':'R')+x.id}if(S.view==='real'){let r=S.real;return(r.phase==='listen'?'L':r.phase==='read'?'R':'W')+r.id}return''}
async function revealVocab(i){let v=S.vocab[i];v.show=!v.show;if(v.show&&!v.ja){v.ja=await translateCached('vocab_'+v.text,v.text,'ko','ja')}save();render()}
function deleteVocab(i){S.vocab.splice(i,1);save();render()}
function vocabPage(sc){navActive('vocab');sc.innerHTML=`<div class="sectionTitle"><h2>${tr('vocab')}</h2><span>${S.vocab.length}</span></div><div class="infoCard"><p>${ml('문제·선택지에서 원하는 단어나 문법을 길게 눌러 선택 → 단어장 추가. 뜻은 보고 싶을 때만 일본어로 엽니다.','問題文や選択肢を長押しして範囲選択 → 単語帳に追加。意味は必要な時だけ日本語で開きます。','Long-press and select a word or grammar expression → add it to Vocab. Reveal the Japanese meaning only when you want it.','长按并选择题目中的单词或语法 → 加入单词本。需要时再显示日语释义。')}</p></div>${S.vocab.map((v,i)=>`<div class="vocabCard"><div class="vocabHead"><div class="vocabWord">${esc(v.text)}</div><span class="source">${esc(v.source)}</span></div><div class="vocabAnswer ${v.show?'show':''}">${v.show?esc(v.ja||'…'):''}</div><div class="vocabActions"><button class="reveal" onclick="revealVocab(${i})">🇯🇵 ${v.show?(S.lang==='ja'?'隠す':'숨기기'):(S.lang==='ja'?'答えを見る':'뜻 보기')}</button><button class="delete" onclick="deleteVocab(${i})">×</button></div></div>`).join('')}`}
// AUDIO LAB
const SPEAKING_PROMPTS=[
'저는 요즘 한국어를 매일 조금씩 공부하고 있습니다.',
'주말에는 친구와 함께 도서관에서 책을 읽었습니다.',
'회의가 끝난 뒤에 필요한 자료를 다시 확인해 주세요.',
'비가 많이 오면 지하철을 이용하는 것이 더 편합니다.',
'새로운 기술을 익히려면 꾸준히 연습하는 것이 중요합니다.',
'오늘 주문한 물건은 내일 오후에 도착할 예정입니다.',
'환경을 보호하기 위해 일회용품 사용을 줄여야 합니다.',
'여행을 가기 전에 숙소와 교통편을 미리 예약했습니다.'
];
function speakingPage(sc){navActive('speaking');let st=S.speaking||{mode:'read',index:0,last:null},text=SPEAKING_PROMPTS[st.index%SPEAKING_PROMPTS.length];setProgress((st.index%SPEAKING_PROMPTS.length)/SPEAKING_PROMPTS.length*100);sc.innerHTML=`<div class="sectionTitle"><h2>${ml('말하기 모드','スピーキング','Speaking Mode','口语模式')}</h2><span>${st.index%SPEAKING_PROMPTS.length+1}/${SPEAKING_PROMPTS.length}</span></div><div class="speakTabs"><button class="${st.mode==='read'?'active':''}" onclick="setSpeakingMode('read')">📖 ${ml('대본 읽기','台本読み','Read aloud','朗读')}</button><button class="${st.mode==='shadow'?'active':''}" onclick="setSpeakingMode('shadow')">🎧 ${ml('듣고 따라하기','聞いて真似る','Listen & repeat','听后跟读')}</button></div>${st.mode==='shadow'?`<button class="audioBtn" onclick="playSpeakingModel()">▶ ${ml('원어민 음성 듣기','モデル音声を聞く','Play model voice','播放示范音频')}</button>`:''}<div class="speakPrompt"><div class="korean">${esc(text)}</div><div class="roman">${ml('문장을 자연스럽게 읽어 보세요.','自然に読んでください。','Read the sentence naturally.','请自然地朗读句子。')}</div></div><button id="speakMic" class="micBtn" onclick="startSpeakingCheck()">🎙</button><div style="text-align:center;color:#91a5c2;font-size:10px">${ml('버튼을 누르고 말하세요','ボタンを押して話してください','Tap and speak','点击后说话')}</div><div id="speakResult">${st.last?renderSpeakResult(st.last):''}</div><div class="examNav"><button class="prev" onclick="nextSpeaking(-1)">${tr('prev')}</button><button class="next" onclick="nextSpeaking(1)">${tr('next')}</button></div><div class="infoCard"><p>${ml('현재 점수는 기기 음성인식 결과와 원문 일치도·말하기 시간으로 계산한 학습 점수입니다. 음소 단위 정밀 발음평가는 서버형 발음평가 엔진을 연결하면 더 정확해집니다.','現在の点数は端末音声認識と原文一致度・発話時間による学習スコアです。音素単位評価は専用エンジン連携で精密化できます。','Current score is a learning score based on device speech recognition, text match, and timing. Phoneme-level assessment requires a dedicated pronunciation service.','当前分数基于设备语音识别、文本匹配和时长，是学习评分；音素级评估需要专用服务。')}</p></div>`}
function setSpeakingMode(m){S.speaking=S.speaking||{};S.speaking.mode=m;S.speaking.last=null;save();render()}
function nextSpeaking(d){stopListeningAudio();S.speaking=S.speaking||{};S.speaking.index=(S.speaking.index||0)+d;if(S.speaking.index<0)S.speaking.index=SPEAKING_PROMPTS.length-1;S.speaking.index%=SPEAKING_PROMPTS.length;S.speaking.last=null;save();render()}
async function playSpeakingModel(){let idx=(S.speaking?.index||0)%SPEAKING_PROMPTS.length,text=SPEAKING_PROMPTS[idx];stopListeningAudio();let token=++audioFallbackToken;speechBusy=true,n=String(idx+1).padStart(3,'0'),cands=[`audio/speaking/p${n}.mp3`,`audio/speaking/p${n}.m4a`,`audio/speaking/p${n}.aac`,`audio/speaking/p${n}.webm`],file=null;for(let u of cands){try{let r=await fetch(u,{method:'HEAD',cache:'no-store'});if(r.ok){file=u;break}}catch(e){}}if(token!==audioFallbackToken)return;if(file){let a=new Audio(file);activeAudio=a;a.onended=()=>{speechBusy=false;activeAudio=null};a.onerror=()=>playSpeakingTTS(text,token);try{await a.play();return}catch(e){}}playSpeakingTTS(text,token)}
function playSpeakingTTS(text,token){if(token!==audioFallbackToken)return;let vs=koVoices(),u=window.MALBIT_TTS?window.MALBIT_TTS.utterance(text):new SpeechSynthesisUtterance(text);if(!window.MALBIT_TTS){u.lang='ko-KR';u.rate=.82;u.pitch=1;u.voice=vs[0]||null}u.onend=()=>{if(token===audioFallbackToken)speechBusy=false};speechSynthesis.speak(u)}
function normalizeSpeech(t){return (t||'').toLowerCase().replace(/[^가-힣a-z0-9]/g,'')}
function editSimilarity(a,b){a=normalizeSpeech(a);b=normalizeSpeech(b);if(!a||!b)return 0;let dp=Array(b.length+1).fill(0).map((_,i)=>i);for(let i=1;i<=a.length;i++){let prev=dp[0];dp[0]=i;for(let j=1;j<=b.length;j++){let old=dp[j];dp[j]=Math.min(dp[j]+1,dp[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old}}return Math.max(0,1-dp[b.length]/Math.max(a.length,b.length))}
function startSpeakingCheck(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition,btn=$('speakMic'),target=SPEAKING_PROMPTS[(S.speaking?.index||0)%SPEAKING_PROMPTS.length];if(!SR){toast(ml('이 브라우저는 실시간 음성인식을 지원하지 않습니다.','このブラウザは音声認識に対応していません。','Speech recognition is unavailable in this browser.','此浏览器不支持语音识别。'));return}try{if(speechRec)speechRec.abort()}catch(e){};stopListeningAudio();let rec=new SR();speechRec=rec;rec.lang='ko-KR';rec.interimResults=false;rec.continuous=false;rec.maxAlternatives=3;speakingStart=Date.now();if(btn)btn.classList.add('recording');rec.onresult=e=>{let best='';for(let i=0;i<e.results[0].length;i++){let t=e.results[0][i].transcript||'';if(editSimilarity(target,t)>editSimilarity(target,best))best=t}let dur=Math.max(1,(Date.now()-speakingStart)/1000),sim=editSimilarity(target,best),ideal=Math.max(2.4,target.length/5.2),pace=Math.max(0,1-Math.abs(dur-ideal)/Math.max(ideal,4)),accuracy=Math.round(sim*100),fluency=Math.round(Math.min(100,pace*100)),score=Math.round(accuracy*.8+fluency*.2);let result={score,accuracy,fluency,text:best,duration:dur};S.speaking.last=result;save();let box=$('speakResult');if(box)box.innerHTML=renderSpeakResult(result)};rec.onerror=e=>toast(ml('음성 인식에 실패했습니다. 마이크 권한을 확인해 주세요.','音声認識に失敗しました。マイク権限を確認してください。','Speech recognition failed. Check microphone permission.','语音识别失败，请检查麦克风权限。'));rec.onend=()=>{if(btn)btn.classList.remove('recording')};rec.start()}
function renderSpeakResult(x){return `<div class="speakResult"><div class="scoreRing" style="--score:${x.score}"><b>${x.score}</b></div><div class="scoreMetrics"><div><b>${x.accuracy}</b><small>${ml('정확도','正確度','Accuracy','准确度')}</small></div><div><b>${x.fluency}</b><small>${ml('유창성','流暢さ','Fluency','流利度')}</small></div><div><b>${x.duration.toFixed(1)}s</b><small>${ml('시간','時間','Time','时间')}</small></div></div><div class="recognized">🎤 ${esc(x.text||ml('인식 결과 없음','認識結果なし','No transcript','无识别结果'))}</div></div>`}
function developerStudio(sc){navActive('more');let rows=LS.map(q=>`<div class="devRow"><div><b>Q${String(q.id).padStart(3,'0')}</b></div><div><b>${q.id<=20?'1 PLAY':'SCRIPT'}</b><p>${esc((q.script||'').replace(/\n/g,' / '))}</p></div><div style="display:flex;gap:5px"><button onclick="playListening(${q.id},false)">▶</button><button id="devRec_${q.id}" onclick="toggleDevRecord(${q.id})">🎙</button>${devBlobs[q.id]?`<button onclick="downloadDevRecording(${q.id})">⬇</button>`:''}</div></div>`).join('');sc.innerHTML=`<div class="sectionTitle"><h2>🔒 Developer Listening Studio</h2><span>NOT IN PUBLIC NAV</span></div><div class="devBanner">${ml('이 화면은 공개 메뉴에 노출되지 않는 개발용 페이지입니다. GitHub Pages만으로는 진짜 접근 제어가 불가능하므로 보안 인증이 필요하면 별도 백엔드가 필요합니다.','この画面は公開メニューに表示されない開発用ページです。GitHub Pagesだけでは本当のアクセス制御はできません。','This is a hidden development page. GitHub Pages alone cannot provide real access control.','这是不在公开菜单中的开发页面。GitHub Pages本身无法提供真正的访问控制。')}</div><div class="infoCard"><h3>🎙 ${ml('직접 녹음 → 저장 → 업로드','録音 → 保存 → アップロード','Record → save → upload','录音 → 保存 → 上传')}</h3><p>${ml('각 문항의 🎙 버튼을 누르면 대본을 보며 직접 녹음할 수 있습니다. 다시 누르면 녹음이 끝나고 파일을 저장할 수 있습니다. 저장한 파일을 audio/topik2/에 q001, q002… 이름으로 업로드하면 앱이 자동으로 그 녹음을 우선 재생합니다.','各問題の🎙で録音し、もう一度押すと終了・保存できます。audio/topik2/ に q001, q002… の名前でアップロードすると優先再生されます。','Use 🎙 to record while reading the script. Tap again to stop and save. Upload as q001, q002… under audio/topik2/ and the app will prefer that recording.','点击🎙按脚本录音，再次点击停止并保存。上传到 audio/topik2/ 并命名为 q001、q002… 后，应用会优先播放录音。')}</p><button class="primary alt" onclick="window.open('https://github.com/okometsbu-beep/topik-quest/upload/main/audio/topik2','_blank')">↗ GitHub audio/topik2 업로드</button></div><div class="infoCard"><h3>✨ High-quality Korean TTS</h3><p>${ml('사람 녹음 대신 고품질 TTS를 사용할 경우 외부에서 HD 음원을 생성해 같은 파일명으로 올리는 방식을 권장합니다. 정적 GitHub Pages에 API 키를 넣으면 노출되므로 앱에서 직접 클라우드 TTS를 호출하지 않습니다.','高品質TTSは外部で生成し、同じファイル名でアップロードしてください。PagesにAPIキーを置かない構成です。','Generate high-quality TTS outside the static site and upload with the same filenames. API keys are never embedded in GitHub Pages.','高级TTS请在站外生成并按相同文件名上传，API密钥不会写入GitHub Pages。')}</p></div><div>${rows}</div>`}
async function toggleDevRecord(id){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){toast('MediaRecorder unavailable');return}if(devRecorder&&devRecorder.state==='recording'){if(devRecordingId!==id){toast(ml('먼저 현재 녹음을 종료하세요.','先に現在の録音を終了してください。','Stop the current recording first.','请先结束当前录音。'));return}devRecorder.stop();return}try{devStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});let types=['audio/mp4','audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus'],mime=types.find(t=>MediaRecorder.isTypeSupported?.(t))||'';devChunks=[];devRecordingId=id;devRecorder=new MediaRecorder(devStream,mime?{mimeType:mime}:undefined);let b=$('devRec_'+id);if(b){b.textContent='■';b.style.background='#6d2431'}devRecorder.ondataavailable=e=>{if(e.data?.size)devChunks.push(e.data)};devRecorder.onstop=()=>{let type=devRecorder.mimeType||mime||'audio/webm',ext=type.includes('mp4')?'m4a':type.includes('ogg')?'ogg':'webm',blob=new Blob(devChunks,{type}),url=URL.createObjectURL(blob);devBlobs[id]={blob,url,ext};try{devStream?.getTracks().forEach(t=>t.stop())}catch(e){};devStream=null;devRecorder=null;devRecordingId=null;toast(ml('녹음 완료. 다운로드 버튼이 생겼습니다.','録音完了。ダウンロードできます。','Recording ready to download.','录音完成，可下载。'));render()};devRecorder.start()}catch(e){toast(ml('마이크 권한을 확인해 주세요.','マイク権限を確認してください。','Check microphone permission.','请检查麦克风权限。'))}}
function downloadDevRecording(id){let x=devBlobs[id];if(!x)return;let a=document.createElement('a');a.href=x.url;a.download=`q${String(id).padStart(3,'0')}.${x.ext}`;a.click()}
// selection/vocab
document.addEventListener('selectionchange',()=>{clearTimeout(window._selT);window._selT=setTimeout(()=>{let sel=window.getSelection();if(!sel||sel.isCollapsed)return hideSelection();let text=sel.toString().trim();if(!text||text.length>60)return hideSelection();let node=sel.anchorNode,host=node&&(node.nodeType===1?node:node.parentElement);if(!host?.closest?.('.selectable'))return hideSelection();selectedText=text;$('selectionWord').textContent='「'+text+'」';$('selectionBar').classList.add('show')},220)});
function toast(msg){let x=$('toast');x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1500)}
window.addEventListener('click',e=>{if(!e.target.closest('#flagBtn')&&!e.target.closest('#flagMenu'))$('flagMenu').classList.remove('open')});
window.addEventListener('beforeunload',()=>stopListeningAudio());
// init
if(new URLSearchParams(location.search).get('dev')==='studio')S.view='devStudio';
renderShell();
