const VERSION='162',CACHE_PREFIX='malbit-v',CACHE=CACHE_PREFIX+VERSION;
const SHELL=Object.freeze(['./growth-learning.css','./learning-rewards.js','./data/growth-learning.js','./data/growth-learning-locales.js','./growth-learning-engine.js','./growth-learning.js','./growth-learning-entrypoints.js','./writing-curriculum.css','./data/writing-curriculum.js','./data/writing-curriculum-locales.js','./writing-curriculum-i18n.js','./writing-curriculum-engine.js','./writing-curriculum.js','./assets/art/writing/flow-start-v1.webp','./assets/art/writing/flow-unlock-v1.webp','./assets/art/writing/flow-return-v1.webp','./assets/art/writing/context-work-v1.webp','./assets/art/writing/context-park-v1.webp','./assets/art/writing/context-study-v1.webp','./assets/art/writing/context-movie-v1.webp','./assets/art/writing/context-rain-v1.webp','./assets/art/haruman/home-study-v2.webp','./assets/art/haruman/shorts-quiz-v2.webp','./assets/art/haruman/travel-journey-v2.webp','./assets/art/haruman/vocab-reading-v2.webp','./assets/art/haruman/review-thinking-v2.webp','./assets/art/haruman/lesson-welcome-v2.webp','./assets/art/haruman/progress-proud-v2.webp','./assets/art/haruman/answer-correct-v2.webp','./assets/art/haruman/answer-retry-v2.webp','./assets/art/haruman/lesson-complete-v2.webp','./assets/art/haruman/review-empty-v2.webp','./assets/art/haruman/audio-listening-v2.webp','./haruman-intro.js','./haruman-intro.css','./assets/art/haruman/welcome-v1.webp','./assets/art/haruman/thinking-v1.webp','./assets/art/haruman/correct-v1.webp','./assets/art/haruman/retry-v1.webp','./assets/art/haruman/celebrate-v1.webp','./assets/art/haruman/encourage-v1.webp','./assets/art/haruman/journey-v1.webp','./assets/art/haruman/rest-v1.webp','./','./index.html','./styles.css','./harumal-ui.css','./listening-player.js','./listening-player.css','./learning-hub.css','./learning-hub.js','./assets/harumal/ui/vocab-diary-empty-v1.webp','./travel-adventure.css','./legacy-data.js','./legacy-core.js','./site-patch.js','./manifest.webmanifest','./icon.svg','./assets/art/malbit-home-hero.webp','./assets/art/travel/rpg/traveler-blue-4dir-v1.png','./assets/art/travel/rpg/travel-stamina-game-over-v1.webp','./assets/art/travel/rpg/korean-street-basic-atlas-v1.webp','./assets/art/travel/rpg/korean-street-corners-atlas-v1.webp','./assets/art/travel/rpg/korean-street-junctions-atlas-v1.webp','./assets/art/travel/rpg/korean-street-building-entrances-atlas-v1.webp','./assets/art/travel/rpg/korean-street-decor-upper-atlas-v1.webp']);
self.addEventListener('message',event=>{if(event.data==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith(CACHE_PREFIX)&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
  const request=event.request,url=new URL(request.url);

  if(request.method!=='GET'||url.origin!==location.origin)return;
  // Optional movies must not gate shell installation or cache partial range responses.
  if(url.pathname.includes('/assets/video/')||url.pathname.includes('/audio/listening/'))return;
  const isDocument=request.mode==='navigate';
  const remember=(key,response)=>{if(response?.ok)event.waitUntil(caches.open(CACHE).then(cache=>cache.put(key,response.clone())).catch(()=>{}));return response};
  if(isDocument){event.respondWith(fetch(request).then(response=>remember('./index.html',response)).catch(()=>caches.match('./index.html')));return}
  const requestedVersion=new URL(request.url).searchParams.get('v'),ignoreSearch=!requestedVersion||requestedVersion===VERSION;
  event.respondWith(caches.match(request,{ignoreSearch}).then(hit=>hit||fetch(request).then(response=>remember(request,response))).catch(()=>fetch(request)));
});
