// TOPIK QUEST · TOPIK I engine v2 · full UI localization
(function(){
'use strict';
const L=window.TOPIK1_LISTENING_DATA||[],R=window.TOPIK1_READING_DATA||[],A=[...L,...R];
if(!A.length){console.error('TOPIK I data missing');return}
const LEVEL='topikQuestExamLevel',SESSION='topikQuestTopik1Session',EXT=['mp3','m4a','aac','webm','ogg'];
let Q=null,timer=null,audio=null,ctx=null;
const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const T=(ko,ja,en,zh)=>typeof ml==='function'?ml(ko,ja,en,zh):ko;
const level=()=>{try{return localStorage.getItem(LEVEL)==='1'?1:2}catch(e){return 2}};
window.tqSetLevel=n=>{try{localStorage.setItem(LEVEL,String(n))}catch(e){};render()};
function stopAudio(){try{speechSynthesis.cancel()}catch(e){};if(audio){try{audio.pause();audio.currentTime=0}catch(e){}audio=null}}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function open(v){stopAudio();stopTimer();S.view=v;try{save()}catch(e){};render()}
function find(id){return A.find(x=>x.id===Number(id))}
function pool(k){return k==='listening'?L:k==='reading'?R:A}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function clock(s){s=Math.max(0,Math.floor(s));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function secName(sec){return sec==='listening'?T('듣기','聞き取り','Listening','听力'):T('읽기','読解','Reading','阅读')}
function groupName(g){
  const M={
    '응답':['응답','応答','Response','应答'],'장소':['장소','場所','Place','场所'],'내용':['내용','内容','Content','内容'],'안내':['안내','案内','Notice','通知'],'목적':['목적','目的','Purpose','目的'],'중심':['중심 생각','中心内容','Main idea','中心思想'],'세부':['세부 내용','詳細内容','Detail','细节'],'긴 대화':['긴 대화','長い会話','Long dialogue','长对话'],
    '어휘·문법':['어휘·문법','語彙・文法','Vocabulary & Grammar','词汇·语法'],'표지·안내':['표지·안내','標識・案内','Signs & Notices','标识·通知'],'광고':['광고','広告','Advertisement','广告'],'짧은 글':['짧은 글','短文','Short passage','短文'],'빈칸':['빈칸','空欄補充','Fill in the blank','填空'],'순서':['문장 순서','文の順序','Sentence order','句子顺序'],'중심 내용':['중심 내용','中心内容','Main idea','中心内容'],'긴 글':['긴 글','長文','Long passage','长文']
  };
  const a=M[g];return a?T(...a):g;
}
function instructionText(q){
  if((S?.lang||'ko')==='ko')return q.instruction||'';
  if(q.section==='listening'){
    if(q.group==='응답')return T('', '音声を聞いて、続く言葉として最も適切なものを選んでください。','Listen and choose the most appropriate response.','请听录音，选择最恰当的回答。');
    if(q.group==='장소')return T('', '音声を聞いて、場所として最も適切なものを選んでください。','Listen and choose the most appropriate place.','请听录音，选择最恰当的场所。');
    if(q.group==='내용')return T('', '音声を聞いて、内容と一致するものを選んでください。','Listen and choose the statement that matches the content.','请听录音，选择与内容相符的一项。');
    if(q.group==='목적')return T('', '音声を聞いて、話し手の目的として最も適切なものを選んでください。','Listen and choose the speaker’s purpose.','请听录音，选择说话人的目的。');
    if(q.group==='중심')return T('', '音声を聞いて、中心内容として最も適切なものを選んでください。','Listen and choose the main idea.','请听录音，选择中心内容。');
    return T('', '音声を聞いて、質問に最も適切な答えを選んでください。','Listen and choose the best answer.','请听录音，选择最恰当的答案。');
  }
  if(q.group==='어휘·문법'||q.group==='빈칸')return T('', '空欄に入る最も適切なものを選んでください。','Choose the best answer for the blank.','请选择最适合填入空格的一项。');
  if(q.group==='순서')return T('', '文の順序として最も適切なものを選んでください。','Choose the most appropriate sentence order.','请选择最恰当的句子顺序。');
  return T('', '次の文を読んで、最も適切な答えを選んでください。','Read the passage and choose the best answer.','阅读下面的内容，选择最恰当的答案。');
}
function explainText(q){
  if((S?.lang||'ko')==='ko')return q.explanation||'';
  return T('',`正解は${q.answerIndex+1}番です。設問と選択肢をもう一度確認してください。`,`The correct answer is option ${q.answerIndex+1}. Review the question and choices.`,`正确答案是第${q.answerIndex+1}项。请再次确认题目和选项。`);
}
async function fileAudio(id){const n=String(id).padStart(3,'0');for(const x of EXT){const u=`audio/topik1/q${n}.${x}`;try{const r=await fetch(u,{method:'HEAD',cache:'no-store'});if(r.ok)return u}catch(e){}}return null}
function tts(txt){stopAudio();const lines=String(txt||'').replace(/^(여자|남자|안내|방송|여자\(안내\)|남자\(안내\)|여자\(설명\)|남자\(설명\)):\s*/gm,'').split(/\n+/).map(x=>x.trim()).filter(Boolean);let i=0,token=Date.now();window.__t1tts=token;const next=()=>{if(window.__t1tts!==token||i>=lines.length)return;const u=new SpeechSynthesisUtterance(lines[i++]);u.lang='ko-KR';u.rate=.91;u.pitch=1;try{const vs=speechSynthesis.getVoices().filter(v=>/^ko/i.test(v.lang));if(vs.length)u.voice=vs[(i-1)%vs.length]}catch(e){}u.onend=()=>setTimeout(next,230);u.onerror=()=>setTimeout(next,80);speechSynthesis.speak(u)};next()}
async function play(id){const q=find(id);if(!q)return;if(Q?.mode==='real'&&Q.played?.[id]){toast(T('실전 듣기는 한 번만 재생할 수 있습니다.','実戦の聞き取り音声は1回だけ再生できます。','Listening audio can be played only once in Exam Mode.','实战模式的听力音频只能播放一次。'));return}if(Q?.mode==='real'){Q.played[id]=1;saveQ();render()}stopAudio();const url=await fileAudio(id);if(!url)return tts(q.script);try{const a=new Audio(url+'?v='+Date.now());audio=a;try{const AC=window.AudioContext||window.webkitAudioContext;if(AC){ctx=ctx||new AC();if(ctx.state==='suspended')await ctx.resume();const s=ctx.createMediaElementSource(a),g=ctx.createGain(),c=ctx.createDynamicsCompressor();g.gain.value=1.3;c.threshold.value=-8;c.ratio.value=5;s.connect(g).connect(c).connect(ctx.destination)}}catch(e){}a.onended=()=>audio=null;await a.play()}catch(e){tts(q.script)}}
window.t1Play=play;
function saveQ(){try{localStorage.setItem(SESSION,JSON.stringify(Q))}catch(e){}}
function clearQ(){Q=null;try{localStorage.removeItem(SESSION)}catch(e){}}
function restore(){if(Q)return Q;try{Q=JSON.parse(localStorage.getItem(SESSION)||'null')}catch(e){};return Q}
function seconds(){return Q?.duration?Q.duration-Math.floor((Date.now()-Q.started)/1000):999999}
window.tqStartMode=mode=>{if(level()===2){if(mode==='real')return setView('realSetup');if(mode==='game')return setView('game');return startInfinity()}if(mode==='real')return open('t1setup');if(mode==='game')return startPractice('game');return startPractice('inf')};
const css=document.createElement('style');
css.textContent=`.t1level{display:grid;grid-template-columns:1fr 1fr;gap:5px;background:#0d192b;border:1px solid #273b5a;border-radius:17px;padding:5px;margin:0 0 10px}.t1level button{border:0;border-radius:13px;padding:10px 5px;background:transparent;color:#8296b4;font-size:11px;font-weight:900}.t1level button.on{background:linear-gradient(135deg,#4e86ff,#8065ff);color:#fff}.t1setup{display:grid;gap:9px}.t1setup button{border:1px solid #2c4264;background:linear-gradient(145deg,#102039,#172b49);color:#fff;border-radius:21px;padding:16px;text-align:left}.t1setup b{font-size:16px}.t1setup small{float:right;color:#87b4ff}.t1setup p{font-size:10px;color:#9db1ce;line-height:1.5;margin:6px 0 0}.t1head{background:#0d1b30;border:1px solid #2b4164;border-radius:19px;padding:12px;margin-bottom:10px}.t1head>div{display:flex;justify-content:space-between;align-items:center}.t1head strong{font-size:21px}.t1bar{height:6px;background:#182941;border-radius:99px;overflow:hidden;margin-top:8px}.t1bar i{display:block;height:100%;background:linear-gradient(90deg,#4d9cff,#8c70ff)}.t1audio{width:100%;border:0;border-radius:15px;padding:13px;background:#152d50;color:#fff;font-weight:900;margin-bottom:11px}.t1nav{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.t1nav button{border:0;border-radius:14px;padding:13px;font-weight:900}.t1nav .p{background:#e9eef6;color:#34445d}.t1nav .n{background:#286cff;color:#fff}.t1hud{display:flex;gap:6px;overflow:auto;margin-bottom:9px}.t1hud span{white-space:nowrap;background:#10213a;border:1px solid #2d4669;border-radius:99px;padding:7px 10px;font-size:10px;color:#c7d7ed}.t1result{background:linear-gradient(150deg,#11233e,#1b3154);border:1px solid #34517d;border-radius:24px;padding:18px}.t1score{font-size:44px;font-weight:950;margin:13px 0}.t1score small{font-size:14px;color:#9fb4d1}.t1split{display:grid;grid-template-columns:1fr 1fr;gap:8px}.t1split div{background:#0d1b30;border-radius:15px;padding:12px}.t1split b{display:block;font-size:20px}.t1wrong{display:flex;flex-wrap:wrap;gap:5px;margin-top:11px}.t1wrong span{padding:5px 7px;border-radius:9px;background:#48212c;color:#ffcad2;font-size:9px}`;
document.head.appendChild(css);
home=function(sc){
  navActive('home');setProgress(0);sc.classList.add('tqHome');
  const lv=level(),hero=ASSETS['exam_student.png'];
  sc.innerHTML=`<section class="tqHero"><img src="${hero}" alt="TOPIK QUEST"><div class="tqHeroBrand"><b>TOPIK QUEST</b><small>KOREAN MASTERY</small></div><div class="tqBubble">${T('오늘도 한 문제씩, 한국어를 더 가깝게.','今日も一問ずつ、韓国語をもっと身近に。','One question at a time, closer to Korean.','每天一道题，更接近韩语。')}</div><div class="tqHeroFoot"><b>${T('시험 레벨과 연습 방식을 선택하세요','試験レベルと練習方法を選んでください','Choose your exam level and practice mode','请选择考试等级和练习方式')}</b><small>TOPIK I · TOPIK II</small></div></section>
  <div class="t1level"><button class="${lv===1?'on':''}" onclick="tqSetLevel(1)">${T('TOPIK I · 1~2급','TOPIK I · 1～2級','TOPIK I · Levels 1–2','TOPIK I · 1~2级')}</button><button class="${lv===2?'on':''}" onclick="tqSetLevel(2)">${T('TOPIK II · 3~6급','TOPIK II · 3～6級','TOPIK II · Levels 3–6','TOPIK II · 3~6级')}</button></div>
  <div class="tqModeGrid">
    <button class="tqMode exam" onclick="tqStartMode('real')"><div class="fakeArt"><span>🎧📝</span></div><div class="copy"><b>${T('실전모드','実戦モード','Exam Mode','实战模式')}</b><small>${lv===1?T('듣기 30 · 읽기 40','聞き取り30 · 読解40','Listening 30 · Reading 40','听力30 · 阅读40'):T('실제 시험 형식으로 집중 연습','本番形式で集中練習','Focused practice in real exam format','按真实考试形式集中练习')}</small></div></button>
    <button class="tqMode game" onclick="tqStartMode('game')"><div class="fakeArt"><span>⚔️👾</span></div><div class="copy"><b>${T('게임모드','ゲームモード','Game Mode','游戏模式')}</b><small>${lv===1?T('TOPIK I 랜덤 10문항 배틀','TOPIK I ランダム10問バトル','TOPIK I random 10-question battle','TOPIK I 随机10题挑战'):T('몬스터를 물리치며 학습','モンスターを倒しながら学習','Learn while defeating monsters','击败怪物进行学习')}</small></div></button>
    <button class="tqMode inf" onclick="tqStartMode('infinity')"><div class="fakeArt"><span>🐱∞</span></div><div class="copy"><b>${T('인피니티','インフィニティ','Infinity','无限模式')}</b><small>${lv===1?T('TOPIK I 70문항 무한 연습','TOPIK I 70問 無限練習','Endless practice from 70 TOPIK I questions','TOPIK I 70题无限练习'):T('무한 문제 풀이','無限問題練習','Endless question practice','无限题目练习')}</small></div></button>
  </div>
  <div class="tqSectionHead"><b>${T('빠른 연습','クイック練習','Quick Practice','快速练习')}</b><span>${lv===1?'TOPIK I':'TOPIK II'}</span></div>
  <div class="tqQuick"><button onclick="setView('speaking')"><i>🎙</i><b>${T('말하기 연습','スピーキング練習','Speaking Practice','口语练习')}</b><small>${T('읽기·따라하기·발음 점수','音読・リピート・発音スコア','Read · Repeat · Pronunciation score','朗读·跟读·发音评分')}</small></button><button onclick="setView('review')"><i>↻</i><b>${T('복습','復習','Review','复习')}</b><small>${T('틀린 문제 다시 확인','間違えた問題をもう一度確認','Review missed questions','重新查看错题')}</small></button></div>`;
};
function renderSetup(sc){navActive('home');sc.innerHTML=`<div class="sectionTitle"><h2>TOPIK I · ${T('실전모드','実戦モード','Exam Mode','实战模式')}</h2><span>70 QUESTIONS</span></div><div class="infoCard"><h3>${T('TOPIK I 모의연습 세트','TOPIK I 模擬練習セット','TOPIK I Mock Practice Set','TOPIK I 模拟练习套题')}</h3><p>${T('독자 제작 문제로 듣기 30문항과 읽기 40문항을 연습합니다.','オリジナル問題で聞き取り30問・読解40問を練習します。','Practice 30 listening and 40 reading questions with original content.','使用原创题目练习30道听力题和40道阅读题。')}</p></div><div class="t1setup"><button onclick="t1Begin('full')"><small>100 MIN</small><b>🎓 ${T('전체 실전','フル模擬試験','Full Mock Exam','完整模拟考试')}</b><p>${T('듣기 30 → 읽기 40, 총 70문항','聞き取り30 → 読解40、全70問','Listening 30 → Reading 40, 70 questions total','听力30 → 阅读40，共70题')}</p></button><button onclick="t1Begin('listening')"><small>40 MIN</small><b>🎧 ${T('듣기만','聞き取りのみ','Listening Only','仅听力')}</b><p>${T('30문항 · 실전에서는 각 문항 1회 재생','30問 · 実戦では各問題1回のみ再生','30 questions · one playback per question in Exam Mode','30题 · 实战模式每题仅播放一次')}</p></button><button onclick="t1Begin('reading')"><small>60 MIN</small><b>📖 ${T('읽기만','読解のみ','Reading Only','仅阅读')}</b><p>${T('40문항','40問','40 questions','40题')}</p></button></div><button class="primary alt" style="margin-top:12px" onclick="setView('home')">${T('홈으로','ホームへ','Back Home','返回首页')}</button>`}
window.t1Begin=k=>{clearQ();const m=k==='listening'?40:k==='reading'?60:100;Q={mode:'real',kind:k,ids:pool(k).map(x=>x.id),i:0,answers:{},played:{},started:Date.now(),duration:m*60};saveQ();open('t1quiz')};
function startPractice(mode){clearQ();const first=mode==='game'?shuffle(A).slice(0,10):[A[Math.floor(Math.random()*A.length)]];Q={mode,kind:'all',ids:first.map(x=>x.id),i:0,answers:{},played:{},score:0,total:0,streak:0,locked:false};saveQ();open('t1quiz')}
function cur(){restore();return Q?find(Q.ids[Q.i]):null}
function choices(q,sel,locked){return q.choices.map((c,i)=>{let z='choice';if(sel===i)z+=' selected';if(locked&&i===q.answerIndex)z+=' correct';if(locked&&sel===i&&i!==q.answerIndex)z+=' wrong';return `<button class="${z}" ${locked?'disabled':''} onclick="t1Pick(${i})"><span class="n">${i+1}</span><span>${E(c)}</span></button>`}).join('')}
window.t1Pick=i=>{restore();if(!Q||Q.locked)return;Q.answers[cur().id]=i;saveQ();render()};
function body(q,locked){const sel=Q.answers[q.id],aud=q.section==='listening'?`<button class="t1audio" onclick="t1Play(${q.id})" ${Q.mode==='real'&&Q.played[q.id]?'disabled':''}>${Q.mode==='real'&&Q.played[q.id]?T('✓ 재생 완료','✓ 再生済み','✓ Played','✓ 已播放'):T('▶ 듣기','▶ 聞く','▶ Play Audio','▶ 播放听力')}</button>`:'';return `<div class="instruction">${E(instructionText(q))}</div>${aud}${q.stem?`<div class="stem">${E(q.stem)}</div>`:''}${q.prompt?`<div class="stem" style="font-size:14px">${E(q.prompt)}</div>`:''}<div class="choices">${choices(q,sel,locked)}</div>${locked?`<div class="resultStrip ${sel===q.answerIndex?'good':'bad'}">${sel===q.answerIndex?T('정답입니다.','正解です。','Correct.','回答正确。'):T(`정답: ${q.answerIndex+1}번`,`正解: ${q.answerIndex+1}番`,`Answer: option ${q.answerIndex+1}`,`正确答案：第${q.answerIndex+1}项`)} · ${E(explainText(q))}</div>`:''}`}
window.t1Next=()=>{restore();if(!Q)return;stopAudio();if(Q.mode==='real'){Q.i++;if(Q.i>=Q.ids.length)return finish();saveQ();return render()}if(!Q.locked){const q=cur(),sel=Q.answers[q.id];if(sel==null)return;const ok=sel===q.answerIndex;Q.locked=true;Q.total++;if(ok){Q.score++;Q.streak++}else Q.streak=0;saveQ();return render()}if(Q.mode==='game'){Q.i++;if(Q.i>=Q.ids.length)return finish();Q.locked=false;saveQ();return render()}const nq=A[Math.floor(Math.random()*A.length)];Q.ids=[nq.id];Q.i=0;Q.answers={};Q.played={};Q.locked=false;saveQ();render()};
window.t1Prev=()=>{restore();if(Q?.mode==='real'&&Q.i>0){stopAudio();Q.i--;saveQ();render()}};
function result(){let lc=0,lt=0,rc=0,rt=0,w=[];for(const id of Q.ids){const q=find(id),ok=Q.answers[id]===q.answerIndex;if(q.section==='listening'){lt++;if(ok)lc++}else{rt++;if(ok)rc++}if(!ok)w.push(id)}const ls=lt?Math.round(lc/lt*100):0,rs=rt?Math.round(rc/rt*100):0;return {lc,lt,rc,rt,ls,rs,total:(lt?ls:0)+(rt?rs:0),wrong:w}}
function finish(){stopAudio();stopTimer();Q.result=Q.mode==='real'?result():{score:Q.score,total:Q.total};saveQ();open('t1result')}
function tick(){stopTimer();if(Q.mode!=='real')return;const f=()=>{const s=seconds(),e=document.getElementById('t1clock');if(e)e.textContent=clock(s);if(s<=0)finish()};f();timer=setInterval(f,1000)}
function renderQuiz(sc){restore();if(!Q)return open('t1setup');const q=cur();if(!q)return open('home');if(Q.mode==='real'&&seconds()<=0)return finish();const sel=Q.answers[q.id],locked=Q.mode!=='real'&&Q.locked;const top=Q.mode==='real'?`<div class="t1head"><div><span><b>TOPIK I · ${secName(q.section)}</b><small style="display:block;color:#91a5c2">${Q.i+1}/${Q.ids.length}</small></span><strong id="t1clock">--:--</strong></div><div class="t1bar"><i style="width:${(Q.i+1)/Q.ids.length*100}%"></i></div></div>`:`<div class="t1hud"><span>${Q.mode==='game'?`⚔️ ${T('게임 10','ゲーム 10','GAME 10','游戏 10')}`:'♾ INFINITY'}</span><span>${T('정답','正解','Correct','答对')} ${Q.score}/${Q.total}</span><span>🔥 ${Q.streak}</span>${Q.mode==='game'?`<span>${Q.i+1}/10</span>`:''}</div>`;sc.innerHTML=`${top}<div class="card"><div class="qmeta"><div class="qno">${q.id}</div><span class="cat">${E(groupName(q.group))}</span></div>${body(q,locked)}${Q.mode==='real'?`<div class="t1nav"><button class="p" onclick="t1Prev()" ${Q.i===0?'disabled':''}>‹ ${T('이전','前へ','Previous','上一题')}</button><button class="n" onclick="t1Next()">${Q.i===Q.ids.length-1?T('제출','提出','Submit','提交'):T('다음','次へ','Next','下一题')} ›</button></div>`:`<button class="attack" style="width:100%;border:0;border-radius:15px;padding:14px;margin-top:12px;font-weight:950" onclick="t1Next()" ${sel==null&&!locked?'disabled':''}>${locked?T('다음 문제 ›','次の問題 ›','Next Question ›','下一题 ›'):T('정답 확인','答えを確認','Check Answer','查看答案')}</button>`}</div><button class="primary alt" style="margin-top:10px" onclick="setView('home')">${T('종료','終了','Exit','退出')}</button>`;tick()}
function gradeText(total){if(total>=140)return T('2급','2級','Level 2','2级');if(total>=80)return T('1급','1級','Level 1','1级');return T('등급 전','級なし','Below Level 1','未达等级')}
function renderResult(sc){restore();if(!Q?.result)return open('home');if(Q.mode!=='real'){const r=Q.result;sc.innerHTML=`<div class="t1result"><h2>${Q.mode==='game'?T('⚔️ 배틀 완료','⚔️ バトル完了','⚔️ Battle Complete','⚔️ 挑战完成'):T('♾ 연습 종료','♾ 練習終了','♾ Practice Complete','♾ 练习结束')}</h2><div class="t1score">${r.score}<small> / ${r.total}</small></div><p>${T('정확도','正答率','Accuracy','正确率')} ${r.total?Math.round(r.score/r.total*100):0}%</p></div><button class="primary" style="margin-top:10px" onclick="setView('home')">${T('홈','ホーム','Home','首页')}</button>`;return}const r=Q.result,full=r.lt&&r.rt,score=full?r.total:(r.lt?r.ls:r.rs),den=full?200:100,grade=full?gradeText(r.total):'';sc.innerHTML=`<div class="t1result"><small>TOPIK I · ${T('연습 결과','練習結果','PRACTICE RESULT','练习结果')}</small><h2>✅ ${T('풀이 완료','解答完了','Completed','答题完成')}</h2><div class="t1score">${score}<small> / ${den}</small></div>${full?`<b style="font-size:18px">${T('연습 판정','練習判定','Practice Level','练习等级')}: ${grade}</b>`:''}<div class="t1split" style="margin-top:12px">${r.lt?`<div><small>${T('듣기','聞き取り','Listening','听力')}</small><b>${r.ls}</b><small>${r.lc}/${r.lt}</small></div>`:''}${r.rt?`<div><small>${T('읽기','読解','Reading','阅读')}</small><b>${r.rs}</b><small>${r.rc}/${r.rt}</small></div>`:''}</div>${r.wrong.length?`<div style="margin-top:12px;font-size:10px;color:#9fb4d1">${T('틀린 문제','間違えた問題','Missed Questions','错题')}</div><div class="t1wrong">${r.wrong.map(x=>`<span>Q${x}</span>`).join('')}</div>`:''}</div><button class="primary" style="margin-top:10px" onclick="setView('home')">${T('홈','ホーム','Home','首页')}</button>`}
const baseRender=render;
render=function(){if(['t1setup','t1quiz','t1result'].includes(S.view)){try{hideSelection()}catch(e){};try{renderShell()}catch(e){};const sc=$('screen');sc.className='screen';sc.innerHTML='';if(S.view==='t1setup')return renderSetup(sc);if(S.view==='t1quiz')return renderQuiz(sc);return renderResult(sc)}return baseRender()};
const baseSetView=setView;
setView=function(v){if(/^t1/.test(S.view||'')&&!/^t1/.test(v||'')){stopAudio();stopTimer()}return baseSetView(v)};
window.TOPIK1_QUESTIONS=A;
if(S.view==='home')setTimeout(()=>render(),0)
})();
