// TOPIK QUEST · TOPIK I engine v1
(function(){
'use strict';
const L=window.TOPIK1_LISTENING_DATA||[],R=window.TOPIK1_READING_DATA||[],A=[...L,...R];
if(!A.length){console.error('TOPIK I data missing');return}
const LEVEL='topikQuestExamLevel',SESSION='topikQuestTopik1Session',EXT=['mp3','m4a','aac','webm','ogg'];
let Q=null,timer=null,audio=null,ctx=null;
const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const level=()=>{try{return localStorage.getItem(LEVEL)==='1'?1:2}catch(e){return 2}};
window.tqSetLevel=n=>{try{localStorage.setItem(LEVEL,String(n))}catch(e){};render()};
function stopAudio(){try{speechSynthesis.cancel()}catch(e){};if(audio){try{audio.pause();audio.currentTime=0}catch(e){}audio=null}}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function open(v){stopAudio();stopTimer();S.view=v;try{save()}catch(e){};render()}
function find(id){return A.find(x=>x.id===Number(id))}
function pool(k){return k==='listening'?L:k==='reading'?R:A}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function clock(s){s=Math.max(0,Math.floor(s));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
async function fileAudio(id){const n=String(id).padStart(3,'0');for(const x of EXT){const u=`audio/topik1/q${n}.${x}`;try{const r=await fetch(u,{method:'HEAD',cache:'no-store'});if(r.ok)return u}catch(e){}}return null}
function tts(txt){stopAudio();const lines=String(txt||'').replace(/^(여자|남자|안내|방송|여자\(안내\)|남자\(안내\)|여자\(설명\)|남자\(설명\)):\s*/gm,'').split(/\n+/).map(x=>x.trim()).filter(Boolean);let i=0,token=Date.now();window.__t1tts=token;const next=()=>{if(window.__t1tts!==token||i>=lines.length)return;const u=new SpeechSynthesisUtterance(lines[i++]);u.lang='ko-KR';u.rate=.91;u.pitch=1;try{const vs=speechSynthesis.getVoices().filter(v=>/^ko/i.test(v.lang));if(vs.length)u.voice=vs[(i-1)%vs.length]}catch(e){}u.onend=()=>setTimeout(next,230);u.onerror=()=>setTimeout(next,80);speechSynthesis.speak(u)};next()}
async function play(id){const q=find(id);if(!q)return;if(Q?.mode==='real'&&Q.played?.[id]){toast('실전 듣기는 한 번만 재생할 수 있습니다.');return}if(Q?.mode==='real'){Q.played[id]=1;saveQ();render()}stopAudio();const url=await fileAudio(id);if(!url)return tts(q.script);try{const a=new Audio(url+'?v='+Date.now());audio=a;try{const AC=window.AudioContext||window.webkitAudioContext;if(AC){ctx=ctx||new AC();if(ctx.state==='suspended')await ctx.resume();const s=ctx.createMediaElementSource(a),g=ctx.createGain(),c=ctx.createDynamicsCompressor();g.gain.value=1.3;c.threshold.value=-8;c.ratio.value=5;s.connect(g).connect(c).connect(ctx.destination)}}catch(e){}a.onended=()=>audio=null;await a.play()}catch(e){tts(q.script)}}
window.t1Play=play;
function saveQ(){try{localStorage.setItem(SESSION,JSON.stringify(Q))}catch(e){}}
function clearQ(){Q=null;try{localStorage.removeItem(SESSION)}catch(e){}}
function restore(){if(Q)return Q;try{Q=JSON.parse(localStorage.getItem(SESSION)||'null')}catch(e){};return Q}
function seconds(){return Q?.duration?Q.duration-Math.floor((Date.now()-Q.started)/1000):999999}
window.tqStartMode=mode=>{if(level()===2){if(mode==='real')return setView('realSetup');if(mode==='game')return setView('game');return startInfinity()}if(mode==='real')return open('t1setup');if(mode==='game')return startPractice('game');return startPractice('inf')};
const css=document.createElement('style');
css.textContent=`.t1level{display:grid;grid-template-columns:1fr 1fr;gap:5px;background:#0d192b;border:1px solid #273b5a;border-radius:17px;padding:5px;margin:0 0 10px}.t1level button{border:0;border-radius:13px;padding:10px 5px;background:transparent;color:#8296b4;font-size:11px;font-weight:900}.t1level button.on{background:linear-gradient(135deg,#4e86ff,#8065ff);color:#fff}.t1setup{display:grid;gap:9px}.t1setup button{border:1px solid #2c4264;background:linear-gradient(145deg,#102039,#172b49);color:#fff;border-radius:21px;padding:16px;text-align:left}.t1setup b{font-size:16px}.t1setup small{float:right;color:#87b4ff}.t1setup p{font-size:10px;color:#9db1ce;line-height:1.5;margin:6px 0 0}.t1head{background:#0d1b30;border:1px solid #2b4164;border-radius:19px;padding:12px;margin-bottom:10px}.t1head>div{display:flex;justify-content:space-between;align-items:center}.t1head strong{font-size:21px}.t1bar{height:6px;background:#182941;border-radius:99px;overflow:hidden;margin-top:8px}.t1bar i{display:block;height:100%;background:linear-gradient(90deg,#4d9cff,#8c70ff)}.t1audio{width:100%;border:0;border-radius:15px;padding:13px;background:#152d50;color:#fff;font-weight:900;margin-bottom:11px}.t1nav{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.t1nav button{border:0;border-radius:14px;padding:13px;font-weight:900}.t1nav .p{background:#e9eef6;color:#34445d}.t1nav .n{background:#286cff;color:#fff}.t1hud{display:flex;gap:6px;overflow:auto;margin-bottom:9px}.t1hud span{white-space:nowrap;background:#10213a;border:1px solid #2d4669;border-radius:99px;padding:7px 10px;font-size:10px;color:#c7d7ed}.t1result{background:linear-gradient(150deg,#11233e,#1b3154);border:1px solid #34517d;border-radius:24px;padding:18px}.t1score{font-size:44px;font-weight:950;margin:13px 0}.t1score small{font-size:14px;color:#9fb4d1}.t1split{display:grid;grid-template-columns:1fr 1fr;gap:8px}.t1split div{background:#0d1b30;border-radius:15px;padding:12px}.t1split b{display:block;font-size:20px}.t1wrong{display:flex;flex-wrap:wrap;gap:5px;margin-top:11px}.t1wrong span{padding:5px 7px;border-radius:9px;background:#48212c;color:#ffcad2;font-size:9px}`;
document.head.appendChild(css);
home=function(sc){navActive('home');setProgress(0);sc.classList.add('tqHome');const lv=level(),hero=ASSETS['exam_student.png'];sc.innerHTML=`<section class="tqHero"><img src="${hero}" alt="TOPIK QUEST"><div class="tqHeroBrand"><b>TOPIK QUEST</b><small>KOREAN MASTERY</small></div><div class="tqBubble">오늘도 한 문제씩, 한국어를 더 가깝게.</div><div class="tqHeroFoot"><b>시험 레벨과 연습 방식을 선택하세요</b><small>TOPIK I · TOPIK II</small></div></section><div class="t1level"><button class="${lv===1?'on':''}" onclick="tqSetLevel(1)">TOPIK I · 1~2급</button><button class="${lv===2?'on':''}" onclick="tqSetLevel(2)">TOPIK II · 3~6급</button></div><div class="tqModeGrid"><button class="tqMode exam" onclick="tqStartMode('real')"><div class="fakeArt"><span>🎧📝</span></div><div class="copy"><b>${tr('real')}</b><small>${lv===1?'듣기 30 · 읽기 40':'실제 시험 형식으로 집중 연습'}</small></div></button><button class="tqMode game" onclick="tqStartMode('game')"><div class="fakeArt"><span>⚔️👾</span></div><div class="copy"><b>게임모드</b><small>${lv===1?'TOPIK I 랜덤 10문항 배틀':'몬스터를 물리치며 학습'}</small></div></button><button class="tqMode inf" onclick="tqStartMode('infinity')"><div class="fakeArt"><span>🐱∞</span></div><div class="copy"><b>${tr('infinity')}</b><small>${lv===1?'TOPIK I 70문항 무한 연습':'무한 문제 풀이'}</small></div></button></div><div class="tqSectionHead"><b>빠른 연습</b><span>${lv===1?'TOPIK I':'TOPIK II'}</span></div><div class="tqQuick"><button onclick="setView('speaking')"><i>🎙</i><b>말하기 연습</b><small>읽기·따라하기·발음 점수</small></button><button onclick="setView('review')"><i>↻</i><b>${tr('review')}</b><small>틀린 문제 다시 확인</small></button></div>`};
function renderSetup(sc){navActive('home');sc.innerHTML=`<div class="sectionTitle"><h2>TOPIK I · 실전모드</h2><span>70 QUESTIONS</span></div><div class="infoCard"><h3>TOPIK I 모의연습 세트</h3><p>독자 제작 문제로 듣기 30문항과 읽기 40문항을 연습합니다.</p></div><div class="t1setup"><button onclick="t1Begin('full')"><small>100 MIN</small><b>🎓 전체 실전</b><p>듣기 30 → 읽기 40, 총 70문항</p></button><button onclick="t1Begin('listening')"><small>40 MIN</small><b>🎧 듣기만</b><p>30문항 · 실전에서는 각 문항 1회 재생</p></button><button onclick="t1Begin('reading')"><small>60 MIN</small><b>📖 읽기만</b><p>40문항</p></button></div><button class="primary alt" style="margin-top:12px" onclick="setView('home')">홈으로</button>`}
window.t1Begin=k=>{clearQ();const m=k==='listening'?40:k==='reading'?60:100;Q={mode:'real',kind:k,ids:pool(k).map(x=>x.id),i:0,answers:{},played:{},started:Date.now(),duration:m*60};saveQ();open('t1quiz')};
function startPractice(mode){clearQ();const first=mode==='game'?shuffle(A).slice(0,10):[A[Math.floor(Math.random()*A.length)]];Q={mode,kind:'all',ids:first.map(x=>x.id),i:0,answers:{},played:{},score:0,total:0,streak:0,locked:false};saveQ();open('t1quiz')}
function cur(){restore();return Q?find(Q.ids[Q.i]):null}
function choices(q,sel,locked){return q.choices.map((c,i)=>{let z='choice';if(sel===i)z+=' selected';if(locked&&i===q.answerIndex)z+=' correct';if(locked&&sel===i&&i!==q.answerIndex)z+=' wrong';return `<button class="${z}" ${locked?'disabled':''} onclick="t1Pick(${i})"><span class="n">${i+1}</span><span>${E(c)}</span></button>`}).join('')}
window.t1Pick=i=>{restore();if(!Q||Q.locked)return;Q.answers[cur().id]=i;saveQ();render()};
function body(q,locked){const sel=Q.answers[q.id],aud=q.section==='listening'?`<button class="t1audio" onclick="t1Play(${q.id})" ${Q.mode==='real'&&Q.played[q.id]?'disabled':''}>${Q.mode==='real'&&Q.played[q.id]?'✓ 재생 완료':'▶ 듣기'}</button>`:'';return `<div class="instruction">${E(q.instruction)}</div>${aud}${q.stem?`<div class="stem">${E(q.stem)}</div>`:''}${q.prompt?`<div class="stem" style="font-size:14px">${E(q.prompt)}</div>`:''}<div class="choices">${choices(q,sel,locked)}</div>${locked?`<div class="resultStrip ${sel===q.answerIndex?'good':'bad'}">${sel===q.answerIndex?'정답입니다.':'정답: '+(q.answerIndex+1)+'번'} · ${E(q.explanation)}</div>`:''}`}
window.t1Next=()=>{restore();if(!Q)return;stopAudio();if(Q.mode==='real'){Q.i++;if(Q.i>=Q.ids.length)return finish();saveQ();return render()}if(!Q.locked){const q=cur(),sel=Q.answers[q.id];if(sel==null)return;const ok=sel===q.answerIndex;Q.locked=true;Q.total++;if(ok){Q.score++;Q.streak++}else Q.streak=0;saveQ();return render()}if(Q.mode==='game'){Q.i++;if(Q.i>=Q.ids.length)return finish();Q.locked=false;saveQ();return render()}const nq=A[Math.floor(Math.random()*A.length)];Q.ids=[nq.id];Q.i=0;Q.answers={};Q.played={};Q.locked=false;saveQ();render()};
window.t1Prev=()=>{restore();if(Q?.mode==='real'&&Q.i>0){stopAudio();Q.i--;saveQ();render()}};
function result(){let lc=0,lt=0,rc=0,rt=0,w=[];for(const id of Q.ids){const q=find(id),ok=Q.answers[id]===q.answerIndex;if(q.section==='listening'){lt++;if(ok)lc++}else{rt++;if(ok)rc++}if(!ok)w.push(id)}const ls=lt?Math.round(lc/lt*100):0,rs=rt?Math.round(rc/rt*100):0;return {lc,lt,rc,rt,ls,rs,total:(lt?ls:0)+(rt?rs:0),wrong:w}}
function finish(){stopAudio();stopTimer();Q.result=Q.mode==='real'?result():{score:Q.score,total:Q.total};saveQ();open('t1result')}
function tick(){stopTimer();if(Q.mode!=='real')return;const f=()=>{const s=seconds(),e=document.getElementById('t1clock');if(e)e.textContent=clock(s);if(s<=0)finish()};f();timer=setInterval(f,1000)}
function renderQuiz(sc){restore();if(!Q)return open('t1setup');const q=cur();if(!q)return open('home');if(Q.mode==='real'&&seconds()<=0)return finish();const sel=Q.answers[q.id],locked=Q.mode!=='real'&&Q.locked;const top=Q.mode==='real'?`<div class="t1head"><div><span><b>TOPIK I · ${q.section==='listening'?'듣기':'읽기'}</b><small style="display:block;color:#91a5c2">${Q.i+1}/${Q.ids.length}</small></span><strong id="t1clock">--:--</strong></div><div class="t1bar"><i style="width:${(Q.i+1)/Q.ids.length*100}%"></i></div></div>`:`<div class="t1hud"><span>${Q.mode==='game'?'⚔️ GAME 10':'♾ INFINITY'}</span><span>정답 ${Q.score}/${Q.total}</span><span>🔥 ${Q.streak}</span>${Q.mode==='game'?`<span>${Q.i+1}/10</span>`:''}</div>`;sc.innerHTML=`${top}<div class="card"><div class="qmeta"><div class="qno">${q.id}</div><span class="cat">${E(q.group)}</span></div>${body(q,locked)}${Q.mode==='real'?`<div class="t1nav"><button class="p" onclick="t1Prev()" ${Q.i===0?'disabled':''}>‹ 이전</button><button class="n" onclick="t1Next()">${Q.i===Q.ids.length-1?'제출':'다음'} ›</button></div>`:`<button class="attack" style="width:100%;border:0;border-radius:15px;padding:14px;margin-top:12px;font-weight:950" onclick="t1Next()" ${sel==null&&!locked?'disabled':''}>${locked?'다음 문제 ›':'정답 확인'}</button>`}</div><button class="primary alt" style="margin-top:10px" onclick="setView('home')">종료</button>`;tick()}
function renderResult(sc){restore();if(!Q?.result)return open('home');if(Q.mode!=='real'){const r=Q.result;sc.innerHTML=`<div class="t1result"><h2>${Q.mode==='game'?'⚔️ 배틀 완료':'♾ 연습 종료'}</h2><div class="t1score">${r.score}<small> / ${r.total}</small></div><p>정확도 ${r.total?Math.round(r.score/r.total*100):0}%</p></div><button class="primary" style="margin-top:10px" onclick="setView('home')">홈</button>`;return}const r=Q.result,full=r.lt&&r.rt,score=full?r.total:(r.lt?r.ls:r.rs),den=full?200:100,grade=full?(r.total>=140?'2급':r.total>=80?'1급':'등급 전'):'';sc.innerHTML=`<div class="t1result"><small>TOPIK I · PRACTICE RESULT</small><h2>✅ 풀이 완료</h2><div class="t1score">${score}<small> / ${den}</small></div>${full?`<b style="font-size:18px">연습 판정: ${grade}</b>`:''}<div class="t1split" style="margin-top:12px">${r.lt?`<div><small>듣기</small><b>${r.ls}</b><small>${r.lc}/${r.lt}</small></div>`:''}${r.rt?`<div><small>읽기</small><b>${r.rs}</b><small>${r.rc}/${r.rt}</small></div>`:''}</div>${r.wrong.length?`<div class="t1wrong">${r.wrong.map(x=>`<span>Q${x}</span>`).join('')}</div>`:''}</div><button class="primary" style="margin-top:10px" onclick="setView('home')">홈</button>`}
const baseRender=render;
render=function(){if(['t1setup','t1quiz','t1result'].includes(S.view)){try{hideSelection()}catch(e){};try{renderShell()}catch(e){};const sc=$('screen');sc.className='screen';sc.innerHTML='';if(S.view==='t1setup')return renderSetup(sc);if(S.view==='t1quiz')return renderQuiz(sc);return renderResult(sc)}return baseRender()};
const baseSetView=setView;
setView=function(v){if(/^t1/.test(S.view||'')&&!/^t1/.test(v||'')){stopAudio();stopTimer()}return baseSetView(v)};
window.TOPIK1_QUESTIONS=A;
if(S.view==='home')setTimeout(()=>render(),0)
})();
