const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const E=require('../growth-learning-engine.js'),D=require('../data/growth-learning.js');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8'),clone=x=>JSON.parse(JSON.stringify(x));
const recipe=id=>D.recipes.find(r=>r.id===id);
function answer(q){if(q.kind==='text')return q.accepted[0];if(q.rows)return Object.fromEntries(q.rows.map(r=>[r.id,r.answer]));if(q.cards)return Object.fromEntries(q.cards.map(r=>[r.id,r.answer]));return clone(q.answer);}
function step(s,type,value,now=Date.now()){return E.transition(s,{type,...value},recipe(s.recipeId),now).session;}
function solved(id='meaning',sid='test-session'){let s=E.createSession(recipe(id),sid,1);s=step(s,'begin',{},2);for(const p of ['learn','transfer']){if(p==='transfer')s=step(s,'continue',{},5);if(recipe(id)[p].kind==='listen')s=step(s,'heard',{},6);s=step(s,'draft',{value:answer(recipe(id)[p])},7);s=step(s,'submit',{},8);}return s;}
let uid=0;
function harness({seed,storage=new Map(),ledger=new Map(),tts,failSave=false}={}){
 if(seed!==undefined)storage.set('harumalGrowthLearningV1',typeof seed==='string'?seed:JSON.stringify(seed));
 const events={},nodes=[],body={children:[],style:{overflow:''},appendChild(node){this.children.push(node);nodes.push(node);}},document={body,readyState:'complete',activeElement:{focus(){}},createElement(){return {hidden:false,dataset:{},listeners:{},setAttribute(){},addEventListener(type,fn){this.listeners[type]=fn;},contains(){return true;},querySelector(){return null;},querySelectorAll(){return []},innerHTML:''};}};
 const history={state:null,pushState(state){this.state=state;},replaceState(state){this.state=state;},back(){this.state=null;for(const fn of events.popstate||[])fn({state:null});}};
 const rewards={newSession(){return `growth-test-${++uid}`},answer(payload){return grant(payload,'answer',10,2);},stage(payload){return grant(payload,'stage',payload.phase==='learn'?20:30,payload.phase==='learn'?4:6);}};
 function grant(payload,kind,xp,coins){const id=`${kind}:${payload.sessionId}:${payload.slot||payload.stageId}`;if(ledger.has(id))return{awarded:false,duplicate:true,xp:0,coins:0,event:ledger.get(id),persisted:true};const event={...payload,id,kind,xp,coins};ledger.set(id,event);return{awarded:true,xp,coins,event,persisted:true};}
 const c={console,Date,Math,history,location:{href:'https://example.test/'},document,S:{lang:'ko'},localStorage:{getItem:key=>storage.get(key)||null,setItem(key,value){if(failSave)throw new Error('quota');storage.set(key,String(value));}},addEventListener(type,fn){(events[type]??=[]).push(fn)},HARUMAL_REWARDS:rewards,MALBIT_TTS:{play:tts||(()=>Promise.resolve({})),cancel(){}},crypto:{randomUUID:()=>`tab-${++uid}`}};c.window=c;vm.createContext(c);for(const file of ['data/growth-learning.js','growth-learning-engine.js','growth-learning.js'])vm.runInContext(read(file),c);
 const root=()=>nodes[0];
 return {c,storage,ledger,root,events,open:id=>c.HARUMAL_GROWTH.open(id),state:()=>clone(c.HARUMAL_GROWTH.getState()),current:()=>{const s=c.HARUMAL_GROWTH.getState();return clone(s.sessions[s.currentId]);},click(action,extra={}){const button={dataset:{growthAction:action,...extra},disabled:false};root().listeners.click({target:{closest:()=>button}});},emit(type,event){for(const fn of events[type]||[])fn(event);}};
}
function choose(h,value,field){h.click('select',{value,field:field||''});}
function finishMeaning(h,{help=false,wrong=false}={}){h.click('begin');if(help){h.click('help',{help:'isoo'});h.click('help',{help:'man'});}if(wrong){choose(h,'junho');h.click('submit');h.click('retry');}choose(h,'minji');h.click('submit');h.click('continue');choose(h,'sora');h.click('submit');}

test('11 original type recipes contain 22 authored, distinct tasks and valid answers',()=>{
 assert.equal(D.recipes.length,11);assert.equal(new Set(D.recipes.map(r=>r.type)).size,11);const ids=[];const kinds=new Set();
 for(const r of D.recipes){assert.ok(r.goal&&r.rule);assert.notEqual(r.learn.id,r.transfer.id);for(const q of [r.learn,r.transfer]){ids.push(q.id);kinds.add(q.kind);assert.ok(['easy','medium','hard','very_hard'].includes(q.difficulty));assert.ok(q.prompt&&q.hint&&q.retry&&q.explain);assert.ok(E.grade(q,answer(q)),q.id);assert.equal(E.grade(q,'unrelated'),false,q.id);}}
 assert.equal(new Set(ids).size,22);assert.ok(kinds.size>=9);assert.match(recipe('grammar').learn.rows[0].text,/예상과 달랐어요/);assert.match(recipe('grammar').transfer.rows[0].text,/예상과 달랐어요/);
 assert.equal(recipe('meaning').learn.text,'교육 이수자만 입장 가능');assert.equal(recipe('meaning').transfer.text,'예약자만 입장 가능');assert.match(recipe('meaning').transferScope,/‘이수자’/);
});
test('state machine forbids skipping and awards intents only on actual correct completion',()=>{
 let s=E.createSession(recipe('meaning'),'state-test',1);assert.equal(E.transition(s,{type:'continue'},recipe('meaning')).changed,false);assert.equal(s.records.learn.rewardIntent,undefined);
 s=step(s,'begin',{},2);assert.equal(E.transition(s,{type:'submit'},recipe('meaning')).reason,'incomplete');s=step(s,'draft',{value:'junho'},3);s=step(s,'submit',{},4);assert.equal(s.stage,'learn');assert.equal(s.records.learn.rewardIntent,undefined);assert.equal(E.transition(s,{type:'submit'},recipe('meaning')).changed,false);
 s=step(s,'retry',{},5);s=step(s,'draft',{value:'minji'},6);s=step(s,'submit',{},7);assert.equal(s.stage,'learn-complete');assert.deepEqual(s.records.learn.rewardIntent,{answer:true,stage:true});assert.equal(E.summary(s).learn.independent,false);assert.equal(E.summary(s).learn.retries,1);assert.equal(E.transition(s,{type:'submit'},recipe('meaning')).changed,false);
});
test('requested word help, first attempt, retries and independent transfer stay separate',()=>{
 let s=E.createSession(recipe('meaning'),'support-test',1);s=step(s,'begin',{},2);s=step(s,'help',{id:'isoo'},3);s=step(s,'help',{id:'man'},4);s=step(s,'draft',{value:'minji'},5);s=step(s,'submit',{},6);s=step(s,'continue',{},7);s=step(s,'draft',{value:'sora'},8);s=step(s,'submit',{},9);
 const summary=E.summary(s);assert.equal(summary.learn.firstAttemptCorrect,true);assert.equal(summary.learn.helpCount,2);assert.equal(summary.learn.independent,false);assert.equal(summary.transfer.independent,true);assert.equal(s.records.learn.firstAttempt.requestedHelp,true);
});
test('all recipes complete with their interaction-specific structured answers',()=>{for(const r of D.recipes){const s=solved(r.id,`solve-${r.id}`);assert.equal(s.stage,'summary',r.id);assert.equal(E.validSession(s),true,r.id);assert.ok(E.summary(s).transfer.independent,r.id);}});
test('listening requires actual playback or explicitly assisted transcript',()=>{
 let s=E.createSession(recipe('listening'),'audio-test',1);s=step(s,'begin',{},2);s=step(s,'draft',{value:'three'},3);assert.equal(E.transition(s,{type:'submit'},recipe('listening')).reason,'listen-first');s=step(s,'help',{id:'transcript'},4);s=step(s,'submit',{},5);assert.equal(s.records.learn.complete,true);assert.equal(E.summary(s).learn.independent,false);
});
test('writing checks bounded forms and punctuation without claiming semantic free writing',()=>{const q=recipe('writing').learn;assert.ok(E.grade(q,'  저는 공원에   가고 싶어요. '));assert.ok(E.grade(q,'공원에 가고 싶습니다!'));assert.equal(E.grade(q,'공원에 가고 싶지 않아요'),false);assert.equal(E.grade(q,'산책을 하고 싶어요'),false);assert.match(q.retry,/정해진 문장/);});
test('merge unions independent sessions and concurrent attempts, preserving completion',()=>{
 const a=E.empty(),b=E.empty();a.sessions.a=solved('meaning','a');a.currentId='a';b.sessions.b=solved('grammar','b');b.currentId='b';const joined=E.merge(a,b);assert.deepEqual(Object.keys(joined.sessions).sort(),['a','b']);assert.equal(joined.sessions.a.stage,'summary');
 let base=E.createSession(recipe('meaning'),'same',1);base=step(base,'begin',{},2);let wrong=step(base,'draft',{value:'junho'},3),right=step(base,'draft',{value:'minji'},3);wrong=step(wrong,'submit',{},4);right=step(right,'submit',{},4);assert.notEqual(wrong.records.learn.attempts[0].id,right.records.learn.attempts[0].id);const x={...E.empty(),currentId:'same',sessions:{same:wrong}},y={...E.empty(),currentId:'same',sessions:{same:right}},merged=E.merge(x,y);assert.equal(merged.sessions.same.records.learn.attempts.length,2);assert.equal(E.summary(merged.sessions.same).learn.independent,false);
});
test('strict validation rejects null attempts, mismatched IDs, fake completion and corrupted evidence',()=>{
 const state={...E.empty(),sessions:{good:solved('meaning','good')},currentId:'good'};assert.equal(E.validate(state,D.recipes),true);
 for(const mutate of [x=>x.sessions.good.records.learn.attempts.push(null),x=>x.sessions.good.id='bad',x=>x.sessions.good.records.learn.attempts[0].correct='true',x=>x.sessions.good.records.learn.attempts[0].id=null,x=>x.sessions.good.records.learn.attempts[0].answer='junho',x=>x.sessions.good.records.learn.complete=false,x=>x.version=2]){const bad=clone(state);mutate(bad);assert.equal(E.validate(bad,D.recipes),false);}
 const fake={...E.empty(),sessions:{fake:E.createSession(recipe('meaning'),'fake',1)},currentId:'fake'};fake.sessions.fake.stage='summary';assert.equal(E.validate(fake),false);
});
test('UI grants answer and stage separately only after completion; reload and navigation do not regrant',()=>{
 const h=harness();h.open('meaning');assert.equal(h.ledger.size,0);assert.equal(h.current().stage,'orientation');assert.doesNotMatch(h.root().innerHTML,/모르는 낱말을 짚고/);finishMeaning(h,{help:true,wrong:true});assert.equal(h.current().stage,'summary');assert.equal(h.ledger.size,4);assert.deepEqual([...h.ledger.values()].filter(e=>e.kind==='stage').map(e=>[e.xp,e.coins]),[[20,4],[30,6]]);assert.match(h.root().innerHTML,/문항 정답/);assert.match(h.root().innerHTML,/단계 완료/);
 const old=h.current().id,restored=harness({storage:h.storage,ledger:h.ledger});assert.equal(restored.current().stage,'summary');assert.equal(restored.root().hidden,false);assert.equal(h.ledger.size,4);restored.c.HARUMAL_GROWTH.close();restored.open('meaning');assert.equal(restored.current().id,old);assert.equal(h.ledger.size,4);
 restored.click('repeat',{recipe:'meaning'});assert.notEqual(restored.current().id,old);assert.equal(restored.current().repeated,true);finishMeaning(restored);assert.equal(restored.ledger.size,8);assert.match(restored.root().innerHTML,/반복 문항 연습 완료/);assert.equal(restored.c.HARUMAL_GROWTH.status().independentTransfers,1);
});
test('in-progress draft, requested help, wrong feedback and stable session survive reload and back',()=>{
 const h=harness();h.open('meaning');h.click('begin');h.click('help',{help:'isoo'});choose(h,'junho');h.click('submit');const id=h.current().id,reload=harness({storage:h.storage,ledger:h.ledger});assert.equal(reload.current().id,id);assert.equal(reload.current().records.learn.feedback,'wrong');assert.equal(reload.current().records.learn.draft,'junho');assert.deepEqual(reload.current().records.learn.help,['isoo']);reload.emit('popstate',{state:null});assert.equal(reload.root().hidden,true);reload.open('meaning');assert.equal(reload.current().id,id);assert.equal(reload.current().records.learn.attempts.length,1);assert.equal(reload.ledger.size,0);
});
test('malformed roots are not overwritten and cannot break module startup',()=>{for(const seed of ['{broken',JSON.stringify({version:2}),JSON.stringify({...E.empty(),sessions:{bad:{id:'bad',stage:'summary',records:{learn:{attempts:[null]}}}}})]){const h=harness({seed});assert.doesNotThrow(()=>h.open('meaning'));assert.equal(h.storage.get('harumalGrowthLearningV1'),seed);assert.match(h.root().innerHTML,/덮어쓰지 않았어요/);assert.throws(()=>h.c.HARUMAL_GROWTH.mergeImport(E.empty()));}});
test('completed imports do not mint rewards; local pending intents resume exactly once',()=>{
 const imported={...E.empty(),sessions:{imported:solved('meaning','imported')},currentId:'imported'},h=harness();h.c.HARUMAL_GROWTH.validateImport(imported);const raw=h.c.HARUMAL_GROWTH.mergeImport(imported);h.storage.set('harumalGrowthLearningV1',raw);assert.equal(JSON.parse(raw).sessions.imported.records.learn.rewardIntent,undefined);const restored=harness({storage:h.storage,ledger:h.ledger});restored.open('meaning');assert.equal(restored.ledger.size,0);
 const pending=harness({seed:imported});assert.equal(pending.ledger.size,4);const again=harness({storage:pending.storage,ledger:pending.ledger});assert.equal(again.ledger.size,4);
});
test('two tabs durably converge a lost-write union after storage events',()=>{
 const storage=new Map(),a=harness({storage}),b=harness({storage});a.open('meaning');const aRaw=storage.get('harumalGrowthLearningV1');storage.delete('harumalGrowthLearningV1');b.open('grammar');const bRaw=storage.get('harumalGrowthLearningV1');storage.set('harumalGrowthLearningV1',aRaw);
 a.emit('storage',{key:'harumalGrowthLearningV1',newValue:bRaw});b.emit('storage',{key:'harumalGrowthLearningV1',newValue:aRaw});const union=JSON.parse(storage.get('harumalGrowthLearningV1'));assert.equal(Object.keys(union.sessions).length,2);const reloaded=harness({storage});assert.equal(Object.keys(reloaded.state().sessions).length,2);
});
test('old audio completion cannot mark a different phase as heard',async()=>{
 let finish;const h=harness({tts:()=>new Promise(resolve=>{finish=resolve;})});h.open('listening');h.click('begin');h.click('listen');h.click('help',{help:'transcript'});choose(h,'three');h.click('submit');h.click('continue');assert.equal(h.current().records.transfer.heard,false);finish({});await new Promise(setImmediate);assert.equal(h.current().records.transfer.heard,false);
});
test('unavailable device audio never counts as heard',async()=>{const h=harness({tts:()=>Promise.resolve({unavailable:true})});h.open('listening');h.click('begin');h.click('listen');await new Promise(setImmediate);assert.equal(h.current().records.learn.heard,false);assert.match(h.root().innerHTML,/음성 재생이 어려워요/);});
test('semantic tokens, 44px targets and approved assets are used; no Shorts or full-bank mutation',()=>{const css=read('growth-learning.css'),js=read('growth-learning.js');assert.match(css,/min-height:48px/);assert.match(css,/var\(--ui-canvas\)/);assert.match(css,/@media\(max-width:350px\)/);assert.match(js,/assets\/art\/haruman\//);assert.doesNotMatch(js,/topikQuestShortsV1|question-bank-v1-part|setView\(/);for(const pose of ['lesson-welcome','answer-correct','answer-retry','lesson-complete','audio-listening'])assert.ok(fs.existsSync(path.join(__dirname,'../assets/art/haruman',`${pose}-v2.webp`)));});
