const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const read=f=>fs.readFileSync(require('node:path').join(__dirname,'..',f),'utf8');
function boot(view='home'){
 const nav={dataset:{},innerHTML:'',querySelectorAll:()=>[]};const screen={className:'',innerHTML:'',querySelector:()=>null,insertAdjacentHTML(_,html){this.innerHTML=html+this.innerHTML}};const calls=[];
 const c={S:{view,lang:'ja',vocab:[{term:'안녕'}]},document:{body:{classList:{add(){},toggle(){}}},documentElement:{dataset:{theme:'light'}},querySelectorAll:()=>[],querySelector:q=>q==='.nav'?nav:null,getElementById:()=>screen},requestAnimationFrame:fn=>fn(),renderShell(){},render(){screen.innerHTML='existing';return 7},setView(v){calls.push(v);c.S.view=v;c.render()},tqStartMode(v){calls.push(v)},tqSetLearningPath(v){calls.push(v)},tqSetLevel(v){calls.push(v)}};c.window=c;vm.createContext(c);vm.runInContext(read('harumal-ui.js'),c);return{c,nav,screen,calls};
}
test('Harumal routes preserve all learning engines and active tab groups',()=>{const{c,calls}=boot();for(const view of ['beginner','t1quiz','shorts','speaking','realSetup','learn'])assert.equal(c.HARUMAL_UI.activeTab(view),'learn');for(const view of ['vocab','stats','more'])assert.equal(c.HARUMAL_UI.activeTab(view),'more');c.harumalGo('travel');assert.deepEqual(calls,['travel']);c.harumalGo('unsupported');assert.equal(calls.length,1);c.harumalCourse('beginner');assert.deepEqual(calls.slice(-2),['beginner','beginner']);c.harumalCourse('topik2');assert.deepEqual(calls.slice(-2),[2,'home'])});
test('new learning route renders on refresh and My uses real saved vocabulary',()=>{const{c,nav,screen}=boot('learn');assert.equal(c.render(),7);assert.match(screen.innerHTML,/ハングルから/);assert.equal((nav.innerHTML.match(/<button /g)||[]).length,5);c.setView('more');assert.match(screen.innerHTML,/1語を保存/);assert.match(screen.innerHTML,/existing/);assert.doesNotMatch(read('harumal-ui.js'),/localStorage\.(setItem|removeItem|clear)/)});
test('Harumal assets are available offline without changing the legacy backup contract',()=>{assert.match(read('index.html'),/harumal-ui\.css\?v=/);assert.match(read('site-patch.js'),/'vocab-editor.js',\s*'harumal-ui.js'/);assert.match(read('sw.js'),/'\.\/harumal-ui.css'/);assert.equal(JSON.parse(read('manifest.webmanifest')).short_name,'하루말');assert.match(read('product-polish.js'),/app:'MALBIT'/);assert.match(read('product-polish.js'),/data\?\.app!=='MALBIT'/)});
