const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const read=f=>fs.readFileSync(require('node:path').join(__dirname,'..',f),'utf8');
function boot(view='home'){
 const nav={dataset:{},innerHTML:'',querySelectorAll:()=>[]};const screen={className:'',innerHTML:'',children:[],append(){},querySelector:()=>null,insertAdjacentHTML(_,html){this.innerHTML=html+this.innerHTML}};const calls=[];
 const c={S:{view,lang:'ja',vocab:[{term:'안녕'}]},document:{createElement:()=>({append(){},textContent:'',className:''}),body:{classList:{add(){},toggle(){}}},documentElement:{dataset:{theme:'light'}},querySelectorAll:()=>[],querySelector:q=>q==='.nav'?nav:null,getElementById:()=>screen},requestAnimationFrame:fn=>fn(),renderShell(){},render(){screen.innerHTML='existing';return 7},setView(v){calls.push(v);c.S.view=v;c.render()},tqStartMode(v){calls.push(v)},tqSetLearningPath(v){calls.push(v)},tqSetLevel(v){calls.push(v)}};c.window=c;vm.createContext(c);vm.runInContext(read('harumal-ui.js'),c);return{c,nav,screen,calls};
}
test('Harumal routes preserve all learning engines and active tab groups',()=>{const{c,calls}=boot();for(const view of ['beginner','t1quiz','shorts','speaking','realSetup','learn'])assert.equal(c.HARUMAL_UI.activeTab(view),'home');for(const view of ['stats','more'])assert.equal(c.HARUMAL_UI.activeTab(view),'home');for(const view of ['vocab','vocabTest','vocabEditor'])assert.equal(c.HARUMAL_UI.activeTab(view),'vocab');assert.equal(c.HARUMAL_UI.activeTab('travelAdventure'),'home');c.harumalGo('vocab');assert.deepEqual(calls,['vocab']);c.harumalGo('unsupported');assert.equal(calls.length,1);c.harumalCourse('beginner');assert.deepEqual(calls.slice(-2),['beginner','beginner']);c.harumalCourse('topik2');assert.deepEqual(calls.slice(-2),[2,'random'])});
test('new learning route renders on refresh and My uses real saved vocabulary',()=>{const{c,nav,screen}=boot('learn');assert.equal(c.render(),7);assert.match(screen.innerHTML,/ハングルから/);assert.equal((nav.innerHTML.match(/<button /g)||[]).length,3);c.setView('more');assert.match(screen.innerHTML,/1語を保存/);assert.match(screen.innerHTML,/existing/);assert.doesNotMatch(read('harumal-ui.js'),/localStorage\.(setItem|removeItem|clear)/)});
test('Harumal assets are available offline without changing the legacy backup contract',()=>{assert.match(read('index.html'),/harumal-ui\.css\?v=/);assert.match(read('site-patch.js'),/'vocab-editor.js',\s*'vocab-test.js',\s*'app-touch.js',\s*'travel-adventure.js',\s*'haruman-mascot.js',\s*'harumal-ui.js'/);assert.match(read('sw.js'),/'\.\/harumal-ui.css'/);assert.equal(JSON.parse(read('manifest.webmanifest')).short_name,'하루말');assert.match(read('product-polish.js'),/app:'MALBIT'/);assert.match(read('product-polish.js'),/data\?\.app!=='MALBIT'/)});

test('TOPIK exam title and timer have readable paired ink on the fixed navy header',()=>{const css=read('harumal-ui.css'),header=read('topik1.js').match(/\.t1head\{([^}]+)\}/)[1],background=header.match(/background:(#[0-9a-f]{6})/)[1],foreground=css.match(/html body\.harumal \.t1head\{color:(#[0-9a-f]{6})\}/)[1];const luminance=hex=>{const v=hex.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*v[0]+.7152*v[1]+.0722*v[2]};const ratio=(a,b)=>(Math.max(luminance(a),luminance(b))+.05)/(Math.min(luminance(a),luminance(b))+.05);assert.ok(ratio(foreground,background)>=7,'title and timer meet AAA normal-text contrast');assert.ok(ratio('#91a5c2',background)>=4.5,'question count retains AA contrast');});
