const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const read=n=>fs.readFileSync(path.join(__dirname,'..',n),'utf8');
test('three-tab hub is final runtime owner and cached offline',()=>{assert.match(read('site-patch.js'),/'growth-learning-entrypoints.js',\s*'learning-hub.js'/);assert.match(read('index.html'),/learning-hub.css\?v=/);for(const asset of ['learning-hub.js','learning-hub.css','assets/harumal/ui/vocab-diary-empty-v1.webp']){assert.ok(fs.existsSync(path.join(__dirname,'..',asset)));assert.ok(read('sw.js').includes(asset))}});
test('path preferences join durable recovery and backup without clearing old state',()=>{for(const f of ['storage-guard.js','product-polish.js'])assert.ok(read(f).includes("'harumalLearningPathV1'"));assert.doesNotMatch(read('learning-hub.js'),/localStorage\.(removeItem|clear)/);assert.match(read('learning-hub.js'),/oldStage=legacy==='topik1'/)});
test('resume uses existing session owner and guided recipes really exist',()=>{const src=read('learning-hub.js');assert.match(src,/tqSetLearningPath\('topik1'\);tqHomeContinue\(\)/);const data=require('../data/growth-learning.js');for(const id of ['meaning','gist','inference'])assert.ok(data.recipes.some(x=>x.id===id));assert.doesNotMatch(src,/HARUMAL_GROWTH.open\('vocab'\)/)});
test('settings have dismissal, focus trapping, inert restoration and no destructive opening',()=>{const src=read('learning-hub.js');for(const token of ['Escape','Tab','aria-modal','settingsReturn','priorOverflow','harumalSettings','inertNodes','focusKey'])assert.ok(src.includes(token));assert.doesNotMatch(src,/resetAll\(\)|malbitResetProgress\(\)/);assert.match(src,/if\(settingsOpen\)return/)});
test('activity rewards are read-only and incomplete curriculum/shop are disclosed',()=>{const src=read('learning-hub.js');assert.doesNotMatch(src,/HARUMAL_REWARDS\.(answer|stage|reset)/);assert.match(src,/not a fully authored end-to-end course/);assert.match(src,/coin shop and diary sticker purchases are not available yet/)});
const vm=require('node:vm');
function hub(seed={},blocked=false){const data=new Map(Object.entries(seed)),calls=[];const c={S:{view:'home',lang:'ko'},localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>{if(blocked)throw Error('quota');data.set(k,String(v))}},document:{getElementById:()=>null},render:()=>{},setView:v=>calls.push(v),tqSetLearningPath:v=>calls.push('path:'+v),tqHomeContinue:()=>calls.push('resume-owner'),tqSetLevel:v=>calls.push('level:'+v),tqStartMode:v=>calls.push('mode:'+v),harumalCourse:v=>calls.push('course:'+v),malbitOpenGrammar:()=>calls.push('grammar'),toast:t=>calls.push('toast'),HARUMAL_GROWTH:{open:v=>calls.push('growth:'+v)},addEventListener:()=>{}};c.window=c;vm.createContext(c);vm.runInContext(read('learning-hub.js'),c);return {api:c.HARUMAL_HUB,data,calls}}
test('fresh and returning learner paths resolve without writing progress',()=>{for(const [legacy,want] of [[null,'hangul'],['beginner','hangul'],['topik1','topik1'],['topik2','topik2']]){const {api,data}=hub(legacy?{malbitProductPrefsV1:JSON.stringify({learningPath:legacy})}:{});assert.equal(api.getState().stage,want);assert.equal(data.has('harumalLearningPathV1'),false)}});
test('hub guards untrusted stored preferences and only explicit selections persist',()=>{const {api,data,calls}=hub({harumalLearningPathV1:JSON.stringify({stage:'<script>',goal:'bogus',palette:'url(evil)'})});assert.equal(api.getState().stage,'hangul');assert.equal(api.getState().goal,'advanced');assert.equal(api.getState().palette,'mint');api.showStage('invalid');assert.equal(calls.length,0);api.chooseStage('topik1');assert.equal(api.getState().stage,'topik1');assert.deepEqual(calls,['home']);assert.deepEqual(JSON.parse(data.get('harumalLearningPathV1')),{stage:'topik1',goal:'advanced',palette:'mint'})});
test('current stage starts its actual engine and TOPIK I delegates resume',()=>{for(const [stage,want] of [['hangul',['course:beginner']],['foundation',['grammar']],['topik1',['path:topik1','resume-owner']],['topik2',['growth:gist']],['advanced',['growth:inference']]]){const {api,calls}=hub({harumalLearningPathV1:JSON.stringify({stage})});api.continueLearning();assert.deepEqual(calls,want)}});
test('unavailable preference storage does not pretend a stage was selected',()=>{const {api,calls}=hub({},true);api.chooseStage('advanced');assert.deepEqual(calls,['toast']);assert.equal(api.getState().stage,'hangul')});
