const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
test('late media start after context changes cancels without consuming an attempt',async()=>{const b=boot({start:false});let valid=true,starts=0;const done=b.p.play({key:'q',isCurrent:()=>valid,onStart(){starts++}});valid=false;b.audio[0].onplaying();assert.equal((await done).cancelled,true);assert.equal(starts,0);assert.equal(b.audio[0].paused,true)});
test('legacy lookup receives cancellation context and cannot play after question changes',async()=>{const b=boot({segments:null});let valid=true,resolve,request;const done=b.p.play({key:'q',script:'x',isCurrent:()=>valid,legacy:r=>{request=r;return new Promise(v=>resolve=v)}});await Promise.resolve();assert.equal(request.isCurrent(),true);valid=false;assert.equal(request.isCurrent(),false);resolve('old.mp3');const result=await done;assert.equal(result.cancelled,true);assert.equal(result.started,false);assert.equal(b.audio.length,0)});
test('cancel before lookup microtask prevents starting the request',async()=>{const b=boot({segments:null});let calls=0;const done=b.p.play({key:'q',legacy:()=>{calls++;return 'old.mp3'}});b.p.cancel();await done;await Promise.resolve();assert.equal(calls,0)});
test('recorded answer blank is part of duration and stop cancels it',async()=>{const b=boot({segments:[{url:'a.mp3'},{pause:1200},{url:'b.mp3'}]});const done=b.p.play({key:'q'});assert.equal(b.elements['input[type="range"]'].max,5.2);b.audio[0].onended();const blank=[...b.timers.values()].find(v=>v.ms===1200);assert.ok(blank);b.p.cancel();blank.fn();assert.equal((await done).cancelled,true);assert.equal(b.audio[1].plays,undefined);assert.equal(b.timers.size,0)});
test('device unavailability restores failure state',async()=>{const b=boot();const done=b.p.play({key:'q',script:'hello',forceDevice:true});b.finishSpeech({unavailable:true});assert.equal((await done).error,true);assert.equal(b.elements['.listeningToggle'].disabled,false)});
test('owner HEAD helpers stop checking extensions as soon as request context expires',async()=>{for(const [file,name,call] of [['topik1.js','fileAudio','fileAudio(1,1,request)'],['legacy-core.js','findRecordedAudio','findRecordedAudio(1,request)']]){const src=fs.readFileSync(file,'utf8'),start=src.indexOf('async function '+name+'('),end=src.indexOf('\n',start);let valid=true,calls=0;const c={EXT:['mp3','m4a'],request:{isCurrent:()=>valid},recordedAudioCandidates:()=>['a.mp3','b.mp3'],fetch:async()=>{calls++;valid=false;return{ok:true}}};vm.createContext(c);vm.runInContext(src.slice(start,end),c);assert.equal(await vm.runInContext(call,c),null);assert.equal(calls,1,file)}});
function boot({segments=[{url:'F1/a.mp3'},{url:'M1/b.mp3'}],duration=2,reject=false,start=true}={}){
 const audio=[],timers=new Map(),intervals=new Map(),spoken=[],elements={};let timerId=0,rate=1,pendingSpeech;
 for(const key of ['.listeningToggle','input[type="range"]','output','[data-player-source]','.listeningMessage','.listeningFallback'])elements[key]={setAttribute(k,v){this[k]=v}};
 const root={dataset:{listeningPlayer:'q',playerOnce:'0',playerPlayed:'0'},querySelector:k=>elements[k],querySelectorAll:()=>[]};
 class Audio{constructor(){this.duration=duration;this.currentTime=0;audio.push(this)}load(){this.onloadedmetadata?.()}pause(){this.paused=true}removeAttribute(){this.src=''}play(){this.paused=false;this.plays=(this.plays||0)+1;if(reject)return Promise.reject(Error('missing'));if(start)this.onplaying?.();return Promise.resolve()}}
 const c={console,Audio,Date,Promise,document:{querySelectorAll:()=>[root]},setTimeout(fn,ms){const id=++timerId;timers.set(id,{fn,ms});return id},clearTimeout:id=>timers.delete(id),setInterval(fn){const id=++timerId;intervals.set(id,fn);return id},clearInterval:id=>intervals.delete(id),S:{lang:'ko'}};c.window=c;c.HARUMAL_LISTENING_AUDIO={resolve:()=>segments,cancel(){}};
 c.MALBIT_TTS={preferences:()=>({rate}),cancel(){pendingSpeech?.({cancelled:true});pendingSpeech=null},play(text,options){spoken.push({text,options});options.onStart?.();return new Promise(r=>pendingSpeech=r)}};c.malbitTtsSetRate=v=>rate=v;
 vm.createContext(c);vm.runInContext(fs.readFileSync('listening-player.js','utf8'),c);
 return{p:c.HARUMAL_LISTENING_PLAYER,audio,timers,intervals,spoken,root,elements,c,finishSpeech:result=>{const r=pendingSpeech;pendingSpeech=null;r(result||{})},gap(){const pair=[...timers.entries()].find(([,v])=>v.ms<1000);assert.ok(pair,'gap scheduled');timers.delete(pair[0]);pair[1].fn()},tick(){for(const fn of intervals.values())fn()}};
}
test('dialogue metadata totals include real clip durations and the inter-speaker gap',async()=>{const b=boot();const done=b.p.play({key:'q',script:'dialogue'});assert.equal(b.elements.output.textContent,'0:00 / 0:04');assert.equal(b.elements['input[type="range"]'].max,4.38);b.audio[0].currentTime=1;b.tick();assert.match(b.elements.output.textContent,/0:01/);b.audio[0].onended();b.gap();assert.equal(b.audio[1].plays,1);b.audio[1].onended();assert.equal((await done).cancelled,false);assert.equal(b.elements['.listeningToggle'].textContent,'▶ 재생')});
test('unknown duration never enables seeking or fabricates a total',async()=>{const b=boot({duration:NaN});const done=b.p.play({key:'q',script:'x'});assert.match(b.elements.output.textContent,/—:—/);assert.equal(b.elements['input[type="range"]'].disabled,true);b.p.seek(50);assert.equal(b.audio[1].plays,undefined);b.p.cancel();await done});
test('stop clears current and scheduled audio, resets position and ignores late callbacks',async()=>{const b=boot();const done=b.p.play({key:'q',script:'x'}),stale=b.audio[0].onended;b.audio[0].currentTime=1;b.p.cancel();stale();assert.equal((await done).cancelled,true);assert.equal(b.audio[0].paused,true);assert.equal(b.audio[1].plays,undefined);assert.equal(b.timers.size,0);assert.equal(b.intervals.size,0);assert.match(b.elements.output.textContent,/^0:00/)});
test('cancellation during legacy HEAD lookup cannot revive old audio',async()=>{const b=boot({segments:null});let resolve;const done=b.p.play({key:'q',script:'x',legacy:()=>new Promise(r=>resolve=r)});await Promise.resolve();b.p.cancel();resolve('old-question.mp3');await Promise.resolve();assert.equal((await done).cancelled,true);assert.equal(b.audio.length,0)});
test('rapid restart settles old work and stale rejection cannot stop new playback',async()=>{const b=boot();const old=b.p.play({key:'q',script:'x'}),stale=b.audio[0].onerror;const next=b.p.play({key:'q',script:'y'});stale();assert.equal((await old).cancelled,true);assert.equal(b.p.busy('q'),true);b.p.cancel();await next});
test('all rates apply to current clip, later male/female clips and gap duration',async()=>{for(const r of [.75,1,1.25,1.5]){const b=boot(),done=b.p.play({key:'q',script:'x'});b.p.setRate(r);assert.equal(b.audio[0].playbackRate,r);b.audio[0].onended();assert.ok([...b.timers.values()].some(v=>Math.abs(v.ms-380/r)<.01));b.gap();assert.equal(b.audio[1].playbackRate,r);b.p.cancel();await done}});
test('seeking across a dialogue uses cumulative source seconds and invalidates old callbacks',async()=>{const b=boot(),done=b.p.play({key:'q',script:'x'}),stale=b.audio[0].onended;b.p.seek(3);assert.equal(b.audio[1].plays,1);assert.ok(Math.abs(b.audio[1].currentTime-.62)<.001);stale();assert.equal(b.audio[1].plays,1);b.p.cancel();await done});
test('exam seeking remains disabled and actual start consumes only one attempt',async()=>{const b=boot();b.root.dataset.playerOnce='1';let starts=0;const done=b.p.play({key:'q',script:'x',once:true,onStart(){starts++;b.root.dataset.playerPlayed='1'}});b.p.seek(3);assert.equal(b.audio[1].plays,undefined);assert.equal(b.elements['.listeningToggle'].disabled,false);b.p.cancel();assert.equal((await done).started,true);assert.equal(starts,1);assert.equal(b.elements['.listeningToggle'].disabled,true)});
test('failure before start is error, never completed, and permits retry',async()=>{const b=boot({reject:true});let starts=0;const result=await b.p.play({key:'q',script:'x',onStart(){starts++}});assert.equal(result.error,true);assert.equal(result.started,false);assert.equal(starts,0);assert.equal(b.elements['.listeningToggle'].disabled,false);assert.equal(b.elements['.listeningFallback'].hidden,false)});
test('failure after start is distinct from stop and owners can restore exam attempt',async()=>{const b=boot();let consumed=false;const done=b.p.play({key:'q',script:'x',once:true,onStart(){consumed=true},onResult(r){if(r.error)consumed=false}});b.audio[0].onerror();assert.equal((await done).error,true);assert.equal(consumed,false)});
test('loading is stoppable and timeout failure never claims success',async()=>{const b=boot({start:false}),done=b.p.play({key:'q',script:'x'});assert.equal(b.elements['.listeningToggle'].textContent,'■ 정지');[...b.timers.values()].find(v=>v.ms===15000).fn();assert.equal((await done).error,true);assert.equal(b.elements['.listeningToggle'].textContent,'↻ 다시 시도')});
test('explicit device fallback keeps gender, rejects blanks, has no fake duration and restarts speech on speed change',async()=>{const b=boot(),done=b.p.play({key:'q',script:'여자: 안녕\n남자: 반가워\n여자: ____',forceDevice:true});assert.equal(b.spoken[0].options.gender,'female');assert.match(b.elements.output.textContent,/—:— \/ —:—/);b.p.setRate(1.5);assert.equal(b.spoken.length,2);assert.equal(b.spoken[1].options.rate,1.5);b.finishSpeech({});await Promise.resolve();b.gap();assert.equal(b.spoken[2].options.gender,'male');b.finishSpeech({});await Promise.resolve();const blank=[...b.timers.values()].find(v=>Math.abs(v.ms-800)<.01);assert.ok(blank,'1.2 second answer blank scales with speed');blank.fn();assert.equal((await done).error,undefined);assert.equal(b.spoken.length,3)});
test('device speech failure stays failure without recording a completed hearing',async()=>{const b=boot(),done=b.p.play({key:'q',script:'말',forceDevice:true});b.finishSpeech({error:true});assert.equal((await done).error,true)});
test('catalog resolution carries exact text and voice-specific paths without changing the MP3 inventory',()=>{const c={};c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync('listening-audio.js','utf8'),c);const corpus=JSON.parse(fs.readFileSync('audio/listening/v1/corpus.json'));for(const q of corpus.coverage){const resolved=c.HARUMAL_LISTENING_AUDIO.resolve(q.script);assert.ok(resolved?.length);for(const part of resolved)if(part.url){assert.ok(fs.existsSync(part.url),part.url);assert.ok(part.text);assert.match(part.url,part.gender==='female'?/\/F1\//:/\/M1\//)}}});

test('seeking straight to end cannot count as a completed hearing',async()=>{const b=boot(),done=b.p.play({key:'q'});b.p.seek(4.38);const result=await done;assert.equal(result.cancelled,false);assert.equal(result.heard,false)});
test('full playback records hearing but stop never does',async()=>{const b=boot(),done=b.p.play({key:'q'});b.audio[0].onended();b.gap();b.audio[1].onended();assert.equal((await done).heard,true);const stopped=b.p.play({key:'q'});b.p.cancel();assert.equal((await stopped).heard,false)});
test('exam cancellation before actual start explains a reusable attempt',async()=>{const b=boot({start:false});b.root.dataset.playerOnce='1';const done=b.p.play({key:'q',once:true});b.p.cancel();assert.equal((await done).started,false);assert.equal(b.elements['.listeningToggle'].disabled,false);assert.doesNotMatch(b.elements['.listeningMessage'].textContent,/이미 시작한/)});
