const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),crypto=require('node:crypto');
const spec=JSON.parse(fs.readFileSync('audio/listening/v1/corpus.json','utf8'));
const script=id=>spec.coverage.find(x=>x.id===id).script;
function boot(mode='auto'){
 const audio=[],urls=[],timers=new Map();let clock=0,cancelDevice=0;
 function FakeAudio(){audio.push(this);this.duration=1;this.play=()=>{urls.push(this.src);if(mode==='reject')return Promise.reject(Error('blocked'));this.onplaying?.();if(mode==='auto')queueMicrotask(()=>this.onended?.());return Promise.resolve()};this.pause=()=>{this.paused=true};this.load=()=>{};this.removeAttribute=()=>{};}
 const c={console,Audio:FakeAudio,document:{getElementById:()=>null},setTimeout(fn,ms){const id=++clock;timers.set(id,{fn,ms});if(mode==='auto'&&ms<=1200)queueMicrotask(()=>{if(timers.has(id)){timers.delete(id);fn()}});return id},clearTimeout(id){timers.delete(id)}};c.window=c;c.MALBIT_TTS={cancel(){cancelDevice++;c.HARUMAL_LISTENING_AUDIO?.cancel()}};vm.createContext(c);vm.runInContext(fs.readFileSync('listening-audio.js','utf8'),c);return{c,audio,urls,timers,cancelDevice:()=>cancelDevice}}
test('all 1050 listening questions map to exact scripts and no vocabulary-only playback is registered',()=>{const{c}=boot(),api=c.HARUMAL_LISTENING_AUDIO;assert.equal(api.questionCount,1050);assert.equal(api.scriptCount,843);assert.equal(api.textCount,360);assert.equal(api.clipCount,363);assert.equal(spec.coverage.length,1050);for(const q of spec.coverage)assert.ok(api.has(q.script),q.id);assert.equal(api.has('학교'),false);assert.equal(api.has('__proto__'),false);assert.equal(api.has(script('legacy-II-1')+' 다른 문장'),false)});
test('role-labelled dialogue uses actual separate female and male files in order',async()=>{const{c,urls,audio}=boot();const result=await c.HARUMAL_LISTENING_AUDIO.play(script('legacy-II-1'),{rate:.9});assert.equal(result.error,undefined);assert.equal(result.playedSegments,2);assert.match(urls[0],/\/F1\//);assert.match(urls[1],/\/M1\//);assert.equal(audio.length,1);assert.equal(audio[0].preservesPitch,true);assert.equal(audio[0].playbackRate,.9)});
test('response blanks are silence and never disclose the correct answer',async()=>{const{c,urls}=boot();const seq=c.HARUMAL_LISTENING_AUDIO.lookup(script('P01-I-L-01'));assert.equal(seq.length,2);assert.equal(seq[1].pause,1200);const result=await c.HARUMAL_LISTENING_AUDIO.play(script('P01-I-L-01'));assert.equal(result.playedSegments,1);assert.equal(urls.length,1);assert.ok(spec.corpus.every(x=>!/^_+$/.test(x.text)))});
test('new playback cancels and settles the old player and stale callbacks cannot advance it',async()=>{const{c,audio,urls}=boot('manual');const old=c.HARUMAL_LISTENING_AUDIO.play(script('legacy-II-1'));const stale=audio[0].onended;const newer=c.HARUMAL_LISTENING_AUDIO.play(script('legacy-I-1'));stale();assert.equal((await old).cancelled,true);assert.equal(audio[0].paused,true);assert.equal(urls.length,2);c.HARUMAL_LISTENING_AUDIO.cancel();assert.equal((await newer).cancelled,true)});
test('failure returns only the remaining dialogue for explicit device fallback',async()=>{const{c,audio,timers}=boot('manual');const pending=c.HARUMAL_LISTENING_AUDIO.play(script('legacy-II-1'));audio[0].onended();const gap=[...timers.values()].find(x=>x.ms===380);gap.fn();audio[0].onerror();const result=await pending;assert.equal(result.error,true);assert.equal(result.playedSegments,1);assert.match(result.remainingScript,/^남자:/);assert.doesNotMatch(result.remainingScript,/이 상자 안에는/)});
test('missing files, rejected playback and unavailable scripts fail without hanging',async()=>{const{c,urls}=boot('reject');assert.equal((await c.HARUMAL_LISTENING_AUDIO.play('등록되지 않은 대본')).unavailable,true);assert.equal(urls.length,0);const result=await c.HARUMAL_LISTENING_AUDIO.play(script('legacy-I-1'));assert.equal(result.error,true);assert.equal(result.playedSegments,0)});
test('all listening owners use the recorded script before legacy device fallback',()=>{for(const file of ['topik1.js','legacy-core.js','growth-learning.js'])assert.match(fs.readFileSync(file,'utf8'),/HARUMAL_LISTENING_PLAYER/);const worker=fs.readFileSync('sw.js','utf8');assert.match(worker,/url.pathname.includes\('\/audio\/listening\/'\)/);assert.doesNotMatch(fs.readFileSync('tts-quality.js','utf8'),/MALBIT_NEURAL_TTS/)});
test('full source inventory still matches the generated script manifest',()=>{const c={};c.window=c;vm.createContext(c);for(const file of ['data/topik1-listening.js','legacy-data.js','data/growth-learning.js','data/question-bank-v1-part1.js','data/question-bank-v1-part2.js','data/question-bank-v1-part3.js','data/question-bank-v1-part4.js','data/question-bank-practice-v1.js'])vm.runInContext(fs.readFileSync(file,'utf8'),c);const current=[...c.MALBIT_QUESTION_BANK_PARTS.flat().filter(x=>x[3]==='l').map(x=>({id:x[0],script:x[9]})),...c.TOPIK1_LISTENING_DATA.map(x=>({id:'legacy-I-'+x.id,script:x.script})),...vm.runInContext('LS',c).map(x=>({id:'legacy-II-'+x.id,script:x.script})),...c.MALBIT_QUESTION_BANK_EXPANSION.filter(x=>x.section==='listening'),...c.HARUMAL_GROWTH_DATA.recipes.flatMap(r=>[r.learn,r.transfer]).filter(x=>x.kind==='listen').map(x=>({id:x.id,script:x.audio}))];const{c:runtime}=boot();assert.equal(current.length,1050);for(const q of current){const entry=spec.coverage.find(x=>x.id===q.id);assert.ok(entry,q.id);assert.equal(entry.script,runtime.HARUMAL_LISTENING_AUDIO.normalize(q.script))}});

test('every source segment is covered by a verified, exact-hash MP3 and no obsolete clips remain',()=>{
 const manifest=JSON.parse(fs.readFileSync('audio/listening/v1/manifest.json','utf8'));assert.equal(manifest.questionCount,1050);assert.equal(manifest.scriptCount,843);assert.equal(manifest.textCount,360);assert.equal(manifest.fileCount,363);assert.equal(manifest.decodeVerified,true);assert.equal(manifest.humanPronunciationReview,false);assert.equal(manifest.physicalIOSPlaybackVerified,false);assert.ok(manifest.totalBytes<50*1024*1024);assert.equal(new Set(manifest.files.map(x=>x.sha256)).size,363);let sum=0,count=0;
 for(const row of spec.corpus){assert.equal(crypto.createHash('sha256').update(row.text).digest('hex').slice(0,16),row.id);for(const voice of row.voices){const file=`audio/listening/v1/${voice}/${row.id}.mp3`,data=fs.readFileSync(file),entry=manifest.files.find(x=>x.file===file);assert.ok(entry,file);assert.equal(entry.bytes,data.length);assert.equal(entry.sha256,crypto.createHash('sha256').update(data).digest('hex'));assert.ok(entry.duration>.2&&entry.peak<1&&entry.rms>.001);sum+=data.length;count++}}assert.equal(count,363);assert.equal(sum,manifest.totalBytes);assert.equal(['F1','M1'].reduce((n,v)=>n+fs.readdirSync(`audio/listening/v1/${v}`).filter(x=>x.endsWith('.mp3')).length,0),363);
});
