const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8'),plain=value=>JSON.parse(JSON.stringify(value));
function boot(values=new Map()){
 const node={innerHTML:'',className:'',style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},appendChild(){},querySelector:()=>null,querySelectorAll:()=>[]};
 const c={console,Date,Math,S:{lang:'en',view:'home',vocab:[]},localStorage:{get length(){return values.size},key:i=>[...values.keys()][i]??null,getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,String(v)),removeItem:k=>values.delete(k)},document:{head:node,body:node,documentElement:node,createElement:()=>({...node}),getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[],addEventListener(){}},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},render(){},renderShell(){},scrollTo(){},addEventListener(){},hideSelection(){},navActive(){},setProgress(){},stopTimer(){},stopAudio(){},stopListeningAudio(){},toast(){},save(){values.set('topikQuestV8',JSON.stringify(c.S))}};
 c.window=c;c.setView=c.open=v=>{c.S.view=v};vm.createContext(c);vm.runInContext(read('learning-rewards.js'),c);return{c,values,node,run:src=>vm.runInContext(src,c),load:file=>vm.runInContext(read(file),c,{filename:file}),xp:()=>c.HARUMAL_REWARDS.getState().xp};
}
function part(file,start,end){const text=read(file),at=text.indexOf(start);assert.ok(at>=0,start);const finish=end?text.indexOf(end,at+start.length):text.length;assert.ok(finish>at,end);return text.slice(at,finish)}
function line(file,start){return read(file).split('\n').find(row=>row.startsWith(start))}
function topik(env){
 const {c,run}=env;Object.assign(c,{Q:null,SESSION:'topikQuestTopik1Session',restore:()=>c.Q,cur:()=>c.questions[c.Q.ids[c.Q.i]],find:id=>c.questions[id],nextPracticeQuestion:()=>Object.keys(c.questions)[0],questions:{a:{id:'a',section:'reading',difficulty:'easy',answerIndex:1},b:{id:'b',section:'listening',difficulty:'hard',answerIndex:2}}});
 run(line('topik1.js','function saveQ()'));run(part('topik1.js','function rewardQuestion(','function clearQ('));run(part('topik1.js','window.t1Next=()=>{','function result('));run(part('topik1.js','function result(){','function game1BossSkillDelay('));
 c.fresh=(mode='random')=>c.Q={mode,examLevel:1,rewardSessionId:c.HARUMAL_REWARDS.newSession(mode),ids:mode==='real'?['a','b']:['a'],answers:{},played:{},i:0,total:0,score:0,streak:0,locked:false};
}
test('TOPIK I actual practice submission grants once, survives reload and starts a new reward session',()=>{
 const e=boot();topik(e);const {c}=e;c.fresh();c.Q.answers.a=0;c.t1Next();assert.equal(e.xp(),0);assert.equal(c.Q.total,1);
 c.t1Next();c.Q.answers.a=1;c.t1Next();assert.equal(e.xp(),10);c.render();assert.equal(e.xp(),10);
 const saved=plain(c.Q),second=boot(e.values);topik(second);second.c.Q=saved;second.c.t1Next();assert.equal(second.xp(),10,'a next tap advances rather than re-grading the locked answer');
 second.c.fresh();second.c.Q.answers.a=1;second.c.t1Next();assert.equal(second.xp(),20);assert.equal(second.c.Q.total,1);
});
test('TOPIK I reading/listening exam pays only at final submission and never for reopening old results',()=>{
 const e=boot();topik(e);const {c}=e;c.fresh('real');c.Q.answers.a=1;c.t1Next();assert.equal(e.xp(),0);c.Q.answers.b=2;c.t1Next();assert.equal(e.xp(),35);assert.equal(c.Q.result.lc,1);assert.equal(c.Q.result.rc,1);c.finish();assert.equal(e.xp(),35);
 const old=boot();topik(old);old.c.Q={mode:'real',ids:['a'],answers:{a:1},result:{rc:1}};old.c.finish();assert.equal(old.xp(),0,'historical completed attempt is not retroactively awarded');
});
test('Shorts actual checks are idempotent across refresh; a newly started practice earns again',()=>{
 const e=boot();const {c,run}=e;let p={index:0,total:0,score:0};Object.assign(c,{SH:{activeLevel:1,daily:{}},level:()=>1,shortState:()=>p,shortsOptions:()=>({correct:1,target:{id:'short',difficulty:'medium'}}),randomShortsIndex:()=>0,prepareShortsCard(){},saveShorts(){e.values.set('shorts',JSON.stringify(p))},dayKey:()=> '2026-10-08'});
 run(part('topik1.js','window.startShorts=()=>{','function bindShortsSwipe('));c.startShorts();p.selected=0;c.checkShorts();assert.equal(e.xp(),0);c.nextShorts();p.selected=1;c.checkShorts();assert.equal(e.xp(),15);c.checkShorts();p=JSON.parse(e.values.get('shorts'));c.checkShorts();assert.equal(e.xp(),15);c.startShorts();p.selected=1;c.checkShorts();assert.equal(e.xp(),30);assert.equal(p.total,3);
});
function legacy(env){const {c,run}=env;Object.assign(c,{LS:Array.from({length:50},(_,i)=>({id:i+1,answerIndex:1,difficulty:'hard'})),RW:Array.from({length:54},(_,i)=>({id:i+1,answerIndex:2,difficulty:'very_hard'})),activateTopik2BankSet(){},writingEstimate:()=>0,rememberWriting(){},showSectionResult(){},showResultCeremony(){},elapsed:()=>4,infLimit:()=>30,ml:x=>x,selected:null});
 for(const start of ['function rewardLegacyAnswer(','function beginReal(','function realSaveChoice(','function finishReal(','function startRandomPractice(','function submitInfinity(','function submitInfinityWriting('])run(line('legacy-core.js',start));c.nextInfinity=()=>{c.S.infinity.current={type:'read',id:1};c.S.infinity.feedback=null};c.infinityCurrentQuestion=()=>c.RW[0];}
test('TOPIK II random answers and all mock sections respect final-submit and duplicate guards',()=>{
 const e=boot();legacy(e);const {c}=e;c.startRandomPractice(2);c.selected=0;c.submitInfinity();assert.equal(e.xp(),0);c.submitInfinity();assert.equal(c.S.infinity.count,1);c.nextInfinity();c.selected=2;c.submitInfinity();assert.equal(e.xp(),40);c.submitInfinity();assert.equal(e.xp(),40);c.startRandomPractice(2);c.selected=2;c.submitInfinity();assert.equal(e.xp(),80);
 c.beginReal('full');c.realSaveChoice(1);assert.equal(e.xp(),80);c.S.real.phase='read';c.realSaveChoice(2);assert.equal(e.xp(),80);c.finishReal();assert.equal(e.xp(),145);c.finishReal();assert.equal(e.xp(),145);assert.equal(c.S.lastResult.l,2);assert.equal(c.S.lastResult.r,2);
});
test('expedition battle uses question difficulty, preserves its run currencies and never rewards a timeout',()=>{
 const e=boot();topik(e);const{c,run}=e;Object.assign(c,{game1Effects:()=>({}),game1ActiveMonsterName:()=> 'Wolf',game1SyncRun(){}});run(part('topik1.js','function game1GradeAnswer(','function game1AdvanceAnswer('));
 c.fresh('game');Object.assign(c.Q,{node:'battle',enemyHp:2,enemyMax:2,focus:3,maxFocus:3,gold:12,essence:4,hiddenChoices:[0]});c.Q.answers.a=1;c.game1GradeAnswer();assert.equal(e.xp(),10);assert.equal(c.Q.gold,12);assert.equal(c.Q.essence,4);assert.equal(c.HARUMAL_REWARDS.getState().events[0].assisted,true);c.game1GradeAnswer();assert.equal(e.xp(),10);c.Q.locked=false;c.game1GradeAnswer(true);assert.equal(e.xp(),10);
});
test('vocabulary final submission preserves flashcards and does not regrant restored results',()=>{
 const e=boot();e.c.S.vocab=[{text:'학교',meanings:{en:'school'},dueAt:123},{text:'물',meanings:{en:'water'},interval:4}];e.c.document.getElementById=()=>e.node;e.load('vocab-test.js');const{c}=e,original=JSON.stringify(c.S.vocab);c.harumalVocabTestStart();c.harumalVocabTestDraft(c.S.vocabExam.items[0].term);c.harumalVocabTestSubmit();assert.equal(e.xp(),0);c.harumalVocabTestDraft('오답');c.harumalVocabTestSubmit();assert.equal(e.xp(),15);c.harumalVocabTestSubmit();assert.equal(e.xp(),15);
 const next=boot(e.values);next.c.S=plain(c.S);next.c.document.getElementById=()=>next.node;next.load('vocab-test.js');next.c.harumalVocabTestResume();next.c.harumalVocabTestSubmit();assert.equal(next.xp(),15);next.c.harumalVocabTestStart();next.c.harumalVocabTestDraft(next.c.S.vocabExam.items[0].term);next.c.harumalVocabTestSubmit();next.c.harumalVocabTestDraft('wrong');next.c.harumalVocabTestSubmit();assert.equal(next.xp(),30);assert.equal(JSON.stringify(next.c.S.vocab),original);
});
test('grammar drill grants only verified accepted answers; explicit fresh practice earns while reopening does not',()=>{
 const e=boot();e.values.set('malbitBeginnerV1',JSON.stringify({known:['v:ㅏ'],legacyReadingProgress:['r1']}));e.load('data/beginner-grammar-v1.js');e.load('beginner-grammar.js');const{c}=e,id=c.MALBIT_BEGINNER_GRAMMAR_V1.lessons[0].id,answer=c.MALBIT_BEGINNER_GRAMMAR_V1.lessons[0].drill.accepted[0];c.malbitGrammarLesson(id);c.malbitGrammarDraft('wrong');assert.equal(c.malbitGrammarSubmit(),false);assert.equal(e.xp(),0);c.malbitGrammarDraft(answer);assert.equal(c.malbitGrammarSubmit(),true);assert.equal(e.xp(),10);c.malbitGrammarSubmit();c.malbitGrammarLesson(id);c.malbitGrammarDraft(answer);c.malbitGrammarSubmit();assert.equal(e.xp(),10);
 const next=boot(e.values);next.load('data/beginner-grammar-v1.js');next.load('beginner-grammar.js');next.c.malbitGrammarLesson(id);next.c.malbitGrammarDraft(answer);next.c.malbitGrammarSubmit();assert.equal(next.xp(),10);next.c.malbitGrammarRetry();next.c.malbitGrammarDraft(answer);next.c.malbitGrammarSubmit();assert.equal(next.xp(),20);const saved=JSON.parse(e.values.get('malbitBeginnerV1'));assert.deepEqual(saved.known,['v:ㅏ']);assert.deepEqual(saved.legacyReadingProgress,['r1']);
});
test('review retry episode keeps stable reward identity across closing/reopening and refresh',()=>{
 const e=boot();const{c,run}=e;Object.assign(c,{REVIEW_KEY:'review',REVIEW:{items:{k:{key:'k',level:2,id:1,type:'read',active:true,wrongCount:1,retryCount:0}}},reviewAttempt:null,reviewQuestion:()=>({id:1,answerIndex:1,difficulty:'hard'}),renderReviewRetry(){},saveReview(){e.values.set('review',JSON.stringify(c.REVIEW))}});run(part('learning-features.js','function resolveReview(','function scanLatestExamWrongAnswers('));run(part('learning-features.js','function reviewRewardSession(','function renderReviewRetry('));run(part('learning-features.js','function toggleReviewTranslation(','function clearMasteredReview('));c.openReviewRetry('k');c.toggleReviewTranslation();c.toggleReviewTranslation();assert.equal(c.REVIEW.items.k.rewardAttempt.assisted,true);c.openReviewRetry('k');c.reviewSelect(0);c.reviewSelect(0);assert.equal(e.xp(),0);c.openReviewRetry('k');c.reviewSelect(1);c.reviewSelect(1);assert.equal(e.xp(),25);c.REVIEW=JSON.parse(e.values.get('review'));c.openReviewRetry('k');c.reviewSelect(1);c.reviewSelect(1);assert.equal(e.xp(),25);assert.equal(c.REVIEW.items.k.active,false);assert.equal(c.HARUMAL_REWARDS.getState().events[0].assisted,true);
});
test('travel dialogue quiz preserves the route and adventure self-ratings never mint correctness rewards',()=>{
 const e=boot();const{c}=e;c.document.getElementById=()=>e.node;e.load('data/travel-pack-seoul-001.js');c.MALBIT_TRAVEL={packs:c.MALBIT_TRAVEL_PACKS};e.load('data/travel-adventure-seoul-v1.js');e.load('travel-adventure.js');e.values.set('malbitStoryV1',JSON.stringify({version:1,episodes:{old:{wallet:800,inventory:['ticket']}},avatar:'blue'}));c.harumalAdventureStart(1);for(let i=0;i<3;i++)c.harumalAdventureNextLine();const q=c.HARUMAL_ADVENTURE_DATA.levels[1][0];c.harumalAdventureChoose((q.answer+1)%4);c.harumalAdventureSubmit();assert.equal(e.xp(),0);c.harumalAdventureRetry();c.harumalAdventureChoose(q.answer);c.harumalAdventureSubmit();assert.equal(e.xp(),15);c.harumalAdventureSubmit();c.harumalAdventureStart(1);c.harumalAdventureSubmit();assert.equal(e.xp(),15);c.harumalAdventureReview(1);c.harumalAdventurePickReview(q.id);c.harumalAdventureReveal();c.harumalAdventureRate(true);assert.equal(e.xp(),15);const saved=JSON.parse(e.values.get('malbitStoryV1'));assert.deepEqual(saved.episodes.old,{wallet:800,inventory:['ticket']});assert.equal(saved.avatar,'blue');
});
test('writing rewards bounded choice correctness only, never unreviewed free/form text or historical duplicates',()=>{
 const e=boot();const{c,run}=e;e.load('data/writing-curriculum.js');e.load('writing-curriculum-engine.js');c.E=c.HARUMAL_WRITING_ENGINE.create(c.localStorage,c.HARUMAL_WRITING_DATA);Object.assign(c,{item:id=>c.E.itemById(id),navigate(){},updateActionLayout(){},T:x=>x});run(line('writing-curriculum.js','window.harumalWritingSubmit='));
 const relation=c.HARUMAL_WRITING_DATA.items.find(i=>i.kind==='relation'),free=c.HARUMAL_WRITING_DATA.items.find(i=>i.kind!=='relation'&&i.models?.length);c.E.setDraft(relation.id,'wrong');c.harumalWritingSubmit(relation.id);assert.equal(e.xp(),0);c.E.setDraft(relation.id,relation.evaluation.correctChoiceId);c.harumalWritingSubmit(relation.id);assert.equal(e.xp(),10);c.harumalWritingSubmit(relation.id);assert.equal(e.xp(),10);c.E.setDraft(free.id,free.models[0]);c.harumalWritingSubmit(free.id);assert.equal(e.xp(),10);assert.ok(c.E.getState().attempts.length>=3);
});

test('legacy travel correct retry earns once with assistance without changing first-try wallet/scoring',()=>{
 const e=boot();const{c,run}=e;const pack={id:'route',startWallet:100,scenes:[{id:'q'}]},scene={id:'q',type:'question',dialogueLesson:{},reward:20},q={id:'q',bankId:'travel-test',answerIndex:1,choiceOrder:[0,1,2,3],difficulty:'hard',section:'reading'};let state;Object.assign(c,{RPG:null,now:()=>new Date().toISOString(),normalizeMeasurement:()=>({}),normalizeHubState:()=>({}),correctCount:()=>0,SELECTED:{},notify(){},l:x=>x.en,normalizeDialogueState:x=>({...x,attempts:x?.attempts||0,firstWrong:x?.firstWrong??null}),current:()=>({pack,state,scene}),ensureQuestion:()=>({display:q,source:{level:2}}),writeState:s=>e.values.set('travel-session',JSON.stringify(s)),revealFeedback(){}});run(part('travel-mode.js','  function newState(','  function current('));run(part('travel-mode.js','  window.malbitTravelSubmit=()=>{','  window.malbitTravelToggleTranscript='));state=c.newState(pack);const original=state.rewardSessionId;c.SELECTED.q=0;c.malbitTravelSubmit();assert.equal(e.xp(),0);assert.equal(state.dialogues.q.attempts,1);state=JSON.parse(e.values.get('travel-session'));assert.equal(state.rewardSessionId,original);c.SELECTED.q=1;c.malbitTravelSubmit();assert.equal(e.xp(),25);assert.equal(state.answers.q.correct,false);assert.equal(state.wallet,100);assert.equal(c.HARUMAL_REWARDS.getState().events[0].assisted,true);c.malbitTravelSubmit();state=JSON.parse(e.values.get('travel-session'));c.malbitTravelSubmit();assert.equal(e.xp(),25);state=c.newState(pack,state);assert.notEqual(state.rewardSessionId,original);c.SELECTED.q=1;c.malbitTravelSubmit();assert.equal(e.xp(),50);assert.equal(state.wallet,120);
});

test('two stale review tabs share a deterministic wrong-answer episode and mint one reward',()=>{
 const values=new Map(),a=boot(values),b=boot(values);
 for(const e of [a,b]){const{c,run}=e;Object.assign(c,{REVIEW_KEY:'review',REVIEW:{items:{k:{key:'k',level:2,id:1,type:'read',lastWrongAt:172800000,active:true,wrongCount:2,retryCount:0}}},reviewAttempt:null,reviewQuestion:()=>({id:1,answerIndex:1,difficulty:'hard'}),renderReviewRetry(){},saveReview(){values.set('review',JSON.stringify(c.REVIEW))}});run(part('learning-features.js','function resolveReview(','function scanLatestExamWrongAnswers('));run(part('learning-features.js','function reviewRewardSession(','function renderReviewRetry('));run(part('learning-features.js','function reviewSelect(','function clearMasteredReview('));c.openReviewRetry('k')}
 for(const e of [a,b]){e.c.reviewSelect(1);e.c.reviewSelect(1)}assert.equal(a.xp(),25);assert.equal(b.xp(),25);assert.equal(a.c.REVIEW.items.k.rewardAttempt.sessionId,b.c.REVIEW.items.k.rewardAttempt.sessionId);
});
test('pre-reward TOPIK sessions use the same migration identity in two stale tabs',()=>{
 const values=new Map(),a=boot(values),b=boot(values);for(const e of [a,b]){topik(e);e.c.Q={mode:'random',examLevel:1,ids:['a'],i:0,total:3,score:1,streak:0,answers:{a:1},played:{},locked:false};e.c.t1Next()}assert.equal(a.xp(),10);assert.equal(b.xp(),10);
 const x=boot(values),y=boot(values);for(const e of [x,y]){legacy(e);e.c.S.infinity={active:true,examLevel:2,count:3,graded:3,correct:1,totalSec:10,targetSec:50,current:{type:'read',id:1},feedback:null};e.c.selected=2;e.c.submitInfinity()}assert.equal(x.xp(),50);assert.equal(y.xp(),50);
});

test('travel constrained minigames reward only new exact targets and preserve old completed quests',()=>{
 const e=boot();const{c,run}=e,pack={id:'route'},price={id:'price',interaction:'price-budget',targetItem:'tea',targetQuantity:2,budget:100,menu:[{id:'tea',price:10}]},order={id:'order',tokens:['학교','가요'],answer:['학교','가요'],reward:5},hub={events:{price,order}};let state={packId:'route',startedAt:'old',wallet:100,clockMinutes:0,evidence:[],inventory:[],myeongdong:{screen:'order',activeEvent:'price',quests:{},attempts:0}};Object.assign(c,{now:()=>new Date().toISOString(),HUB_BUDGET:{price:1},HUB_ORDER:{order:[1,0]},HUB_COMPOSE_RESULT:{},current:()=>({pack,state}),hubByRoute:()=>hub,activeHubEvent:()=>price,hubQuestDone:(s,id)=>!!s.myeongdong.quests[id]?.completed,writeState:s=>e.values.set('travel-mini',JSON.stringify(s)),render(){},revealFeedback(){},resetViewport(){},notify(){},l:x=>x.en});run(part('travel-mode.js','  function rewardTravelAnswer(','  function current('));run(part('travel-mode.js','  function submitHubBudget(){','  window.malbitTravelBudgetChange='));run(part('travel-mode.js','  window.malbitTravelOrderSubmit=()=>{','  window.malbitTravelBuy='));
 c.submitHubBudget();assert.equal(e.xp(),0);c.HUB_BUDGET.price=2;c.submitHubBudget();assert.equal(e.xp(),10);assert.equal(state.wallet,80);state.myeongdong.screen='order';c.submitHubBudget();assert.equal(e.xp(),10);assert.equal(state.wallet,80);state.myeongdong.screen='order';state.myeongdong.activeEvent='order';c.malbitTravelOrderSubmit();assert.equal(e.xp(),10);c.HUB_ORDER.order=[0,1];c.malbitTravelOrderSubmit();assert.equal(e.xp(),25);assert.equal(state.wallet,85);assert.ok(c.HARUMAL_REWARDS.getState().events.every(x=>x.assisted));state.myeongdong.screen='order';c.HUB_ORDER.order=[0,1];c.malbitTravelOrderSubmit();assert.equal(e.xp(),25);
});
