const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),cycle=require('../shorts-cycle.js');
function data(){const c={console,localStorage:{getItem:()=>null,setItem(){}}};c.window=c;vm.createContext(c);for(const file of ['data/shorts-levels.js',...Array.from({length:4},(_,i)=>`data/question-bank-v1-part${i+1}.js`),'data/question-bank-practice-v1.js','data/explanations-i18n.js','question-bank-engine.js'])vm.runInContext(fs.readFileSync(file,'utf8'),c);return c;}
test('every retired grammar or reading card migrates without losing earned records',()=>{const c=data();let count=0;for(const lv of [1,2]){const allowed=c.MALBIT_SHORTS_DECKS[lv].filter(q=>['word','expression','idiom'].includes(q.type)),deck=[...allowed,...c.MALBIT_BANK.shorts(lv)],retired=c.MALBIT_SHORTS_DECKS[lv].filter(q=>!['word','expression','idiom'].includes(q.type));for(const id of lv===1?['M01-I-R-44']:['P01-II-R-06']){const q=c.MALBIT_BANK.present(id);assert.ok(q);retired.push({bankId:id,type:'word',term:[q.passage,q.prompt].filter(Boolean).join('\n'),choices:q.choices});}for(const q of retired){const old=cycle.identity(q,lv),state={index:0,cardId:old.id,orderId:old.id,selected:2,locked:true,choiceOrder:[2,0,1,3],total:24,score:20,streak:4,recentIds:[old.id],recentFamilies:[old.family],cycleFamilies:[old.family]};assert.equal(deck.some(x=>cycle.identity(x,lv).id===old.id),false);cycle.migrate(state,deck,lv);assert.equal(state.selected,null);assert.equal(state.locked,false);assert.equal(state.choiceOrder,null);assert.deepEqual([state.total,state.score,state.streak],[24,20,4]);assert.ok(!state.recentIds.includes(old.id));assert.ok(!state.recentFamilies.includes(old.family));assert.ok(!state.cycleFamilies.includes(old.family));assert.ok(deck.some(x=>cycle.identity(x,lv).id===state.cardId));count++;}}assert.equal(count,105);});
test('browser fixtures use the runtime vocabulary deck while retaining reading and archived grammar coverage',()=>{const source=fs.readFileSync('scripts/check-travel-mobile.mjs','utf8');assert.doesNotMatch(source,/\[\.\.\.window\.MALBIT_SHORTS_DECKS/);assert.match(source,/HARUMAL_SHORTS_DECK\(lv\)/);assert.match(source,/bankId:'P01-II-R-06'/);assert.match(source,/q\.ids=\['M01-I-R-44'\]/);assert.match(source,/verifyRetiredShorts\(\{evaluate,send,ready,shot\}\)/);const contentTests=fs.readFileSync('tests/vocabulary-library.test.cjs','utf8');for(const id of ['S04-II-G-CAUSE','S04-II-G-INFER','S04-I-G-NEGATION','S04-I-G-TENSE','S04-I-G-PARTICLE'])assert.ok(contentTests.includes(id));});

test('runtime persists retired-card migration once while retaining other learner records',()=>{
 const source=fs.readFileSync('topik1.js','utf8'),start=source.indexOf('function shortState('),end=source.indexOf('\nfunction saveShorts',start),other={total:9,score:8},daily={'2026-01-01':{total:7,score:4}};let writes=0,saved;
 const state={activeLevel:1,levels:{1:{index:0,cardId:'RETIRED',orderId:'RETIRED',selected:2,locked:true,choiceOrder:[2,0,1,3],total:24,score:20,streak:4,recentIds:['RETIRED'],recentFamilies:[],cycleFamilies:[]},2:other},daily};
 const c={SH:state,level:()=>1,shortsDeck:()=>[{type:'word',term:'가게'}],blankShorts:()=>({index:0,selected:null,locked:false,total:0,score:0,streak:0}),SHORTS_CYCLE:cycle,saveShorts(){writes++;saved=JSON.parse(JSON.stringify(state))}};vm.createContext(c);vm.runInContext(source.slice(start,end),c);c.shortState(1);assert.equal(writes,1);assert.equal(saved.levels[1].cardId,'SHORT-1-word-가게');assert.equal(saved.levels[1].selected,null);assert.equal(saved.levels[1].locked,false);assert.equal(saved.levels[1].choiceOrder,null);assert.deepEqual([saved.levels[1].total,saved.levels[1].score,saved.levels[1].streak],[24,20,4]);assert.deepEqual(saved.levels[2],other);assert.deepEqual(saved.daily,daily);c.shortState(1);assert.equal(writes,1,'stable rendering must not keep rewriting storage');
});

test('browser bank fixture uses inline coaching while active fast-review vocabulary retains details coverage',()=>{const c=data();assert.equal(!!c.MALBIT_BANK.byId('P01-II-R-07').coach?.shortsFastReview,false);const card=c.MALBIT_SHORTS_DECKS[1].find(q=>q.id==='S04-I-W-TIME-01');assert.equal(card.type,'word');assert.equal(card.shortsFastReview,true);const source=fs.readFileSync('scripts/check-travel-mobile.mjs','utf8');assert.match(source,/unflagged vocabulary bank card renders its complete coaching inline/);assert.match(source,/assert.equal\(timeReview.closed,true\)/);});
