const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('vocabulary-translation.js','utf8');
function runtime(fetch=async()=>{throw Error('Network should not be used')}){const c={S:{transCache:{}},save(){},fetch,console,URL,AbortController,setTimeout,clearTimeout};c.window=c;vm.createContext(c);vm.runInContext(source,c);return c}
test('authored meanings bypass machine service in all supported target languages',async()=>{const c=runtime();c.MALBIT_SHORTS_DECKS={1:[{term:'발이 넓다',meaning:{ja:'顔が広い',en:'to know many people',zh:'人脉广'}}]};for(const lang of ['ja','en','zh']){const result=await c.MALBIT_VOCAB_TRANSLATION.resolve({text:'발이 넓다'},lang);assert.equal(result.source,'authored');assert.equal(result.value,c.MALBIT_SHORTS_DECKS[1][0].meaning[lang])}});
test('homographs require matching example instead of taking first dictionary row',()=>{const c=runtime();c.MALBIT_SHORTS_DECKS={1:[{term:'배',example:'배를 먹어요.',meaning:{en:'pear'}},{term:'배',example:'배를 타요.',meaning:{en:'boat'}}]};assert.equal(c.MALBIT_VOCAB_TRANSLATION.authored({text:'배'},'en'),null);assert.equal(c.MALBIT_VOCAB_TRANSLATION.authored({text:'배',example:'배를 타요.'},'en').meaning.en,'boat')});
test('provider errors, source echoes and transport errors are never cached',async()=>{for(const response of [{responseStatus:403,responseData:{translatedText:'MYMEMORY WARNING: YOU USED ALL AVAILABLE FREE TRANSLATIONS'}},{responseStatus:200,responseData:{translatedText:'학교'}},{responseStatus:200,quotaFinished:true,responseData:{translatedText:'school'}}]){const c=runtime(async()=>({ok:true,json:async()=>response}));await assert.rejects(c.MALBIT_VOCAB_TRANSLATION.machine('학교','en'));assert.equal(Object.keys(c.S.transCache).length,0)}});
function configure(c){c.MALBIT_TRANSLATION_CONFIG={enabled:true,endpoint:'https://translate.example/v1/vocabulary',verifyPublicEntry:()=>true,getTurnstileToken:async()=> 'test-token'}}
function cloudResult(term='학교',context=''){return{version:1,provider:'cloudflare',reviewRequired:true,result:{term,target:'en',kind:'word',meaning:'school',explanation:'A place where students learn.',senses:[],example:{ko:'학교에 가요.',translation:'I go to school.'},uncertain:false}}}
test('cloud cache is context sensitive and ignores old poisoned cache',async()=>{let calls=0;const c=runtime(async()=>({ok:true,json:async()=>{calls++;return cloudResult()}}));configure(c);c.S.transCache.ko_en_vocab_v20_en_학교='bad cached meaning';for(const context of ['학교에 가요.','학교에 가요.','학교를 지어요.'])await c.MALBIT_VOCAB_TRANSLATION.resolve({text:'학교',context},'en');assert.equal(calls,2);assert.equal(c.S.transCache.ko_en_vocab_v20_en_학교,'bad cached meaning')});
test('unconfigured entries never call an external service',async()=>{const c=runtime();await assert.rejects(c.MALBIT_VOCAB_TRANSLATION.resolve({text:'학교'},'en'),/not configured/)});
test('cloud request retains exact range and bounded context and stores draft details',async()=>{let sent;const c=runtime(async(url,opts)=>{sent=JSON.parse(opts.body);return{ok:true,json:async()=>cloudResult()}});configure(c);const entry={text:'학교',context:'학교에 가요.'};await c.MALBIT_VOCAB_TRANSLATION.reveal(entry,'en');assert.equal(sent.term,'학교');assert.equal(sent.context,entry.context);assert.equal(entry.meaningSources.en,'machine');assert.equal(entry.translationDetails.en.example.translation,'I go to school.')});
test('late cloud response cannot overwrite a word edited during translation',async()=>{let done;const c=runtime(async()=>({ok:true,json:()=>new Promise(r=>done=r)}));configure(c);const entry={text:'학교'},pending=c.MALBIT_VOCAB_TRANSLATION.reveal(entry,'en');await new Promise(r=>setTimeout(r,0));entry.text='고양이';done(cloudResult());await pending;assert.equal(entry.meanings.en,undefined)});
test('manual and legacy saved corrections remain unchanged',async()=>{const c=runtime();for(const entry of [{text:'학교',meanings:{en:'my special meaning'},manual:true},{text:'학교',meanings:{en:'my legacy meaning'}}]){const old=JSON.stringify(entry);await c.MALBIT_VOCAB_TRANSLATION.reveal(entry,'en');assert.equal(JSON.stringify(entry),old)}});
test('only confirmed legacy auto failures are recovered with old content retained',async()=>{const c=runtime();c.MALBIT_SHORTS_DECKS={1:[{term:'학교',meaning:{en:'school'}}]};c.S.transCache.ko_en_vocab_v20_en_학교='MYMEMORY WARNING: quota';const entry={text:'학교',meanings:{en:'MYMEMORY WARNING: quota'},dueAt:123};await c.MALBIT_VOCAB_TRANSLATION.reveal(entry,'en');assert.equal(entry.meanings.en,'school');assert.equal(entry.translationRecovery.en,'MYMEMORY WARNING: quota');assert.equal(entry.dueAt,123)});
test('token normalization preserves lexical suffixes and only strips known stems',()=>{const src=fs.readFileSync('learning-features.js','utf8');const code=src.slice(src.indexOf('const LEXICAL_WORDS='),src.indexOf('function removeUnsafeSavedFragments'));const c={window:{}};vm.createContext(c);vm.runInContext(code+';this.normalize=normalizeKoreanTerm',c);for(const term of ['고양이','호랑이','어린이','차이','제대로','스스로','지하도','미등록어이'])assert.equal(c.normalize(term),term);assert.equal(c.normalize('책을'),'책');assert.equal(c.normalize('고양이를'),'고양이')});
test('Japanese and Chinese targets reject Latin-only wrong-language output',()=>{const c=runtime(),valid=c.MALBIT_VOCAB_TRANSLATION.valid;assert.equal(valid('GYE','기에','ja'),false);assert.equal(valid('V - Stay + Good/Comfortable/Difficult Place/Method','V-기에 + 좋은/편한/어려운 장소·방법','ja'),false);assert.equal(valid('school','학교','zh'),false);assert.equal(valid('学校','학교','ja'),true)});
test('unreviewed grammar notation is not submitted as a normal dictionary word',async()=>{const c=runtime();await assert.rejects(c.MALBIT_VOCAB_TRANSLATION.resolve({text:'V-새로운문법 + N'},'ja'),/not configured/)});
test('an example from another sense is not replaced by a unique deck entry',()=>{const c=runtime();c.MALBIT_SHORTS_DECKS={1:[{term:'쓰다',example:'모자를 썼어요.',meaning:{en:'wear a hat'}}]};assert.equal(c.MALBIT_VOCAB_TRANSLATION.authored({text:'쓰다',context:'글을 써요.'},'en'),null)});
test('all seven screenshot grammar inputs resolve to authored explanations without a network call',async()=>{const c=runtime();vm.runInContext(fs.readFileSync('vocabulary-grammar.js','utf8'),c);for(const term of ['기만 하면','다가','기에','채로','셈이다,돈을 아낀 셈이다','V-기에 + 좋은/편한/어려운 장소·방법','A는커녕 B도'])for(const lang of ['ja','en','zh']){const result=await c.MALBIT_VOCAB_TRANSLATION.resolve({text:term},lang);assert.equal(result.source,'grammar');assert.ok(result.value.length>10);assert.ok(result.row.example);assert.doesNotMatch(result.value,/チェス|チェロ|^GYE$|^たが$/)}});
test('grammar explanations retain alternatives and do not pretend fragments have one meaning',()=>{const c=runtime();vm.runInContext(fs.readFileSync('vocabulary-grammar.js','utf8'),c);assert.match(c.MALBIT_VOCAB_GRAMMAR.lookup('기에').meaning.ja,/①.*②/);assert.match(c.MALBIT_VOCAB_GRAMMAR.lookup('셈이다').meaning.ja,/つもり/);assert.match(c.MALBIT_VOCAB_GRAMMAR.lookup('기만 하면').meaning.ja,/たびに/);assert.equal(c.MALBIT_VOCAB_GRAMMAR.lookup('새로운 기에 문장'),null)});
function selectionRuntime(){const c={window:null,document:{addEventListener(){}},setTimeout,clearTimeout};c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync('vocabulary-grammar.js','utf8'),c);vm.runInContext(fs.readFileSync('vocabulary-selection.js','utf8'),c);return c.MALBIT_VOCAB_SELECTION}
test('selection context stores the containing sentence, not unrelated paragraph contents',()=>{const api=selectionRuntime(),text='연락처는 비공개예요. 불을 켠 채로 잠이 들었어요. 다음 일정은 따로 있어요.',start=text.indexOf('채로');assert.equal(api.sentence(text,start,start+2),'불을 켠 채로 잠이 들었어요.');assert.equal(api.sentence('가'.repeat(900),400,402),'가가')});
test('range across inline markup preserves exact selected text and nearby sentence',()=>{const api=selectionRuntime(),paragraph={textContent:'불을 켠 채로 잠이 들었어요.'};const zone={contains:()=>true,textContent:paragraph.textContent};const element={nodeType:1,closest:selector=>selector==='input,textarea,[contenteditable="true"]'?null:selector.includes('.selectable')?zone:paragraph};const textNode={nodeType:3,parentElement:element};const range={startContainer:textNode,endContainer:textNode,startOffset:0,cloneRange:()=>({selectNodeContents(){},setEnd(){},toString:()=> '불을 켠 '})};const selection={isCollapsed:false,rangeCount:1,toString:()=> '채로',getRangeAt:()=>range};const result=api.capture(selection);assert.equal(result.term,'채로');assert.equal(result.context,paragraph.textContent);assert.equal(result.type,'grammar');assert.equal(api.classify('V-기에 + 좋은/편한/어려운 장소·방법'),'grammar');assert.equal(api.classify('고양이'),'word')});
test('explicit popup edit is saved literally and the native range menu is available',()=>{const source=fs.readFileSync('learning-features.js','utf8');assert.match(source,/const word=String\(edited\?\?term\?\?''\)\.trim\(\)/);assert.match(source,/\.selectionBar\.show\{display:flex!important/);assert.match(source,/user-select:text!important/);assert.match(source,/context:pendingVocab\?\.context/)});
test('legacy fallback does not call unchecked translation when vocabulary modules fail',()=>{const core=fs.readFileSync('legacy-core.js','utf8'),reveal=core.slice(core.indexOf('async function revealVocab'),core.indexOf('function deleteVocab'));assert.match(reveal,/MALBIT_VOCAB_TRANSLATION/);assert.doesNotMatch(reveal,/translateCached/)});
test('localized saving guide describes native range selection, preview and exact preservation',()=>{const source=fs.readFileSync('learning-features.js','utf8'),guide=source.slice(source.indexOf('function showVocabGuide(){'),source.indexOf('window.showVocabGuide='));for(const word of ['선택 핸들','選択ハンドル','selection handles','选择手柄','미리보기','プレビュー','preview','预览'])assert.ok(guide.includes(word));assert.doesNotMatch(guide,/0\.5|instead of the browser copy menu|브라우저 복사 메뉴 대신|친구를 → 친구|보지도 못한 →/);assert.match(guide,/not shortened automatically/)});
test('public-source detection matches exact text and same original context, never metadata labels',()=>{const c=runtime();c.MALBIT_SHORTS_DECKS={1:[{term:'배',example:'배를 타요.'}]};const f=c.MALBIT_VOCAB_TRANSLATION.publicEntry;assert.equal(f({text:'배',context:'배를 타요.'}),true);assert.equal(f({text:'배',context:'배를 먹어요.',source:'TOPIK I'}),false);assert.equal(f({text:'비공개 이름',source:'TOPIK II'}),false)});
test('potential personal identifiers are rejected before sending or verification',async()=>{const c=runtime();configure(c);c.MALBIT_TRANSLATION_CONFIG.getTurnstileToken=()=>{throw Error('Should not request token')};await assert.rejects(c.MALBIT_VOCAB_TRANSLATION.resolve({text:'문의',context:'test@example.com으로 보내세요'},'en'),/Invalid translation input/)});
test('production bridge includes localized preview, explicit approval and cancellation before Turnstile',()=>{assert.match(source,/dialog\.showModal\(\)/);assert.match(source,/preview\.textContent=input\.term/);assert.match(source,/confirm\.onclick=async/);assert.match(source,/Translation cancelled/);for(const term of ['이 내용으로 번역','この内容で翻訳','Translate this text','翻译这些内容'])assert.ok(source.includes(term));assert.match(source,/enabled:false/);assert.match(source,/https:\/\/harumal-vocabulary\.okometsbu\.workers\.dev\/v1\/vocabulary/);assert.match(source,/0x4AAAAAAFR8zumesIyXF9zt/);assert.doesNotMatch(source,/api\.mymemory\.translated/)});
function modalRuntime(){const c=runtime(async()=>({ok:true,json:async()=>cloudResult()}));const elements=[];class Element{constructor(tag){this.tag=tag;this.children=[];this.style={};this.listeners={};elements.push(this)}append(...nodes){this.children.push(...nodes)}appendChild(node){this.append(node)}setAttribute(){}addEventListener(name,fn){this.listeners[name]=fn}focus(){}showModal(){this.open=true}close(){this.open=false;this.listeners.close?.()}remove(){this.removed=true}}c.document={activeElement:new Element('old'),createElement:tag=>new Element(tag),head:new Element('head'),body:new Element('body')};c.MALBIT_TRANSLATION_CONFIG={enabled:true,endpoint:'https://translate.example/v1/vocabulary',turnstileSitekey:'mock-site'};return{c,elements}}
test('actual consent bridge cancel closes modal and performs no translation',async()=>{const {c,elements}=modalRuntime();c.fetch=()=>{throw Error('Must not send')};const pending=c.MALBIT_VOCAB_TRANSLATION.resolve({text:'학교'},'en');const dialog=elements.find(e=>e.tag==='dialog');assert.equal(dialog.open,true);elements.filter(e=>e.tag==='button')[1].onclick();await assert.rejects(pending,/cancelled/);assert.equal(dialog.removed,true)});
test('actual bridge submits only after explicit approval and a verification token',async()=>{const {c,elements}=modalRuntime();let calls=0,verification=0;c.fetch=async(_url,options)=>{calls++;const body=JSON.parse(options.body);assert.equal(body.term,'학교');assert.equal(body.learningTextApproved,true);assert.equal(body.turnstileToken,'verified');return{ok:true,json:async()=>cloudResult()}};c.turnstile={render(_node,opts){verification++;queueMicrotask(()=>opts.callback('verified'));return 0},remove(){}};const pending=c.MALBIT_VOCAB_TRANSLATION.resolve({text:'학교'},'en');assert.equal(calls,0);assert.equal(verification,0);await elements.filter(e=>e.tag==='button')[0].onclick();const result=await pending;assert.equal(result.value,'school');assert.equal(calls,1);assert.equal(verification,1);assert.equal(elements.find(e=>e.tag==='dialog').removed,true)});

test('real public connection is present but inactive until release approval',async()=>{const c=runtime();assert.equal(c.MALBIT_TRANSLATION_CONFIG.enabled,false);assert.equal(c.MALBIT_TRANSLATION_CONFIG.endpoint,'https://harumal-vocabulary.okometsbu.workers.dev/v1/vocabulary');assert.equal(c.MALBIT_TRANSLATION_CONFIG.turnstileSitekey,'0x4AAAAAAFR8zumesIyXF9zt');await assert.rejects(c.MALBIT_VOCAB_TRANSLATION.resolve({text:'새로운말'},'ja'),/not configured/);const config=JSON.parse(fs.readFileSync('services/vocabulary-worker/wrangler.jsonc','utf8'));assert.equal(config.workers_dev,true);assert.equal(config.vars.FREE_PLAN_VERIFIED,'true');assert.equal(config.vars.ENABLED,'false');assert.equal(config.vars.ALLOWED_ORIGINS,'https://okometsbu-beep.github.io');assert.equal(config.ai.binding,'AI');assert.equal(config.ratelimits[0].name,'RATE_LIMITER');assert.equal(config.vars.TURNSTILE_SECRET,undefined)});
